/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.etask.service.base;

import br.com.prodevelopment.etask.model.TypeTaskUsers;
import br.com.prodevelopment.etask.service.TypeTaskUsersService;
import br.com.prodevelopment.etask.service.persistence.TypeTaskPersistence;
import br.com.prodevelopment.etask.service.persistence.TypeTaskUsersPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the type task users remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link br.com.prodevelopment.etask.service.impl.TypeTaskUsersServiceImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see br.com.prodevelopment.etask.service.impl.TypeTaskUsersServiceImpl
 * @see br.com.prodevelopment.etask.service.TypeTaskUsersServiceUtil
 * @generated
 */
public abstract class TypeTaskUsersServiceBaseImpl extends BaseServiceImpl
	implements TypeTaskUsersService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link br.com.prodevelopment.etask.service.TypeTaskUsersServiceUtil} to access the type task users remote service.
	 */

	/**
	 * Returns the type task local service.
	 *
	 * @return the type task local service
	 */
	public br.com.prodevelopment.etask.service.TypeTaskLocalService getTypeTaskLocalService() {
		return typeTaskLocalService;
	}

	/**
	 * Sets the type task local service.
	 *
	 * @param typeTaskLocalService the type task local service
	 */
	public void setTypeTaskLocalService(
		br.com.prodevelopment.etask.service.TypeTaskLocalService typeTaskLocalService) {
		this.typeTaskLocalService = typeTaskLocalService;
	}

	/**
	 * Returns the type task remote service.
	 *
	 * @return the type task remote service
	 */
	public br.com.prodevelopment.etask.service.TypeTaskService getTypeTaskService() {
		return typeTaskService;
	}

	/**
	 * Sets the type task remote service.
	 *
	 * @param typeTaskService the type task remote service
	 */
	public void setTypeTaskService(
		br.com.prodevelopment.etask.service.TypeTaskService typeTaskService) {
		this.typeTaskService = typeTaskService;
	}

	/**
	 * Returns the type task persistence.
	 *
	 * @return the type task persistence
	 */
	public TypeTaskPersistence getTypeTaskPersistence() {
		return typeTaskPersistence;
	}

	/**
	 * Sets the type task persistence.
	 *
	 * @param typeTaskPersistence the type task persistence
	 */
	public void setTypeTaskPersistence(TypeTaskPersistence typeTaskPersistence) {
		this.typeTaskPersistence = typeTaskPersistence;
	}

	/**
	 * Returns the type task users local service.
	 *
	 * @return the type task users local service
	 */
	public br.com.prodevelopment.etask.service.TypeTaskUsersLocalService getTypeTaskUsersLocalService() {
		return typeTaskUsersLocalService;
	}

	/**
	 * Sets the type task users local service.
	 *
	 * @param typeTaskUsersLocalService the type task users local service
	 */
	public void setTypeTaskUsersLocalService(
		br.com.prodevelopment.etask.service.TypeTaskUsersLocalService typeTaskUsersLocalService) {
		this.typeTaskUsersLocalService = typeTaskUsersLocalService;
	}

	/**
	 * Returns the type task users remote service.
	 *
	 * @return the type task users remote service
	 */
	public br.com.prodevelopment.etask.service.TypeTaskUsersService getTypeTaskUsersService() {
		return typeTaskUsersService;
	}

	/**
	 * Sets the type task users remote service.
	 *
	 * @param typeTaskUsersService the type task users remote service
	 */
	public void setTypeTaskUsersService(
		br.com.prodevelopment.etask.service.TypeTaskUsersService typeTaskUsersService) {
		this.typeTaskUsersService = typeTaskUsersService;
	}

	/**
	 * Returns the type task users persistence.
	 *
	 * @return the type task users persistence
	 */
	public TypeTaskUsersPersistence getTypeTaskUsersPersistence() {
		return typeTaskUsersPersistence;
	}

	/**
	 * Sets the type task users persistence.
	 *
	 * @param typeTaskUsersPersistence the type task users persistence
	 */
	public void setTypeTaskUsersPersistence(
		TypeTaskUsersPersistence typeTaskUsersPersistence) {
		this.typeTaskUsersPersistence = typeTaskUsersPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return TypeTaskUsers.class;
	}

	protected String getModelClassName() {
		return TypeTaskUsers.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = typeTaskUsersPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = br.com.prodevelopment.etask.service.TypeTaskLocalService.class)
	protected br.com.prodevelopment.etask.service.TypeTaskLocalService typeTaskLocalService;
	@BeanReference(type = br.com.prodevelopment.etask.service.TypeTaskService.class)
	protected br.com.prodevelopment.etask.service.TypeTaskService typeTaskService;
	@BeanReference(type = TypeTaskPersistence.class)
	protected TypeTaskPersistence typeTaskPersistence;
	@BeanReference(type = br.com.prodevelopment.etask.service.TypeTaskUsersLocalService.class)
	protected br.com.prodevelopment.etask.service.TypeTaskUsersLocalService typeTaskUsersLocalService;
	@BeanReference(type = br.com.prodevelopment.etask.service.TypeTaskUsersService.class)
	protected br.com.prodevelopment.etask.service.TypeTaskUsersService typeTaskUsersService;
	@BeanReference(type = TypeTaskUsersPersistence.class)
	protected TypeTaskUsersPersistence typeTaskUsersPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private TypeTaskUsersServiceClpInvoker _clpInvoker = new TypeTaskUsersServiceClpInvoker();
}