/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.appcomercial.servico.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Funcionario service. Represents a row in the &quot;Funcionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.appcomercial.servico.model.impl.FuncionarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.appcomercial.servico.model.impl.FuncionarioImpl}.
 * </p>
 *
 * @author marcelo
 * @see Funcionario
 * @see br.com.prodevelopment.appcomercial.servico.model.impl.FuncionarioImpl
 * @see br.com.prodevelopment.appcomercial.servico.model.impl.FuncionarioModelImpl
 * @generated
 */
public interface FuncionarioModel extends BaseModel<Funcionario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funcionario model instance should use the {@link Funcionario} interface instead.
	 */

	/**
	 * Returns the primary key of this funcionario.
	 *
	 * @return the primary key of this funcionario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this funcionario.
	 *
	 * @param primaryKey the primary key of this funcionario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the funcionario ID of this funcionario.
	 *
	 * @return the funcionario ID of this funcionario
	 */
	public long getFuncionarioId();

	/**
	 * Sets the funcionario ID of this funcionario.
	 *
	 * @param funcionarioId the funcionario ID of this funcionario
	 */
	public void setFuncionarioId(long funcionarioId);

	/**
	 * Returns the company ID of this funcionario.
	 *
	 * @return the company ID of this funcionario
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this funcionario.
	 *
	 * @param companyId the company ID of this funcionario
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this funcionario.
	 *
	 * @return the group ID of this funcionario
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this funcionario.
	 *
	 * @param groupId the group ID of this funcionario
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this funcionario.
	 *
	 * @return the create user ID of this funcionario
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this funcionario.
	 *
	 * @param createUserId the create user ID of this funcionario
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this funcionario.
	 *
	 * @return the create user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this funcionario.
	 *
	 * @param createUserUuid the create user uuid of this funcionario
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this funcionario.
	 *
	 * @return the modified user ID of this funcionario
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this funcionario.
	 *
	 * @param modifiedUserId the modified user ID of this funcionario
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this funcionario.
	 *
	 * @return the modified user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this funcionario.
	 *
	 * @param modifiedUserUuid the modified user uuid of this funcionario
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this funcionario.
	 *
	 * @return the create date of this funcionario
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this funcionario.
	 *
	 * @param createDate the create date of this funcionario
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this funcionario.
	 *
	 * @return the modified date of this funcionario
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this funcionario.
	 *
	 * @param modifiedDate the modified date of this funcionario
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this funcionario.
	 *
	 * @return the nome of this funcionario
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this funcionario.
	 *
	 * @param nome the nome of this funcionario
	 */
	public void setNome(String nome);

	/**
	 * Returns the apelido of this funcionario.
	 *
	 * @return the apelido of this funcionario
	 */
	@AutoEscape
	public String getApelido();

	/**
	 * Sets the apelido of this funcionario.
	 *
	 * @param apelido the apelido of this funcionario
	 */
	public void setApelido(String apelido);

	/**
	 * Returns the observacao of this funcionario.
	 *
	 * @return the observacao of this funcionario
	 */
	@AutoEscape
	public String getObservacao();

	/**
	 * Sets the observacao of this funcionario.
	 *
	 * @param observacao the observacao of this funcionario
	 */
	public void setObservacao(String observacao);

	/**
	 * Returns the rg of this funcionario.
	 *
	 * @return the rg of this funcionario
	 */
	@AutoEscape
	public String getRg();

	/**
	 * Sets the rg of this funcionario.
	 *
	 * @param rg the rg of this funcionario
	 */
	public void setRg(String rg);

	/**
	 * Returns the rg orgao emissor of this funcionario.
	 *
	 * @return the rg orgao emissor of this funcionario
	 */
	@AutoEscape
	public String getRgOrgaoEmissor();

	/**
	 * Sets the rg orgao emissor of this funcionario.
	 *
	 * @param rgOrgaoEmissor the rg orgao emissor of this funcionario
	 */
	public void setRgOrgaoEmissor(String rgOrgaoEmissor);

	/**
	 * Returns the rg data emissao of this funcionario.
	 *
	 * @return the rg data emissao of this funcionario
	 */
	public Date getRgDataEmissao();

	/**
	 * Sets the rg data emissao of this funcionario.
	 *
	 * @param rgDataEmissao the rg data emissao of this funcionario
	 */
	public void setRgDataEmissao(Date rgDataEmissao);

	/**
	 * Returns the cpf of this funcionario.
	 *
	 * @return the cpf of this funcionario
	 */
	@AutoEscape
	public String getCpf();

	/**
	 * Sets the cpf of this funcionario.
	 *
	 * @param cpf the cpf of this funcionario
	 */
	public void setCpf(String cpf);

	/**
	 * Returns the sexo of this funcionario.
	 *
	 * @return the sexo of this funcionario
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this funcionario.
	 *
	 * @param sexo the sexo of this funcionario
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the estado civil of this funcionario.
	 *
	 * @return the estado civil of this funcionario
	 */
	@AutoEscape
	public String getEstadoCivil();

	/**
	 * Sets the estado civil of this funcionario.
	 *
	 * @param estadoCivil the estado civil of this funcionario
	 */
	public void setEstadoCivil(String estadoCivil);

	/**
	 * Returns the data nascimento of this funcionario.
	 *
	 * @return the data nascimento of this funcionario
	 */
	public Date getDataNascimento();

	/**
	 * Sets the data nascimento of this funcionario.
	 *
	 * @param dataNascimento the data nascimento of this funcionario
	 */
	public void setDataNascimento(Date dataNascimento);

	/**
	 * Returns the end com logradouro of this funcionario.
	 *
	 * @return the end com logradouro of this funcionario
	 */
	@AutoEscape
	public String getEndComLogradouro();

	/**
	 * Sets the end com logradouro of this funcionario.
	 *
	 * @param endComLogradouro the end com logradouro of this funcionario
	 */
	public void setEndComLogradouro(String endComLogradouro);

	/**
	 * Returns the end com descricao of this funcionario.
	 *
	 * @return the end com descricao of this funcionario
	 */
	@AutoEscape
	public String getEndComDescricao();

	/**
	 * Sets the end com descricao of this funcionario.
	 *
	 * @param endComDescricao the end com descricao of this funcionario
	 */
	public void setEndComDescricao(String endComDescricao);

	/**
	 * Returns the end com cep of this funcionario.
	 *
	 * @return the end com cep of this funcionario
	 */
	@AutoEscape
	public String getEndComCep();

	/**
	 * Sets the end com cep of this funcionario.
	 *
	 * @param endComCep the end com cep of this funcionario
	 */
	public void setEndComCep(String endComCep);

	/**
	 * Returns the end com bairro of this funcionario.
	 *
	 * @return the end com bairro of this funcionario
	 */
	@AutoEscape
	public String getEndComBairro();

	/**
	 * Sets the end com bairro of this funcionario.
	 *
	 * @param endComBairro the end com bairro of this funcionario
	 */
	public void setEndComBairro(String endComBairro);

	/**
	 * Returns the end com cidade of this funcionario.
	 *
	 * @return the end com cidade of this funcionario
	 */
	@AutoEscape
	public String getEndComCidade();

	/**
	 * Sets the end com cidade of this funcionario.
	 *
	 * @param endComCidade the end com cidade of this funcionario
	 */
	public void setEndComCidade(String endComCidade);

	/**
	 * Returns the end com uf of this funcionario.
	 *
	 * @return the end com uf of this funcionario
	 */
	@AutoEscape
	public String getEndComUf();

	/**
	 * Sets the end com uf of this funcionario.
	 *
	 * @param endComUf the end com uf of this funcionario
	 */
	public void setEndComUf(String endComUf);

	/**
	 * Returns the end com pais of this funcionario.
	 *
	 * @return the end com pais of this funcionario
	 */
	@AutoEscape
	public String getEndComPais();

	/**
	 * Sets the end com pais of this funcionario.
	 *
	 * @param endComPais the end com pais of this funcionario
	 */
	public void setEndComPais(String endComPais);

	/**
	 * Returns the end res logradouro of this funcionario.
	 *
	 * @return the end res logradouro of this funcionario
	 */
	@AutoEscape
	public String getEndResLogradouro();

	/**
	 * Sets the end res logradouro of this funcionario.
	 *
	 * @param endResLogradouro the end res logradouro of this funcionario
	 */
	public void setEndResLogradouro(String endResLogradouro);

	/**
	 * Returns the end res descricao of this funcionario.
	 *
	 * @return the end res descricao of this funcionario
	 */
	@AutoEscape
	public String getEndResDescricao();

	/**
	 * Sets the end res descricao of this funcionario.
	 *
	 * @param endResDescricao the end res descricao of this funcionario
	 */
	public void setEndResDescricao(String endResDescricao);

	/**
	 * Returns the end res cep of this funcionario.
	 *
	 * @return the end res cep of this funcionario
	 */
	@AutoEscape
	public String getEndResCep();

	/**
	 * Sets the end res cep of this funcionario.
	 *
	 * @param endResCep the end res cep of this funcionario
	 */
	public void setEndResCep(String endResCep);

	/**
	 * Returns the end res bairro of this funcionario.
	 *
	 * @return the end res bairro of this funcionario
	 */
	@AutoEscape
	public String getEndResBairro();

	/**
	 * Sets the end res bairro of this funcionario.
	 *
	 * @param endResBairro the end res bairro of this funcionario
	 */
	public void setEndResBairro(String endResBairro);

	/**
	 * Returns the end res cidade of this funcionario.
	 *
	 * @return the end res cidade of this funcionario
	 */
	@AutoEscape
	public String getEndResCidade();

	/**
	 * Sets the end res cidade of this funcionario.
	 *
	 * @param endResCidade the end res cidade of this funcionario
	 */
	public void setEndResCidade(String endResCidade);

	/**
	 * Returns the end res uf of this funcionario.
	 *
	 * @return the end res uf of this funcionario
	 */
	@AutoEscape
	public String getEndResUf();

	/**
	 * Sets the end res uf of this funcionario.
	 *
	 * @param endResUf the end res uf of this funcionario
	 */
	public void setEndResUf(String endResUf);

	/**
	 * Returns the end res pais of this funcionario.
	 *
	 * @return the end res pais of this funcionario
	 */
	@AutoEscape
	public String getEndResPais();

	/**
	 * Sets the end res pais of this funcionario.
	 *
	 * @param endResPais the end res pais of this funcionario
	 */
	public void setEndResPais(String endResPais);

	/**
	 * Returns the tel com ddd of this funcionario.
	 *
	 * @return the tel com ddd of this funcionario
	 */
	@AutoEscape
	public String getTelComDdd();

	/**
	 * Sets the tel com ddd of this funcionario.
	 *
	 * @param telComDdd the tel com ddd of this funcionario
	 */
	public void setTelComDdd(String telComDdd);

	/**
	 * Returns the tel com numero of this funcionario.
	 *
	 * @return the tel com numero of this funcionario
	 */
	@AutoEscape
	public String getTelComNumero();

	/**
	 * Sets the tel com numero of this funcionario.
	 *
	 * @param telComNumero the tel com numero of this funcionario
	 */
	public void setTelComNumero(String telComNumero);

	/**
	 * Returns the tel com ramal of this funcionario.
	 *
	 * @return the tel com ramal of this funcionario
	 */
	@AutoEscape
	public String getTelComRamal();

	/**
	 * Sets the tel com ramal of this funcionario.
	 *
	 * @param telComRamal the tel com ramal of this funcionario
	 */
	public void setTelComRamal(String telComRamal);

	/**
	 * Returns the tel res ddd of this funcionario.
	 *
	 * @return the tel res ddd of this funcionario
	 */
	@AutoEscape
	public String getTelResDdd();

	/**
	 * Sets the tel res ddd of this funcionario.
	 *
	 * @param telResDdd the tel res ddd of this funcionario
	 */
	public void setTelResDdd(String telResDdd);

	/**
	 * Returns the tel res numero of this funcionario.
	 *
	 * @return the tel res numero of this funcionario
	 */
	@AutoEscape
	public String getTelResNumero();

	/**
	 * Sets the tel res numero of this funcionario.
	 *
	 * @param telResNumero the tel res numero of this funcionario
	 */
	public void setTelResNumero(String telResNumero);

	/**
	 * Returns the tel cel ddd of this funcionario.
	 *
	 * @return the tel cel ddd of this funcionario
	 */
	@AutoEscape
	public String getTelCelDdd();

	/**
	 * Sets the tel cel ddd of this funcionario.
	 *
	 * @param telCelDdd the tel cel ddd of this funcionario
	 */
	public void setTelCelDdd(String telCelDdd);

	/**
	 * Returns the tel cel numero of this funcionario.
	 *
	 * @return the tel cel numero of this funcionario
	 */
	@AutoEscape
	public String getTelCelNumero();

	/**
	 * Sets the tel cel numero of this funcionario.
	 *
	 * @param telCelNumero the tel cel numero of this funcionario
	 */
	public void setTelCelNumero(String telCelNumero);

	/**
	 * Returns the end email of this funcionario.
	 *
	 * @return the end email of this funcionario
	 */
	@AutoEscape
	public String getEndEmail();

	/**
	 * Sets the end email of this funcionario.
	 *
	 * @param endEmail the end email of this funcionario
	 */
	public void setEndEmail(String endEmail);

	/**
	 * Returns the data entrada of this funcionario.
	 *
	 * @return the data entrada of this funcionario
	 */
	public Date getDataEntrada();

	/**
	 * Sets the data entrada of this funcionario.
	 *
	 * @param dataEntrada the data entrada of this funcionario
	 */
	public void setDataEntrada(Date dataEntrada);

	/**
	 * Returns the data saida of this funcionario.
	 *
	 * @return the data saida of this funcionario
	 */
	public Date getDataSaida();

	/**
	 * Sets the data saida of this funcionario.
	 *
	 * @param dataSaida the data saida of this funcionario
	 */
	public void setDataSaida(Date dataSaida);

	/**
	 * Returns the existe user of this funcionario.
	 *
	 * @return the existe user of this funcionario
	 */
	public Boolean getExisteUser();

	/**
	 * Sets the existe user of this funcionario.
	 *
	 * @param existeUser the existe user of this funcionario
	 */
	public void setExisteUser(Boolean existeUser);

	/**
	 * Returns the user ID of this funcionario.
	 *
	 * @return the user ID of this funcionario
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this funcionario.
	 *
	 * @param userId the user ID of this funcionario
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this funcionario.
	 *
	 * @return the user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this funcionario.
	 *
	 * @param userUuid the user uuid of this funcionario
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Funcionario funcionario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Funcionario> toCacheModel();

	@Override
	public Funcionario toEscapedModel();

	@Override
	public Funcionario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}