/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.testeconhecimento.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Resposta_Usuario service. Represents a row in the &quot;TC_Resposta_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.testeconhecimento.model.impl.Resposta_UsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.testeconhecimento.model.impl.Resposta_UsuarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Resposta_Usuario
 * @see br.com.prodevelopment.testeconhecimento.model.impl.Resposta_UsuarioImpl
 * @see br.com.prodevelopment.testeconhecimento.model.impl.Resposta_UsuarioModelImpl
 * @generated
 */
public interface Resposta_UsuarioModel extends BaseModel<Resposta_Usuario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a resposta_ usuario model instance should use the {@link Resposta_Usuario} interface instead.
	 */

	/**
	 * Returns the primary key of this resposta_ usuario.
	 *
	 * @return the primary key of this resposta_ usuario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this resposta_ usuario.
	 *
	 * @param primaryKey the primary key of this resposta_ usuario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this resposta_ usuario.
	 *
	 * @return the ID of this resposta_ usuario
	 */
	public long getId();

	/**
	 * Sets the ID of this resposta_ usuario.
	 *
	 * @param id the ID of this resposta_ usuario
	 */
	public void setId(long id);

	/**
	 * Returns the correta of this resposta_ usuario.
	 *
	 * @return the correta of this resposta_ usuario
	 */
	public boolean getCorreta();

	/**
	 * Returns <code>true</code> if this resposta_ usuario is correta.
	 *
	 * @return <code>true</code> if this resposta_ usuario is correta; <code>false</code> otherwise
	 */
	public boolean isCorreta();

	/**
	 * Sets whether this resposta_ usuario is correta.
	 *
	 * @param correta the correta of this resposta_ usuario
	 */
	public void setCorreta(boolean correta);

	/**
	 * Returns the data inclusao of this resposta_ usuario.
	 *
	 * @return the data inclusao of this resposta_ usuario
	 */
	public Date getDataInclusao();

	/**
	 * Sets the data inclusao of this resposta_ usuario.
	 *
	 * @param dataInclusao the data inclusao of this resposta_ usuario
	 */
	public void setDataInclusao(Date dataInclusao);

	/**
	 * Returns the teste usuario ID of this resposta_ usuario.
	 *
	 * @return the teste usuario ID of this resposta_ usuario
	 */
	public long getTesteUsuarioId();

	/**
	 * Sets the teste usuario ID of this resposta_ usuario.
	 *
	 * @param testeUsuarioId the teste usuario ID of this resposta_ usuario
	 */
	public void setTesteUsuarioId(long testeUsuarioId);

	/**
	 * Returns the resposta ID of this resposta_ usuario.
	 *
	 * @return the resposta ID of this resposta_ usuario
	 */
	public long getRespostaId();

	/**
	 * Sets the resposta ID of this resposta_ usuario.
	 *
	 * @param respostaId the resposta ID of this resposta_ usuario
	 */
	public void setRespostaId(long respostaId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Resposta_Usuario resposta_Usuario);

	public int hashCode();

	public CacheModel<Resposta_Usuario> toCacheModel();

	public Resposta_Usuario toEscapedModel();

	public String toString();

	public String toXmlString();
}