/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.pesquisaopiniao.model.impl;

import br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario;
import br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_UsuarioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Pesquisa_Usuario service. Represents a row in the &quot;PO_Pesquisa_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_UsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Pesquisa_UsuarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Pesquisa_UsuarioImpl
 * @see br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario
 * @see br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_UsuarioModel
 * @generated
 */
public class Pesquisa_UsuarioModelImpl extends BaseModelImpl<Pesquisa_Usuario>
	implements Pesquisa_UsuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pesquisa_ usuario model instance should use the {@link br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario} interface instead.
	 */
	public static final String TABLE_NAME = "PO_Pesquisa_Usuario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "nome", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "dataInclusao", Types.TIMESTAMP },
			{ "pesquisaId", Types.BIGINT },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table PO_Pesquisa_Usuario (id_ LONG not null primary key,nome VARCHAR(75) null,email VARCHAR(75) null,dataInclusao DATE null,pesquisaId LONG,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table PO_Pesquisa_Usuario";
	public static final String ORDER_BY_JPQL = " ORDER BY pesquisa_Usuario.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PO_Pesquisa_Usuario.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario"),
			true);
	public static long PESQUISAID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario"));

	public Pesquisa_UsuarioModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Pesquisa_Usuario.class;
	}

	public String getModelClassName() {
		return Pesquisa_Usuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("nome", getNome());
		attributes.put("email", getEmail());
		attributes.put("dataInclusao", getDataInclusao());
		attributes.put("pesquisaId", getPesquisaId());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		Date dataInclusao = (Date)attributes.get("dataInclusao");

		if (dataInclusao != null) {
			setDataInclusao(dataInclusao);
		}

		Long pesquisaId = (Long)attributes.get("pesquisaId");

		if (pesquisaId != null) {
			setPesquisaId(pesquisaId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	public void setNome(String nome) {
		_nome = nome;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public Date getDataInclusao() {
		return _dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		_dataInclusao = dataInclusao;
	}

	public long getPesquisaId() {
		return _pesquisaId;
	}

	public void setPesquisaId(long pesquisaId) {
		_columnBitmask |= PESQUISAID_COLUMN_BITMASK;

		if (!_setOriginalPesquisaId) {
			_setOriginalPesquisaId = true;

			_originalPesquisaId = _pesquisaId;
		}

		_pesquisaId = pesquisaId;
	}

	public long getOriginalPesquisaId() {
		return _originalPesquisaId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Pesquisa_Usuario.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Pesquisa_Usuario toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Pesquisa_Usuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		Pesquisa_UsuarioImpl pesquisa_UsuarioImpl = new Pesquisa_UsuarioImpl();

		pesquisa_UsuarioImpl.setId(getId());
		pesquisa_UsuarioImpl.setNome(getNome());
		pesquisa_UsuarioImpl.setEmail(getEmail());
		pesquisa_UsuarioImpl.setDataInclusao(getDataInclusao());
		pesquisa_UsuarioImpl.setPesquisaId(getPesquisaId());
		pesquisa_UsuarioImpl.setUserId(getUserId());

		pesquisa_UsuarioImpl.resetOriginalValues();

		return pesquisa_UsuarioImpl;
	}

	public int compareTo(Pesquisa_Usuario pesquisa_Usuario) {
		int value = 0;

		if (getId() < pesquisa_Usuario.getId()) {
			value = -1;
		}
		else if (getId() > pesquisa_Usuario.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Pesquisa_Usuario pesquisa_Usuario = null;

		try {
			pesquisa_Usuario = (Pesquisa_Usuario)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = pesquisa_Usuario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Pesquisa_UsuarioModelImpl pesquisa_UsuarioModelImpl = this;

		pesquisa_UsuarioModelImpl._originalPesquisaId = pesquisa_UsuarioModelImpl._pesquisaId;

		pesquisa_UsuarioModelImpl._setOriginalPesquisaId = false;

		pesquisa_UsuarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Pesquisa_Usuario> toCacheModel() {
		Pesquisa_UsuarioCacheModel pesquisa_UsuarioCacheModel = new Pesquisa_UsuarioCacheModel();

		pesquisa_UsuarioCacheModel.id = getId();

		pesquisa_UsuarioCacheModel.nome = getNome();

		String nome = pesquisa_UsuarioCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			pesquisa_UsuarioCacheModel.nome = null;
		}

		pesquisa_UsuarioCacheModel.email = getEmail();

		String email = pesquisa_UsuarioCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			pesquisa_UsuarioCacheModel.email = null;
		}

		Date dataInclusao = getDataInclusao();

		if (dataInclusao != null) {
			pesquisa_UsuarioCacheModel.dataInclusao = dataInclusao.getTime();
		}
		else {
			pesquisa_UsuarioCacheModel.dataInclusao = Long.MIN_VALUE;
		}

		pesquisa_UsuarioCacheModel.pesquisaId = getPesquisaId();

		pesquisa_UsuarioCacheModel.userId = getUserId();

		return pesquisa_UsuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", dataInclusao=");
		sb.append(getDataInclusao());
		sb.append(", pesquisaId=");
		sb.append(getPesquisaId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append(
			"br.com.prodevelopment.pesquisaopiniao.model.Pesquisa_Usuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataInclusao</column-name><column-value><![CDATA[");
		sb.append(getDataInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pesquisaId</column-name><column-value><![CDATA[");
		sb.append(getPesquisaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Pesquisa_Usuario.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Pesquisa_Usuario.class
		};
	private long _id;
	private String _nome;
	private String _email;
	private Date _dataInclusao;
	private long _pesquisaId;
	private long _originalPesquisaId;
	private boolean _setOriginalPesquisaId;
	private long _userId;
	private String _userUuid;
	private long _columnBitmask;
	private Pesquisa_Usuario _escapedModelProxy;
}