/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.testeconhecimento.model.impl;

import br.com.prodevelopment.testeconhecimento.model.Pergunta;
import br.com.prodevelopment.testeconhecimento.model.PerguntaModel;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the Pergunta service. Represents a row in the &quot;TC_Pergunta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.testeconhecimento.model.PerguntaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PerguntaImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see PerguntaImpl
 * @see br.com.prodevelopment.testeconhecimento.model.Pergunta
 * @see br.com.prodevelopment.testeconhecimento.model.PerguntaModel
 * @generated
 */
public class PerguntaModelImpl extends BaseModelImpl<Pergunta>
	implements PerguntaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pergunta model instance should use the {@link br.com.prodevelopment.testeconhecimento.model.Pergunta} interface instead.
	 */
	public static final String TABLE_NAME = "TC_Pergunta";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "descricao", Types.VARCHAR },
			{ "justificativaResposta", Types.VARCHAR },
			{ "pontuacao", Types.DOUBLE },
			{ "dataInclusao", Types.TIMESTAMP },
			{ "dataAlteracao", Types.TIMESTAMP },
			{ "testeId", Types.BIGINT },
			{ "userIdInclusao", Types.BIGINT },
			{ "userIdAlteracao", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table TC_Pergunta (id_ LONG not null primary key,descricao STRING null,justificativaResposta STRING null,pontuacao DOUBLE,dataInclusao DATE null,dataAlteracao DATE null,testeId LONG,userIdInclusao LONG,userIdAlteracao LONG)";
	public static final String TABLE_SQL_DROP = "drop table TC_Pergunta";
	public static final String ORDER_BY_JPQL = " ORDER BY pergunta.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TC_Pergunta.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Pergunta"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Pergunta"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.testeconhecimento.model.Pergunta"),
			true);
	public static long TESTEID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.testeconhecimento.model.Pergunta"));

	public PerguntaModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Pergunta.class;
	}

	public String getModelClassName() {
		return Pergunta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("descricao", getDescricao());
		attributes.put("justificativaResposta", getJustificativaResposta());
		attributes.put("pontuacao", getPontuacao());
		attributes.put("dataInclusao", getDataInclusao());
		attributes.put("dataAlteracao", getDataAlteracao());
		attributes.put("testeId", getTesteId());
		attributes.put("userIdInclusao", getUserIdInclusao());
		attributes.put("userIdAlteracao", getUserIdAlteracao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String descricao = (String)attributes.get("descricao");

		if (descricao != null) {
			setDescricao(descricao);
		}

		String justificativaResposta = (String)attributes.get(
				"justificativaResposta");

		if (justificativaResposta != null) {
			setJustificativaResposta(justificativaResposta);
		}

		Double pontuacao = (Double)attributes.get("pontuacao");

		if (pontuacao != null) {
			setPontuacao(pontuacao);
		}

		Date dataInclusao = (Date)attributes.get("dataInclusao");

		if (dataInclusao != null) {
			setDataInclusao(dataInclusao);
		}

		Date dataAlteracao = (Date)attributes.get("dataAlteracao");

		if (dataAlteracao != null) {
			setDataAlteracao(dataAlteracao);
		}

		Long testeId = (Long)attributes.get("testeId");

		if (testeId != null) {
			setTesteId(testeId);
		}

		Long userIdInclusao = (Long)attributes.get("userIdInclusao");

		if (userIdInclusao != null) {
			setUserIdInclusao(userIdInclusao);
		}

		Long userIdAlteracao = (Long)attributes.get("userIdAlteracao");

		if (userIdAlteracao != null) {
			setUserIdAlteracao(userIdAlteracao);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getDescricao() {
		if (_descricao == null) {
			return StringPool.BLANK;
		}
		else {
			return _descricao;
		}
	}

	public String getDescricao(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescricao(languageId);
	}

	public String getDescricao(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescricao(languageId, useDefault);
	}

	public String getDescricao(String languageId) {
		return LocalizationUtil.getLocalization(getDescricao(), languageId);
	}

	public String getDescricao(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescricao(), languageId,
			useDefault);
	}

	public String getDescricaoCurrentLanguageId() {
		return _descricaoCurrentLanguageId;
	}

	@JSON
	public String getDescricaoCurrentValue() {
		Locale locale = getLocale(_descricaoCurrentLanguageId);

		return getDescricao(locale);
	}

	public Map<Locale, String> getDescricaoMap() {
		return LocalizationUtil.getLocalizationMap(getDescricao());
	}

	public void setDescricao(String descricao) {
		_descricao = descricao;
	}

	public void setDescricao(String descricao, Locale locale) {
		setDescricao(descricao, locale, LocaleUtil.getDefault());
	}

	public void setDescricao(String descricao, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(descricao)) {
			setDescricao(LocalizationUtil.updateLocalization(getDescricao(),
					"Descricao", descricao, languageId, defaultLanguageId));
		}
		else {
			setDescricao(LocalizationUtil.removeLocalization(getDescricao(),
					"Descricao", languageId));
		}
	}

	public void setDescricaoCurrentLanguageId(String languageId) {
		_descricaoCurrentLanguageId = languageId;
	}

	public void setDescricaoMap(Map<Locale, String> descricaoMap) {
		setDescricaoMap(descricaoMap, LocaleUtil.getDefault());
	}

	public void setDescricaoMap(Map<Locale, String> descricaoMap,
		Locale defaultLocale) {
		if (descricaoMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String descricao = descricaoMap.get(locale);

			setDescricao(descricao, locale, defaultLocale);
		}
	}

	public String getJustificativaResposta() {
		if (_justificativaResposta == null) {
			return StringPool.BLANK;
		}
		else {
			return _justificativaResposta;
		}
	}

	public String getJustificativaResposta(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getJustificativaResposta(languageId);
	}

	public String getJustificativaResposta(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getJustificativaResposta(languageId, useDefault);
	}

	public String getJustificativaResposta(String languageId) {
		return LocalizationUtil.getLocalization(getJustificativaResposta(),
			languageId);
	}

	public String getJustificativaResposta(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getJustificativaResposta(),
			languageId, useDefault);
	}

	public String getJustificativaRespostaCurrentLanguageId() {
		return _justificativaRespostaCurrentLanguageId;
	}

	@JSON
	public String getJustificativaRespostaCurrentValue() {
		Locale locale = getLocale(_justificativaRespostaCurrentLanguageId);

		return getJustificativaResposta(locale);
	}

	public Map<Locale, String> getJustificativaRespostaMap() {
		return LocalizationUtil.getLocalizationMap(getJustificativaResposta());
	}

	public void setJustificativaResposta(String justificativaResposta) {
		_justificativaResposta = justificativaResposta;
	}

	public void setJustificativaResposta(String justificativaResposta,
		Locale locale) {
		setJustificativaResposta(justificativaResposta, locale,
			LocaleUtil.getDefault());
	}

	public void setJustificativaResposta(String justificativaResposta,
		Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(justificativaResposta)) {
			setJustificativaResposta(LocalizationUtil.updateLocalization(
					getJustificativaResposta(), "JustificativaResposta",
					justificativaResposta, languageId, defaultLanguageId));
		}
		else {
			setJustificativaResposta(LocalizationUtil.removeLocalization(
					getJustificativaResposta(), "JustificativaResposta",
					languageId));
		}
	}

	public void setJustificativaRespostaCurrentLanguageId(String languageId) {
		_justificativaRespostaCurrentLanguageId = languageId;
	}

	public void setJustificativaRespostaMap(
		Map<Locale, String> justificativaRespostaMap) {
		setJustificativaRespostaMap(justificativaRespostaMap,
			LocaleUtil.getDefault());
	}

	public void setJustificativaRespostaMap(
		Map<Locale, String> justificativaRespostaMap, Locale defaultLocale) {
		if (justificativaRespostaMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String justificativaResposta = justificativaRespostaMap.get(locale);

			setJustificativaResposta(justificativaResposta, locale,
				defaultLocale);
		}
	}

	public double getPontuacao() {
		return _pontuacao;
	}

	public void setPontuacao(double pontuacao) {
		_pontuacao = pontuacao;
	}

	public Date getDataInclusao() {
		return _dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		_dataInclusao = dataInclusao;
	}

	public Date getDataAlteracao() {
		return _dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		_dataAlteracao = dataAlteracao;
	}

	public long getTesteId() {
		return _testeId;
	}

	public void setTesteId(long testeId) {
		_columnBitmask |= TESTEID_COLUMN_BITMASK;

		if (!_setOriginalTesteId) {
			_setOriginalTesteId = true;

			_originalTesteId = _testeId;
		}

		_testeId = testeId;
	}

	public long getOriginalTesteId() {
		return _originalTesteId;
	}

	public long getUserIdInclusao() {
		return _userIdInclusao;
	}

	public void setUserIdInclusao(long userIdInclusao) {
		_userIdInclusao = userIdInclusao;
	}

	public long getUserIdAlteracao() {
		return _userIdAlteracao;
	}

	public void setUserIdAlteracao(long userIdAlteracao) {
		_userIdAlteracao = userIdAlteracao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Pergunta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		setDescricao(getDescricao(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
		setJustificativaResposta(getJustificativaResposta(defaultImportLocale),
			defaultImportLocale, defaultImportLocale);
	}

	@Override
	public Pergunta toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Pergunta)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PerguntaImpl perguntaImpl = new PerguntaImpl();

		perguntaImpl.setId(getId());
		perguntaImpl.setDescricao(getDescricao());
		perguntaImpl.setJustificativaResposta(getJustificativaResposta());
		perguntaImpl.setPontuacao(getPontuacao());
		perguntaImpl.setDataInclusao(getDataInclusao());
		perguntaImpl.setDataAlteracao(getDataAlteracao());
		perguntaImpl.setTesteId(getTesteId());
		perguntaImpl.setUserIdInclusao(getUserIdInclusao());
		perguntaImpl.setUserIdAlteracao(getUserIdAlteracao());

		perguntaImpl.resetOriginalValues();

		return perguntaImpl;
	}

	public int compareTo(Pergunta pergunta) {
		int value = 0;

		if (getId() < pergunta.getId()) {
			value = -1;
		}
		else if (getId() > pergunta.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Pergunta pergunta = null;

		try {
			pergunta = (Pergunta)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = pergunta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PerguntaModelImpl perguntaModelImpl = this;

		perguntaModelImpl._originalTesteId = perguntaModelImpl._testeId;

		perguntaModelImpl._setOriginalTesteId = false;

		perguntaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Pergunta> toCacheModel() {
		PerguntaCacheModel perguntaCacheModel = new PerguntaCacheModel();

		perguntaCacheModel.id = getId();

		perguntaCacheModel.descricao = getDescricao();

		String descricao = perguntaCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			perguntaCacheModel.descricao = null;
		}

		perguntaCacheModel.justificativaResposta = getJustificativaResposta();

		String justificativaResposta = perguntaCacheModel.justificativaResposta;

		if ((justificativaResposta != null) &&
				(justificativaResposta.length() == 0)) {
			perguntaCacheModel.justificativaResposta = null;
		}

		perguntaCacheModel.pontuacao = getPontuacao();

		Date dataInclusao = getDataInclusao();

		if (dataInclusao != null) {
			perguntaCacheModel.dataInclusao = dataInclusao.getTime();
		}
		else {
			perguntaCacheModel.dataInclusao = Long.MIN_VALUE;
		}

		Date dataAlteracao = getDataAlteracao();

		if (dataAlteracao != null) {
			perguntaCacheModel.dataAlteracao = dataAlteracao.getTime();
		}
		else {
			perguntaCacheModel.dataAlteracao = Long.MIN_VALUE;
		}

		perguntaCacheModel.testeId = getTesteId();

		perguntaCacheModel.userIdInclusao = getUserIdInclusao();

		perguntaCacheModel.userIdAlteracao = getUserIdAlteracao();

		return perguntaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", descricao=");
		sb.append(getDescricao());
		sb.append(", justificativaResposta=");
		sb.append(getJustificativaResposta());
		sb.append(", pontuacao=");
		sb.append(getPontuacao());
		sb.append(", dataInclusao=");
		sb.append(getDataInclusao());
		sb.append(", dataAlteracao=");
		sb.append(getDataAlteracao());
		sb.append(", testeId=");
		sb.append(getTesteId());
		sb.append(", userIdInclusao=");
		sb.append(getUserIdInclusao());
		sb.append(", userIdAlteracao=");
		sb.append(getUserIdAlteracao());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.testeconhecimento.model.Pergunta");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descricao</column-name><column-value><![CDATA[");
		sb.append(getDescricao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>justificativaResposta</column-name><column-value><![CDATA[");
		sb.append(getJustificativaResposta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pontuacao</column-name><column-value><![CDATA[");
		sb.append(getPontuacao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataInclusao</column-name><column-value><![CDATA[");
		sb.append(getDataInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataAlteracao</column-name><column-value><![CDATA[");
		sb.append(getDataAlteracao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testeId</column-name><column-value><![CDATA[");
		sb.append(getTesteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userIdInclusao</column-name><column-value><![CDATA[");
		sb.append(getUserIdInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userIdAlteracao</column-name><column-value><![CDATA[");
		sb.append(getUserIdAlteracao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Pergunta.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Pergunta.class
		};
	private long _id;
	private String _descricao;
	private String _descricaoCurrentLanguageId;
	private String _justificativaResposta;
	private String _justificativaRespostaCurrentLanguageId;
	private double _pontuacao;
	private Date _dataInclusao;
	private Date _dataAlteracao;
	private long _testeId;
	private long _originalTesteId;
	private boolean _setOriginalTesteId;
	private long _userIdInclusao;
	private long _userIdAlteracao;
	private long _columnBitmask;
	private Pergunta _escapedModelProxy;
}