/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.testeconhecimento.model.impl;

import br.com.prodevelopment.testeconhecimento.model.Teste_Usuario;
import br.com.prodevelopment.testeconhecimento.model.Teste_UsuarioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Teste_Usuario service. Represents a row in the &quot;TC_Teste_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.testeconhecimento.model.Teste_UsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Teste_UsuarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Teste_UsuarioImpl
 * @see br.com.prodevelopment.testeconhecimento.model.Teste_Usuario
 * @see br.com.prodevelopment.testeconhecimento.model.Teste_UsuarioModel
 * @generated
 */
public class Teste_UsuarioModelImpl extends BaseModelImpl<Teste_Usuario>
	implements Teste_UsuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a teste_ usuario model instance should use the {@link br.com.prodevelopment.testeconhecimento.model.Teste_Usuario} interface instead.
	 */
	public static final String TABLE_NAME = "TC_Teste_Usuario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "nome", Types.VARCHAR },
			{ "email", Types.VARCHAR },
			{ "dataInclusao", Types.TIMESTAMP },
			{ "dataFinalizacao", Types.TIMESTAMP },
			{ "totalRespostaCorreta", Types.INTEGER },
			{ "totalRespostaErrada", Types.INTEGER },
			{ "totalPontuacao", Types.DOUBLE },
			{ "testeId", Types.BIGINT },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table TC_Teste_Usuario (id_ LONG not null primary key,nome VARCHAR(75) null,email VARCHAR(75) null,dataInclusao DATE null,dataFinalizacao DATE null,totalRespostaCorreta INTEGER,totalRespostaErrada INTEGER,totalPontuacao DOUBLE,testeId LONG,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table TC_Teste_Usuario";
	public static final String ORDER_BY_JPQL = " ORDER BY teste_Usuario.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TC_Teste_Usuario.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Teste_Usuario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Teste_Usuario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.testeconhecimento.model.Teste_Usuario"),
			true);
	public static long TESTEID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.testeconhecimento.model.Teste_Usuario"));

	public Teste_UsuarioModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Teste_Usuario.class;
	}

	public String getModelClassName() {
		return Teste_Usuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("nome", getNome());
		attributes.put("email", getEmail());
		attributes.put("dataInclusao", getDataInclusao());
		attributes.put("dataFinalizacao", getDataFinalizacao());
		attributes.put("totalRespostaCorreta", getTotalRespostaCorreta());
		attributes.put("totalRespostaErrada", getTotalRespostaErrada());
		attributes.put("totalPontuacao", getTotalPontuacao());
		attributes.put("testeId", getTesteId());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		Date dataInclusao = (Date)attributes.get("dataInclusao");

		if (dataInclusao != null) {
			setDataInclusao(dataInclusao);
		}

		Date dataFinalizacao = (Date)attributes.get("dataFinalizacao");

		if (dataFinalizacao != null) {
			setDataFinalizacao(dataFinalizacao);
		}

		Integer totalRespostaCorreta = (Integer)attributes.get(
				"totalRespostaCorreta");

		if (totalRespostaCorreta != null) {
			setTotalRespostaCorreta(totalRespostaCorreta);
		}

		Integer totalRespostaErrada = (Integer)attributes.get(
				"totalRespostaErrada");

		if (totalRespostaErrada != null) {
			setTotalRespostaErrada(totalRespostaErrada);
		}

		Double totalPontuacao = (Double)attributes.get("totalPontuacao");

		if (totalPontuacao != null) {
			setTotalPontuacao(totalPontuacao);
		}

		Long testeId = (Long)attributes.get("testeId");

		if (testeId != null) {
			setTesteId(testeId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	public void setNome(String nome) {
		_nome = nome;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public Date getDataInclusao() {
		return _dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		_dataInclusao = dataInclusao;
	}

	public Date getDataFinalizacao() {
		return _dataFinalizacao;
	}

	public void setDataFinalizacao(Date dataFinalizacao) {
		_dataFinalizacao = dataFinalizacao;
	}

	public int getTotalRespostaCorreta() {
		return _totalRespostaCorreta;
	}

	public void setTotalRespostaCorreta(int totalRespostaCorreta) {
		_totalRespostaCorreta = totalRespostaCorreta;
	}

	public int getTotalRespostaErrada() {
		return _totalRespostaErrada;
	}

	public void setTotalRespostaErrada(int totalRespostaErrada) {
		_totalRespostaErrada = totalRespostaErrada;
	}

	public double getTotalPontuacao() {
		return _totalPontuacao;
	}

	public void setTotalPontuacao(double totalPontuacao) {
		_totalPontuacao = totalPontuacao;
	}

	public long getTesteId() {
		return _testeId;
	}

	public void setTesteId(long testeId) {
		_columnBitmask |= TESTEID_COLUMN_BITMASK;

		if (!_setOriginalTesteId) {
			_setOriginalTesteId = true;

			_originalTesteId = _testeId;
		}

		_testeId = testeId;
	}

	public long getOriginalTesteId() {
		return _originalTesteId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Teste_Usuario.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Teste_Usuario toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Teste_Usuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		Teste_UsuarioImpl teste_UsuarioImpl = new Teste_UsuarioImpl();

		teste_UsuarioImpl.setId(getId());
		teste_UsuarioImpl.setNome(getNome());
		teste_UsuarioImpl.setEmail(getEmail());
		teste_UsuarioImpl.setDataInclusao(getDataInclusao());
		teste_UsuarioImpl.setDataFinalizacao(getDataFinalizacao());
		teste_UsuarioImpl.setTotalRespostaCorreta(getTotalRespostaCorreta());
		teste_UsuarioImpl.setTotalRespostaErrada(getTotalRespostaErrada());
		teste_UsuarioImpl.setTotalPontuacao(getTotalPontuacao());
		teste_UsuarioImpl.setTesteId(getTesteId());
		teste_UsuarioImpl.setUserId(getUserId());

		teste_UsuarioImpl.resetOriginalValues();

		return teste_UsuarioImpl;
	}

	public int compareTo(Teste_Usuario teste_Usuario) {
		int value = 0;

		if (getId() < teste_Usuario.getId()) {
			value = -1;
		}
		else if (getId() > teste_Usuario.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Teste_Usuario teste_Usuario = null;

		try {
			teste_Usuario = (Teste_Usuario)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = teste_Usuario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Teste_UsuarioModelImpl teste_UsuarioModelImpl = this;

		teste_UsuarioModelImpl._originalTesteId = teste_UsuarioModelImpl._testeId;

		teste_UsuarioModelImpl._setOriginalTesteId = false;

		teste_UsuarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Teste_Usuario> toCacheModel() {
		Teste_UsuarioCacheModel teste_UsuarioCacheModel = new Teste_UsuarioCacheModel();

		teste_UsuarioCacheModel.id = getId();

		teste_UsuarioCacheModel.nome = getNome();

		String nome = teste_UsuarioCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			teste_UsuarioCacheModel.nome = null;
		}

		teste_UsuarioCacheModel.email = getEmail();

		String email = teste_UsuarioCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			teste_UsuarioCacheModel.email = null;
		}

		Date dataInclusao = getDataInclusao();

		if (dataInclusao != null) {
			teste_UsuarioCacheModel.dataInclusao = dataInclusao.getTime();
		}
		else {
			teste_UsuarioCacheModel.dataInclusao = Long.MIN_VALUE;
		}

		Date dataFinalizacao = getDataFinalizacao();

		if (dataFinalizacao != null) {
			teste_UsuarioCacheModel.dataFinalizacao = dataFinalizacao.getTime();
		}
		else {
			teste_UsuarioCacheModel.dataFinalizacao = Long.MIN_VALUE;
		}

		teste_UsuarioCacheModel.totalRespostaCorreta = getTotalRespostaCorreta();

		teste_UsuarioCacheModel.totalRespostaErrada = getTotalRespostaErrada();

		teste_UsuarioCacheModel.totalPontuacao = getTotalPontuacao();

		teste_UsuarioCacheModel.testeId = getTesteId();

		teste_UsuarioCacheModel.userId = getUserId();

		return teste_UsuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", dataInclusao=");
		sb.append(getDataInclusao());
		sb.append(", dataFinalizacao=");
		sb.append(getDataFinalizacao());
		sb.append(", totalRespostaCorreta=");
		sb.append(getTotalRespostaCorreta());
		sb.append(", totalRespostaErrada=");
		sb.append(getTotalRespostaErrada());
		sb.append(", totalPontuacao=");
		sb.append(getTotalPontuacao());
		sb.append(", testeId=");
		sb.append(getTesteId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.testeconhecimento.model.Teste_Usuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataInclusao</column-name><column-value><![CDATA[");
		sb.append(getDataInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataFinalizacao</column-name><column-value><![CDATA[");
		sb.append(getDataFinalizacao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalRespostaCorreta</column-name><column-value><![CDATA[");
		sb.append(getTotalRespostaCorreta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalRespostaErrada</column-name><column-value><![CDATA[");
		sb.append(getTotalRespostaErrada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalPontuacao</column-name><column-value><![CDATA[");
		sb.append(getTotalPontuacao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testeId</column-name><column-value><![CDATA[");
		sb.append(getTesteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Teste_Usuario.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Teste_Usuario.class
		};
	private long _id;
	private String _nome;
	private String _email;
	private Date _dataInclusao;
	private Date _dataFinalizacao;
	private int _totalRespostaCorreta;
	private int _totalRespostaErrada;
	private double _totalPontuacao;
	private long _testeId;
	private long _originalTesteId;
	private boolean _setOriginalTesteId;
	private long _userId;
	private String _userUuid;
	private long _columnBitmask;
	private Teste_Usuario _escapedModelProxy;
}