/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.eticket.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.trash.TrashHandler;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.model.TrashedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.trash.model.TrashEntry;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the TypeTicket service. Represents a row in the &quot;Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.eticket.model.impl.TypeTicketModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.eticket.model.impl.TypeTicketImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see TypeTicket
 * @see br.com.prodevelopment.eticket.model.impl.TypeTicketImpl
 * @see br.com.prodevelopment.eticket.model.impl.TypeTicketModelImpl
 * @generated
 */
public interface TypeTicketModel extends BaseModel<TypeTicket>, StagedModel,
	TrashedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type ticket model instance should use the {@link TypeTicket} interface instead.
	 */

	/**
	 * Returns the primary key of this type ticket.
	 *
	 * @return the primary key of this type ticket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this type ticket.
	 *
	 * @param primaryKey the primary key of this type ticket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this type ticket.
	 *
	 * @return the uuid of this type ticket
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this type ticket.
	 *
	 * @param uuid the uuid of this type ticket
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the type ticket ID of this type ticket.
	 *
	 * @return the type ticket ID of this type ticket
	 */
	public long getTypeTicketId();

	/**
	 * Sets the type ticket ID of this type ticket.
	 *
	 * @param typeTicketId the type ticket ID of this type ticket
	 */
	public void setTypeTicketId(long typeTicketId);

	/**
	 * Returns the group ID of this type ticket.
	 *
	 * @return the group ID of this type ticket
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this type ticket.
	 *
	 * @param groupId the group ID of this type ticket
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this type ticket.
	 *
	 * @return the company ID of this type ticket
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this type ticket.
	 *
	 * @param companyId the company ID of this type ticket
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID create of this type ticket.
	 *
	 * @return the user ID create of this type ticket
	 */
	public long getUserIdCreate();

	/**
	 * Sets the user ID create of this type ticket.
	 *
	 * @param userIdCreate the user ID create of this type ticket
	 */
	public void setUserIdCreate(long userIdCreate);

	/**
	 * Returns the user ID modified of this type ticket.
	 *
	 * @return the user ID modified of this type ticket
	 */
	public long getUserIdModified();

	/**
	 * Sets the user ID modified of this type ticket.
	 *
	 * @param userIdModified the user ID modified of this type ticket
	 */
	public void setUserIdModified(long userIdModified);

	/**
	 * Returns the create date of this type ticket.
	 *
	 * @return the create date of this type ticket
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this type ticket.
	 *
	 * @param createDate the create date of this type ticket
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this type ticket.
	 *
	 * @return the modified date of this type ticket
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this type ticket.
	 *
	 * @param modifiedDate the modified date of this type ticket
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this type ticket.
	 *
	 * @return the name of this type ticket
	 */
	public String getName();

	/**
	 * Returns the localized name of this type ticket in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this type ticket
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this type ticket in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this type ticket. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this type ticket in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this type ticket
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this type ticket in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this type ticket
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this type ticket.
	 *
	 * @return the locales and localized names of this type ticket
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this type ticket.
	 *
	 * @param name the name of this type ticket
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this type ticket in the language.
	 *
	 * @param name the localized name of this type ticket
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this type ticket in the language, and sets the default locale.
	 *
	 * @param name the localized name of this type ticket
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this type ticket from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this type ticket
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this type ticket from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this type ticket
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the description of this type ticket.
	 *
	 * @return the description of this type ticket
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this type ticket in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this type ticket
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this type ticket in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this type ticket. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this type ticket in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this type ticket
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this type ticket in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this type ticket
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this type ticket.
	 *
	 * @return the locales and localized descriptions of this type ticket
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this type ticket.
	 *
	 * @param description the description of this type ticket
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this type ticket in the language.
	 *
	 * @param description the localized description of this type ticket
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this type ticket in the language, and sets the default locale.
	 *
	 * @param description the localized description of this type ticket
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this type ticket from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this type ticket
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this type ticket from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this type ticket
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the xsd of this type ticket.
	 *
	 * @return the xsd of this type ticket
	 */
	@AutoEscape
	public String getXsd();

	/**
	 * Sets the xsd of this type ticket.
	 *
	 * @param xsd the xsd of this type ticket
	 */
	public void setXsd(String xsd);

	/**
	 * Returns the status of this type ticket.
	 *
	 * @return the status of this type ticket
	 */
	@Override
	public int getStatus();

	/**
	 * Returns the trash entry created when this type ticket was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this type ticket.
	 *
	 * @return the trash entry created when this type ticket was moved to the Recycle Bin
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TrashEntry getTrashEntry() throws PortalException, SystemException;

	/**
	 * Returns the class primary key of the trash entry for this type ticket.
	 *
	 * @return the class primary key of the trash entry for this type ticket
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this type ticket.
	 *
	 * @return the trash handler for this type ticket
	 */
	@Override
	public TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this type ticket is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this type ticket is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this type ticket is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this type ticket is in the Recycle Bin; <code>false</code> otherwise
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.eticket.model.TypeTicket typeTicket);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.eticket.model.TypeTicket> toCacheModel();

	@Override
	public br.com.prodevelopment.eticket.model.TypeTicket toEscapedModel();

	@Override
	public br.com.prodevelopment.eticket.model.TypeTicket toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}