/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.eticket.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TypeTicketUsers service. Represents a row in the &quot;TypeUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.eticket.model.impl.TypeTicketUsersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.eticket.model.impl.TypeTicketUsersImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see TypeTicketUsers
 * @see br.com.prodevelopment.eticket.model.impl.TypeTicketUsersImpl
 * @see br.com.prodevelopment.eticket.model.impl.TypeTicketUsersModelImpl
 * @generated
 */
public interface TypeTicketUsersModel extends BaseModel<TypeTicketUsers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type ticket users model instance should use the {@link TypeTicketUsers} interface instead.
	 */

	/**
	 * Returns the primary key of this type ticket users.
	 *
	 * @return the primary key of this type ticket users
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this type ticket users.
	 *
	 * @param primaryKey the primary key of this type ticket users
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ticket users ID of this type ticket users.
	 *
	 * @return the type ticket users ID of this type ticket users
	 */
	public long getTypeTicketUsersId();

	/**
	 * Sets the type ticket users ID of this type ticket users.
	 *
	 * @param typeTicketUsersId the type ticket users ID of this type ticket users
	 */
	public void setTypeTicketUsersId(long typeTicketUsersId);

	/**
	 * Returns the user ID create of this type ticket users.
	 *
	 * @return the user ID create of this type ticket users
	 */
	public long getUserIdCreate();

	/**
	 * Sets the user ID create of this type ticket users.
	 *
	 * @param userIdCreate the user ID create of this type ticket users
	 */
	public void setUserIdCreate(long userIdCreate);

	/**
	 * Returns the user ID modified of this type ticket users.
	 *
	 * @return the user ID modified of this type ticket users
	 */
	public long getUserIdModified();

	/**
	 * Sets the user ID modified of this type ticket users.
	 *
	 * @param userIdModified the user ID modified of this type ticket users
	 */
	public void setUserIdModified(long userIdModified);

	/**
	 * Returns the create date of this type ticket users.
	 *
	 * @return the create date of this type ticket users
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this type ticket users.
	 *
	 * @param createDate the create date of this type ticket users
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this type ticket users.
	 *
	 * @return the modified date of this type ticket users
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this type ticket users.
	 *
	 * @param modifiedDate the modified date of this type ticket users
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type ticket ID of this type ticket users.
	 *
	 * @return the type ticket ID of this type ticket users
	 */
	public long getTypeTicketId();

	/**
	 * Sets the type ticket ID of this type ticket users.
	 *
	 * @param typeTicketId the type ticket ID of this type ticket users
	 */
	public void setTypeTicketId(long typeTicketId);

	/**
	 * Returns the user ID of this type ticket users.
	 *
	 * @return the user ID of this type ticket users
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this type ticket users.
	 *
	 * @param userId the user ID of this type ticket users
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this type ticket users.
	 *
	 * @return the user uuid of this type ticket users
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this type ticket users.
	 *
	 * @param userUuid the user uuid of this type ticket users
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.eticket.model.TypeTicketUsers typeTicketUsers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.eticket.model.TypeTicketUsers> toCacheModel();

	@Override
	public br.com.prodevelopment.eticket.model.TypeTicketUsers toEscapedModel();

	@Override
	public br.com.prodevelopment.eticket.model.TypeTicketUsers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}