/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.model.impl;

import br.com.prodevelopment.cliente.model.ClienteUsuario;
import br.com.prodevelopment.cliente.service.ClienteUsuarioLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ClienteUsuario service. Represents a row in the &quot;ClienteUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClienteUsuarioImpl}.
 * </p>
 *
 * @author marcelo
 * @see ClienteUsuarioImpl
 * @see br.com.prodevelopment.cliente.model.ClienteUsuario
 * @generated
 */
public abstract class ClienteUsuarioBaseImpl extends ClienteUsuarioModelImpl
	implements ClienteUsuario {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cliente usuario model instance should use the {@link ClienteUsuario} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ClienteUsuarioLocalServiceUtil.addClienteUsuario(this);
		}
		else {
			ClienteUsuarioLocalServiceUtil.updateClienteUsuario(this);
		}
	}
}