/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.model.impl;

import br.com.prodevelopment.cliente.model.Cliente;
import br.com.prodevelopment.cliente.model.ClienteModel;
import br.com.prodevelopment.cliente.model.ClienteSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Cliente service. Represents a row in the &quot;Cliente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.cliente.model.ClienteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClienteImpl}.
 * </p>
 *
 * @author marcelo
 * @see ClienteImpl
 * @see br.com.prodevelopment.cliente.model.Cliente
 * @see br.com.prodevelopment.cliente.model.ClienteModel
 * @generated
 */
@JSON(strict = true)
public class ClienteModelImpl extends BaseModelImpl<Cliente>
	implements ClienteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cliente model instance should use the {@link br.com.prodevelopment.cliente.model.Cliente} interface instead.
	 */
	public static final String TABLE_NAME = "Cliente";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "clienteId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createUserId", Types.BIGINT },
			{ "modifiedUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "nome", Types.VARCHAR },
			{ "rgInscricaoMun", Types.VARCHAR },
			{ "rgOrgaoEmissor", Types.VARCHAR },
			{ "rgDataEmissao", Types.TIMESTAMP },
			{ "tipoPessoa", Types.VARCHAR },
			{ "cpfCnpj", Types.VARCHAR },
			{ "sexo", Types.VARCHAR },
			{ "estadoCivil", Types.VARCHAR },
			{ "dataNascimento", Types.TIMESTAMP },
			{ "endComLogradouro", Types.VARCHAR },
			{ "endComNumero", Types.VARCHAR },
			{ "endComComplemento", Types.VARCHAR },
			{ "endComCep", Types.VARCHAR },
			{ "endComBairro", Types.VARCHAR },
			{ "endComCidade", Types.BIGINT },
			{ "endComUf", Types.VARCHAR },
			{ "endComPais", Types.VARCHAR },
			{ "endResLogradouro", Types.VARCHAR },
			{ "endResNumero", Types.VARCHAR },
			{ "endResComplemento", Types.VARCHAR },
			{ "endResCep", Types.VARCHAR },
			{ "endResBairro", Types.VARCHAR },
			{ "endResCidade", Types.BIGINT },
			{ "endResUf", Types.VARCHAR },
			{ "endResPais", Types.VARCHAR },
			{ "telComDdd", Types.VARCHAR },
			{ "versao", Types.DOUBLE },
			{ "logoTipoId", Types.BIGINT },
			{ "observacao", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Cliente (uuid_ VARCHAR(75) null,clienteId LONG not null primary key,companyId LONG,groupId LONG,createUserId LONG,modifiedUserId LONG,createDate DATE null,modifiedDate DATE null,nome VARCHAR(100) null,rgInscricaoMun VARCHAR(20) null,rgOrgaoEmissor VARCHAR(20) null,rgDataEmissao DATE null,tipoPessoa VARCHAR(2) null,cpfCnpj VARCHAR(20) null,sexo VARCHAR(1) null,estadoCivil VARCHAR(20) null,dataNascimento DATE null,endComLogradouro VARCHAR(100) null,endComNumero VARCHAR(10) null,endComComplemento VARCHAR(50) null,endComCep VARCHAR(10) null,endComBairro VARCHAR(80) null,endComCidade LONG,endComUf VARCHAR(2) null,endComPais VARCHAR(80) null,endResLogradouro VARCHAR(100) null,endResNumero VARCHAR(10) null,endResComplemento VARCHAR(50) null,endResCep VARCHAR(10) null,endResBairro VARCHAR(80) null,endResCidade LONG,endResUf VARCHAR(2) null,endResPais VARCHAR(80) null,telComDdd VARCHAR(10) null,versao DOUBLE,logoTipoId LONG,observacao VARCHAR(2000) null)";
	public static final String TABLE_SQL_DROP = "drop table Cliente";
	public static final String ORDER_BY_JPQL = " ORDER BY cliente.nome ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Cliente.nome ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.cliente.model.Cliente"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.cliente.model.Cliente"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.cliente.model.Cliente"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long CPFCNPJ_COLUMN_BITMASK = 2L;
	public static long DATANASCIMENTO_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long NOME_COLUMN_BITMASK = 16L;
	public static long RGINSCRICAOMUN_COLUMN_BITMASK = 32L;
	public static long UUID_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Cliente toModel(ClienteSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Cliente model = new ClienteImpl();

		model.setUuid(soapModel.getUuid());
		model.setClienteId(soapModel.getClienteId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateUserId(soapModel.getCreateUserId());
		model.setModifiedUserId(soapModel.getModifiedUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setNome(soapModel.getNome());
		model.setRgInscricaoMun(soapModel.getRgInscricaoMun());
		model.setRgOrgaoEmissor(soapModel.getRgOrgaoEmissor());
		model.setRgDataEmissao(soapModel.getRgDataEmissao());
		model.setTipoPessoa(soapModel.getTipoPessoa());
		model.setCpfCnpj(soapModel.getCpfCnpj());
		model.setSexo(soapModel.getSexo());
		model.setEstadoCivil(soapModel.getEstadoCivil());
		model.setDataNascimento(soapModel.getDataNascimento());
		model.setEndComLogradouro(soapModel.getEndComLogradouro());
		model.setEndComNumero(soapModel.getEndComNumero());
		model.setEndComComplemento(soapModel.getEndComComplemento());
		model.setEndComCep(soapModel.getEndComCep());
		model.setEndComBairro(soapModel.getEndComBairro());
		model.setEndComCidade(soapModel.getEndComCidade());
		model.setEndComUf(soapModel.getEndComUf());
		model.setEndComPais(soapModel.getEndComPais());
		model.setEndResLogradouro(soapModel.getEndResLogradouro());
		model.setEndResNumero(soapModel.getEndResNumero());
		model.setEndResComplemento(soapModel.getEndResComplemento());
		model.setEndResCep(soapModel.getEndResCep());
		model.setEndResBairro(soapModel.getEndResBairro());
		model.setEndResCidade(soapModel.getEndResCidade());
		model.setEndResUf(soapModel.getEndResUf());
		model.setEndResPais(soapModel.getEndResPais());
		model.setTelComDdd(soapModel.getTelComDdd());
		model.setVersao(soapModel.getVersao());
		model.setLogoTipoId(soapModel.getLogoTipoId());
		model.setObservacao(soapModel.getObservacao());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Cliente> toModels(ClienteSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Cliente> models = new ArrayList<Cliente>(soapModels.length);

		for (ClienteSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.cliente.model.Cliente"));

	public ClienteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _clienteId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClienteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _clienteId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Cliente.class;
	}

	@Override
	public String getModelClassName() {
		return Cliente.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("clienteId", getClienteId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createUserId", getCreateUserId());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("nome", getNome());
		attributes.put("rgInscricaoMun", getRgInscricaoMun());
		attributes.put("rgOrgaoEmissor", getRgOrgaoEmissor());
		attributes.put("rgDataEmissao", getRgDataEmissao());
		attributes.put("tipoPessoa", getTipoPessoa());
		attributes.put("cpfCnpj", getCpfCnpj());
		attributes.put("sexo", getSexo());
		attributes.put("estadoCivil", getEstadoCivil());
		attributes.put("dataNascimento", getDataNascimento());
		attributes.put("endComLogradouro", getEndComLogradouro());
		attributes.put("endComNumero", getEndComNumero());
		attributes.put("endComComplemento", getEndComComplemento());
		attributes.put("endComCep", getEndComCep());
		attributes.put("endComBairro", getEndComBairro());
		attributes.put("endComCidade", getEndComCidade());
		attributes.put("endComUf", getEndComUf());
		attributes.put("endComPais", getEndComPais());
		attributes.put("endResLogradouro", getEndResLogradouro());
		attributes.put("endResNumero", getEndResNumero());
		attributes.put("endResComplemento", getEndResComplemento());
		attributes.put("endResCep", getEndResCep());
		attributes.put("endResBairro", getEndResBairro());
		attributes.put("endResCidade", getEndResCidade());
		attributes.put("endResUf", getEndResUf());
		attributes.put("endResPais", getEndResPais());
		attributes.put("telComDdd", getTelComDdd());
		attributes.put("versao", getVersao());
		attributes.put("logoTipoId", getLogoTipoId());
		attributes.put("observacao", getObservacao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long clienteId = (Long)attributes.get("clienteId");

		if (clienteId != null) {
			setClienteId(clienteId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long createUserId = (Long)attributes.get("createUserId");

		if (createUserId != null) {
			setCreateUserId(createUserId);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String rgInscricaoMun = (String)attributes.get("rgInscricaoMun");

		if (rgInscricaoMun != null) {
			setRgInscricaoMun(rgInscricaoMun);
		}

		String rgOrgaoEmissor = (String)attributes.get("rgOrgaoEmissor");

		if (rgOrgaoEmissor != null) {
			setRgOrgaoEmissor(rgOrgaoEmissor);
		}

		Date rgDataEmissao = (Date)attributes.get("rgDataEmissao");

		if (rgDataEmissao != null) {
			setRgDataEmissao(rgDataEmissao);
		}

		String tipoPessoa = (String)attributes.get("tipoPessoa");

		if (tipoPessoa != null) {
			setTipoPessoa(tipoPessoa);
		}

		String cpfCnpj = (String)attributes.get("cpfCnpj");

		if (cpfCnpj != null) {
			setCpfCnpj(cpfCnpj);
		}

		String sexo = (String)attributes.get("sexo");

		if (sexo != null) {
			setSexo(sexo);
		}

		String estadoCivil = (String)attributes.get("estadoCivil");

		if (estadoCivil != null) {
			setEstadoCivil(estadoCivil);
		}

		Date dataNascimento = (Date)attributes.get("dataNascimento");

		if (dataNascimento != null) {
			setDataNascimento(dataNascimento);
		}

		String endComLogradouro = (String)attributes.get("endComLogradouro");

		if (endComLogradouro != null) {
			setEndComLogradouro(endComLogradouro);
		}

		String endComNumero = (String)attributes.get("endComNumero");

		if (endComNumero != null) {
			setEndComNumero(endComNumero);
		}

		String endComComplemento = (String)attributes.get("endComComplemento");

		if (endComComplemento != null) {
			setEndComComplemento(endComComplemento);
		}

		String endComCep = (String)attributes.get("endComCep");

		if (endComCep != null) {
			setEndComCep(endComCep);
		}

		String endComBairro = (String)attributes.get("endComBairro");

		if (endComBairro != null) {
			setEndComBairro(endComBairro);
		}

		Long endComCidade = (Long)attributes.get("endComCidade");

		if (endComCidade != null) {
			setEndComCidade(endComCidade);
		}

		String endComUf = (String)attributes.get("endComUf");

		if (endComUf != null) {
			setEndComUf(endComUf);
		}

		String endComPais = (String)attributes.get("endComPais");

		if (endComPais != null) {
			setEndComPais(endComPais);
		}

		String endResLogradouro = (String)attributes.get("endResLogradouro");

		if (endResLogradouro != null) {
			setEndResLogradouro(endResLogradouro);
		}

		String endResNumero = (String)attributes.get("endResNumero");

		if (endResNumero != null) {
			setEndResNumero(endResNumero);
		}

		String endResComplemento = (String)attributes.get("endResComplemento");

		if (endResComplemento != null) {
			setEndResComplemento(endResComplemento);
		}

		String endResCep = (String)attributes.get("endResCep");

		if (endResCep != null) {
			setEndResCep(endResCep);
		}

		String endResBairro = (String)attributes.get("endResBairro");

		if (endResBairro != null) {
			setEndResBairro(endResBairro);
		}

		Long endResCidade = (Long)attributes.get("endResCidade");

		if (endResCidade != null) {
			setEndResCidade(endResCidade);
		}

		String endResUf = (String)attributes.get("endResUf");

		if (endResUf != null) {
			setEndResUf(endResUf);
		}

		String endResPais = (String)attributes.get("endResPais");

		if (endResPais != null) {
			setEndResPais(endResPais);
		}

		String telComDdd = (String)attributes.get("telComDdd");

		if (telComDdd != null) {
			setTelComDdd(telComDdd);
		}

		Double versao = (Double)attributes.get("versao");

		if (versao != null) {
			setVersao(versao);
		}

		Long logoTipoId = (Long)attributes.get("logoTipoId");

		if (logoTipoId != null) {
			setLogoTipoId(logoTipoId);
		}

		String observacao = (String)attributes.get("observacao");

		if (observacao != null) {
			setObservacao(observacao);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getClienteId() {
		return _clienteId;
	}

	@Override
	public void setClienteId(long clienteId) {
		_clienteId = clienteId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCreateUserId() {
		return _createUserId;
	}

	@Override
	public void setCreateUserId(long createUserId) {
		_createUserId = createUserId;
	}

	@Override
	public String getCreateUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreateUserId(), "uuid",
			_createUserUuid);
	}

	@Override
	public void setCreateUserUuid(String createUserUuid) {
		_createUserUuid = createUserUuid;
	}

	@JSON
	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_columnBitmask = -1L;

		if (_originalNome == null) {
			_originalNome = _nome;
		}

		_nome = nome;
	}

	public String getOriginalNome() {
		return GetterUtil.getString(_originalNome);
	}

	@JSON
	@Override
	public String getRgInscricaoMun() {
		if (_rgInscricaoMun == null) {
			return StringPool.BLANK;
		}
		else {
			return _rgInscricaoMun;
		}
	}

	@Override
	public void setRgInscricaoMun(String rgInscricaoMun) {
		_columnBitmask |= RGINSCRICAOMUN_COLUMN_BITMASK;

		if (_originalRgInscricaoMun == null) {
			_originalRgInscricaoMun = _rgInscricaoMun;
		}

		_rgInscricaoMun = rgInscricaoMun;
	}

	public String getOriginalRgInscricaoMun() {
		return GetterUtil.getString(_originalRgInscricaoMun);
	}

	@JSON
	@Override
	public String getRgOrgaoEmissor() {
		if (_rgOrgaoEmissor == null) {
			return StringPool.BLANK;
		}
		else {
			return _rgOrgaoEmissor;
		}
	}

	@Override
	public void setRgOrgaoEmissor(String rgOrgaoEmissor) {
		_rgOrgaoEmissor = rgOrgaoEmissor;
	}

	@JSON
	@Override
	public Date getRgDataEmissao() {
		return _rgDataEmissao;
	}

	@Override
	public void setRgDataEmissao(Date rgDataEmissao) {
		_rgDataEmissao = rgDataEmissao;
	}

	@JSON
	@Override
	public String getTipoPessoa() {
		if (_tipoPessoa == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoPessoa;
		}
	}

	@Override
	public void setTipoPessoa(String tipoPessoa) {
		_tipoPessoa = tipoPessoa;
	}

	@JSON
	@Override
	public String getCpfCnpj() {
		if (_cpfCnpj == null) {
			return StringPool.BLANK;
		}
		else {
			return _cpfCnpj;
		}
	}

	@Override
	public void setCpfCnpj(String cpfCnpj) {
		_columnBitmask |= CPFCNPJ_COLUMN_BITMASK;

		if (_originalCpfCnpj == null) {
			_originalCpfCnpj = _cpfCnpj;
		}

		_cpfCnpj = cpfCnpj;
	}

	public String getOriginalCpfCnpj() {
		return GetterUtil.getString(_originalCpfCnpj);
	}

	@JSON
	@Override
	public String getSexo() {
		if (_sexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _sexo;
		}
	}

	@Override
	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	@JSON
	@Override
	public String getEstadoCivil() {
		if (_estadoCivil == null) {
			return StringPool.BLANK;
		}
		else {
			return _estadoCivil;
		}
	}

	@Override
	public void setEstadoCivil(String estadoCivil) {
		_estadoCivil = estadoCivil;
	}

	@JSON
	@Override
	public Date getDataNascimento() {
		return _dataNascimento;
	}

	@Override
	public void setDataNascimento(Date dataNascimento) {
		_columnBitmask |= DATANASCIMENTO_COLUMN_BITMASK;

		if (_originalDataNascimento == null) {
			_originalDataNascimento = _dataNascimento;
		}

		_dataNascimento = dataNascimento;
	}

	public Date getOriginalDataNascimento() {
		return _originalDataNascimento;
	}

	@JSON
	@Override
	public String getEndComLogradouro() {
		if (_endComLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComLogradouro;
		}
	}

	@Override
	public void setEndComLogradouro(String endComLogradouro) {
		_endComLogradouro = endComLogradouro;
	}

	@JSON
	@Override
	public String getEndComNumero() {
		if (_endComNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComNumero;
		}
	}

	@Override
	public void setEndComNumero(String endComNumero) {
		_endComNumero = endComNumero;
	}

	@JSON
	@Override
	public String getEndComComplemento() {
		if (_endComComplemento == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComComplemento;
		}
	}

	@Override
	public void setEndComComplemento(String endComComplemento) {
		_endComComplemento = endComComplemento;
	}

	@JSON
	@Override
	public String getEndComCep() {
		if (_endComCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComCep;
		}
	}

	@Override
	public void setEndComCep(String endComCep) {
		_endComCep = endComCep;
	}

	@JSON
	@Override
	public String getEndComBairro() {
		if (_endComBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComBairro;
		}
	}

	@Override
	public void setEndComBairro(String endComBairro) {
		_endComBairro = endComBairro;
	}

	@JSON
	@Override
	public long getEndComCidade() {
		return _endComCidade;
	}

	@Override
	public void setEndComCidade(long endComCidade) {
		_endComCidade = endComCidade;
	}

	@JSON
	@Override
	public String getEndComUf() {
		if (_endComUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComUf;
		}
	}

	@Override
	public void setEndComUf(String endComUf) {
		_endComUf = endComUf;
	}

	@JSON
	@Override
	public String getEndComPais() {
		if (_endComPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComPais;
		}
	}

	@Override
	public void setEndComPais(String endComPais) {
		_endComPais = endComPais;
	}

	@JSON
	@Override
	public String getEndResLogradouro() {
		if (_endResLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResLogradouro;
		}
	}

	@Override
	public void setEndResLogradouro(String endResLogradouro) {
		_endResLogradouro = endResLogradouro;
	}

	@JSON
	@Override
	public String getEndResNumero() {
		if (_endResNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResNumero;
		}
	}

	@Override
	public void setEndResNumero(String endResNumero) {
		_endResNumero = endResNumero;
	}

	@JSON
	@Override
	public String getEndResComplemento() {
		if (_endResComplemento == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResComplemento;
		}
	}

	@Override
	public void setEndResComplemento(String endResComplemento) {
		_endResComplemento = endResComplemento;
	}

	@JSON
	@Override
	public String getEndResCep() {
		if (_endResCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResCep;
		}
	}

	@Override
	public void setEndResCep(String endResCep) {
		_endResCep = endResCep;
	}

	@JSON
	@Override
	public String getEndResBairro() {
		if (_endResBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResBairro;
		}
	}

	@Override
	public void setEndResBairro(String endResBairro) {
		_endResBairro = endResBairro;
	}

	@JSON
	@Override
	public long getEndResCidade() {
		return _endResCidade;
	}

	@Override
	public void setEndResCidade(long endResCidade) {
		_endResCidade = endResCidade;
	}

	@JSON
	@Override
	public String getEndResUf() {
		if (_endResUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResUf;
		}
	}

	@Override
	public void setEndResUf(String endResUf) {
		_endResUf = endResUf;
	}

	@JSON
	@Override
	public String getEndResPais() {
		if (_endResPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResPais;
		}
	}

	@Override
	public void setEndResPais(String endResPais) {
		_endResPais = endResPais;
	}

	@JSON
	@Override
	public String getTelComDdd() {
		if (_telComDdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _telComDdd;
		}
	}

	@Override
	public void setTelComDdd(String telComDdd) {
		_telComDdd = telComDdd;
	}

	@JSON
	@Override
	public double getVersao() {
		return _versao;
	}

	@Override
	public void setVersao(double versao) {
		_versao = versao;
	}

	@JSON
	@Override
	public long getLogoTipoId() {
		return _logoTipoId;
	}

	@Override
	public void setLogoTipoId(long logoTipoId) {
		_logoTipoId = logoTipoId;
	}

	@JSON
	@Override
	public String getObservacao() {
		if (_observacao == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacao;
		}
	}

	@Override
	public void setObservacao(String observacao) {
		_observacao = observacao;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Cliente.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Cliente.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Cliente toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Cliente)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClienteImpl clienteImpl = new ClienteImpl();

		clienteImpl.setUuid(getUuid());
		clienteImpl.setClienteId(getClienteId());
		clienteImpl.setCompanyId(getCompanyId());
		clienteImpl.setGroupId(getGroupId());
		clienteImpl.setCreateUserId(getCreateUserId());
		clienteImpl.setModifiedUserId(getModifiedUserId());
		clienteImpl.setCreateDate(getCreateDate());
		clienteImpl.setModifiedDate(getModifiedDate());
		clienteImpl.setNome(getNome());
		clienteImpl.setRgInscricaoMun(getRgInscricaoMun());
		clienteImpl.setRgOrgaoEmissor(getRgOrgaoEmissor());
		clienteImpl.setRgDataEmissao(getRgDataEmissao());
		clienteImpl.setTipoPessoa(getTipoPessoa());
		clienteImpl.setCpfCnpj(getCpfCnpj());
		clienteImpl.setSexo(getSexo());
		clienteImpl.setEstadoCivil(getEstadoCivil());
		clienteImpl.setDataNascimento(getDataNascimento());
		clienteImpl.setEndComLogradouro(getEndComLogradouro());
		clienteImpl.setEndComNumero(getEndComNumero());
		clienteImpl.setEndComComplemento(getEndComComplemento());
		clienteImpl.setEndComCep(getEndComCep());
		clienteImpl.setEndComBairro(getEndComBairro());
		clienteImpl.setEndComCidade(getEndComCidade());
		clienteImpl.setEndComUf(getEndComUf());
		clienteImpl.setEndComPais(getEndComPais());
		clienteImpl.setEndResLogradouro(getEndResLogradouro());
		clienteImpl.setEndResNumero(getEndResNumero());
		clienteImpl.setEndResComplemento(getEndResComplemento());
		clienteImpl.setEndResCep(getEndResCep());
		clienteImpl.setEndResBairro(getEndResBairro());
		clienteImpl.setEndResCidade(getEndResCidade());
		clienteImpl.setEndResUf(getEndResUf());
		clienteImpl.setEndResPais(getEndResPais());
		clienteImpl.setTelComDdd(getTelComDdd());
		clienteImpl.setVersao(getVersao());
		clienteImpl.setLogoTipoId(getLogoTipoId());
		clienteImpl.setObservacao(getObservacao());

		clienteImpl.resetOriginalValues();

		return clienteImpl;
	}

	@Override
	public int compareTo(Cliente cliente) {
		int value = 0;

		value = getNome().compareTo(cliente.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Cliente)) {
			return false;
		}

		Cliente cliente = (Cliente)obj;

		long primaryKey = cliente.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ClienteModelImpl clienteModelImpl = this;

		clienteModelImpl._originalUuid = clienteModelImpl._uuid;

		clienteModelImpl._originalCompanyId = clienteModelImpl._companyId;

		clienteModelImpl._setOriginalCompanyId = false;

		clienteModelImpl._originalGroupId = clienteModelImpl._groupId;

		clienteModelImpl._setOriginalGroupId = false;

		clienteModelImpl._originalNome = clienteModelImpl._nome;

		clienteModelImpl._originalRgInscricaoMun = clienteModelImpl._rgInscricaoMun;

		clienteModelImpl._originalCpfCnpj = clienteModelImpl._cpfCnpj;

		clienteModelImpl._originalDataNascimento = clienteModelImpl._dataNascimento;

		clienteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Cliente> toCacheModel() {
		ClienteCacheModel clienteCacheModel = new ClienteCacheModel();

		clienteCacheModel.uuid = getUuid();

		String uuid = clienteCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			clienteCacheModel.uuid = null;
		}

		clienteCacheModel.clienteId = getClienteId();

		clienteCacheModel.companyId = getCompanyId();

		clienteCacheModel.groupId = getGroupId();

		clienteCacheModel.createUserId = getCreateUserId();

		clienteCacheModel.modifiedUserId = getModifiedUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			clienteCacheModel.createDate = createDate.getTime();
		}
		else {
			clienteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			clienteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			clienteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		clienteCacheModel.nome = getNome();

		String nome = clienteCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			clienteCacheModel.nome = null;
		}

		clienteCacheModel.rgInscricaoMun = getRgInscricaoMun();

		String rgInscricaoMun = clienteCacheModel.rgInscricaoMun;

		if ((rgInscricaoMun != null) && (rgInscricaoMun.length() == 0)) {
			clienteCacheModel.rgInscricaoMun = null;
		}

		clienteCacheModel.rgOrgaoEmissor = getRgOrgaoEmissor();

		String rgOrgaoEmissor = clienteCacheModel.rgOrgaoEmissor;

		if ((rgOrgaoEmissor != null) && (rgOrgaoEmissor.length() == 0)) {
			clienteCacheModel.rgOrgaoEmissor = null;
		}

		Date rgDataEmissao = getRgDataEmissao();

		if (rgDataEmissao != null) {
			clienteCacheModel.rgDataEmissao = rgDataEmissao.getTime();
		}
		else {
			clienteCacheModel.rgDataEmissao = Long.MIN_VALUE;
		}

		clienteCacheModel.tipoPessoa = getTipoPessoa();

		String tipoPessoa = clienteCacheModel.tipoPessoa;

		if ((tipoPessoa != null) && (tipoPessoa.length() == 0)) {
			clienteCacheModel.tipoPessoa = null;
		}

		clienteCacheModel.cpfCnpj = getCpfCnpj();

		String cpfCnpj = clienteCacheModel.cpfCnpj;

		if ((cpfCnpj != null) && (cpfCnpj.length() == 0)) {
			clienteCacheModel.cpfCnpj = null;
		}

		clienteCacheModel.sexo = getSexo();

		String sexo = clienteCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			clienteCacheModel.sexo = null;
		}

		clienteCacheModel.estadoCivil = getEstadoCivil();

		String estadoCivil = clienteCacheModel.estadoCivil;

		if ((estadoCivil != null) && (estadoCivil.length() == 0)) {
			clienteCacheModel.estadoCivil = null;
		}

		Date dataNascimento = getDataNascimento();

		if (dataNascimento != null) {
			clienteCacheModel.dataNascimento = dataNascimento.getTime();
		}
		else {
			clienteCacheModel.dataNascimento = Long.MIN_VALUE;
		}

		clienteCacheModel.endComLogradouro = getEndComLogradouro();

		String endComLogradouro = clienteCacheModel.endComLogradouro;

		if ((endComLogradouro != null) && (endComLogradouro.length() == 0)) {
			clienteCacheModel.endComLogradouro = null;
		}

		clienteCacheModel.endComNumero = getEndComNumero();

		String endComNumero = clienteCacheModel.endComNumero;

		if ((endComNumero != null) && (endComNumero.length() == 0)) {
			clienteCacheModel.endComNumero = null;
		}

		clienteCacheModel.endComComplemento = getEndComComplemento();

		String endComComplemento = clienteCacheModel.endComComplemento;

		if ((endComComplemento != null) && (endComComplemento.length() == 0)) {
			clienteCacheModel.endComComplemento = null;
		}

		clienteCacheModel.endComCep = getEndComCep();

		String endComCep = clienteCacheModel.endComCep;

		if ((endComCep != null) && (endComCep.length() == 0)) {
			clienteCacheModel.endComCep = null;
		}

		clienteCacheModel.endComBairro = getEndComBairro();

		String endComBairro = clienteCacheModel.endComBairro;

		if ((endComBairro != null) && (endComBairro.length() == 0)) {
			clienteCacheModel.endComBairro = null;
		}

		clienteCacheModel.endComCidade = getEndComCidade();

		clienteCacheModel.endComUf = getEndComUf();

		String endComUf = clienteCacheModel.endComUf;

		if ((endComUf != null) && (endComUf.length() == 0)) {
			clienteCacheModel.endComUf = null;
		}

		clienteCacheModel.endComPais = getEndComPais();

		String endComPais = clienteCacheModel.endComPais;

		if ((endComPais != null) && (endComPais.length() == 0)) {
			clienteCacheModel.endComPais = null;
		}

		clienteCacheModel.endResLogradouro = getEndResLogradouro();

		String endResLogradouro = clienteCacheModel.endResLogradouro;

		if ((endResLogradouro != null) && (endResLogradouro.length() == 0)) {
			clienteCacheModel.endResLogradouro = null;
		}

		clienteCacheModel.endResNumero = getEndResNumero();

		String endResNumero = clienteCacheModel.endResNumero;

		if ((endResNumero != null) && (endResNumero.length() == 0)) {
			clienteCacheModel.endResNumero = null;
		}

		clienteCacheModel.endResComplemento = getEndResComplemento();

		String endResComplemento = clienteCacheModel.endResComplemento;

		if ((endResComplemento != null) && (endResComplemento.length() == 0)) {
			clienteCacheModel.endResComplemento = null;
		}

		clienteCacheModel.endResCep = getEndResCep();

		String endResCep = clienteCacheModel.endResCep;

		if ((endResCep != null) && (endResCep.length() == 0)) {
			clienteCacheModel.endResCep = null;
		}

		clienteCacheModel.endResBairro = getEndResBairro();

		String endResBairro = clienteCacheModel.endResBairro;

		if ((endResBairro != null) && (endResBairro.length() == 0)) {
			clienteCacheModel.endResBairro = null;
		}

		clienteCacheModel.endResCidade = getEndResCidade();

		clienteCacheModel.endResUf = getEndResUf();

		String endResUf = clienteCacheModel.endResUf;

		if ((endResUf != null) && (endResUf.length() == 0)) {
			clienteCacheModel.endResUf = null;
		}

		clienteCacheModel.endResPais = getEndResPais();

		String endResPais = clienteCacheModel.endResPais;

		if ((endResPais != null) && (endResPais.length() == 0)) {
			clienteCacheModel.endResPais = null;
		}

		clienteCacheModel.telComDdd = getTelComDdd();

		String telComDdd = clienteCacheModel.telComDdd;

		if ((telComDdd != null) && (telComDdd.length() == 0)) {
			clienteCacheModel.telComDdd = null;
		}

		clienteCacheModel.versao = getVersao();

		clienteCacheModel.logoTipoId = getLogoTipoId();

		clienteCacheModel.observacao = getObservacao();

		String observacao = clienteCacheModel.observacao;

		if ((observacao != null) && (observacao.length() == 0)) {
			clienteCacheModel.observacao = null;
		}

		return clienteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(75);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", clienteId=");
		sb.append(getClienteId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createUserId=");
		sb.append(getCreateUserId());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", rgInscricaoMun=");
		sb.append(getRgInscricaoMun());
		sb.append(", rgOrgaoEmissor=");
		sb.append(getRgOrgaoEmissor());
		sb.append(", rgDataEmissao=");
		sb.append(getRgDataEmissao());
		sb.append(", tipoPessoa=");
		sb.append(getTipoPessoa());
		sb.append(", cpfCnpj=");
		sb.append(getCpfCnpj());
		sb.append(", sexo=");
		sb.append(getSexo());
		sb.append(", estadoCivil=");
		sb.append(getEstadoCivil());
		sb.append(", dataNascimento=");
		sb.append(getDataNascimento());
		sb.append(", endComLogradouro=");
		sb.append(getEndComLogradouro());
		sb.append(", endComNumero=");
		sb.append(getEndComNumero());
		sb.append(", endComComplemento=");
		sb.append(getEndComComplemento());
		sb.append(", endComCep=");
		sb.append(getEndComCep());
		sb.append(", endComBairro=");
		sb.append(getEndComBairro());
		sb.append(", endComCidade=");
		sb.append(getEndComCidade());
		sb.append(", endComUf=");
		sb.append(getEndComUf());
		sb.append(", endComPais=");
		sb.append(getEndComPais());
		sb.append(", endResLogradouro=");
		sb.append(getEndResLogradouro());
		sb.append(", endResNumero=");
		sb.append(getEndResNumero());
		sb.append(", endResComplemento=");
		sb.append(getEndResComplemento());
		sb.append(", endResCep=");
		sb.append(getEndResCep());
		sb.append(", endResBairro=");
		sb.append(getEndResBairro());
		sb.append(", endResCidade=");
		sb.append(getEndResCidade());
		sb.append(", endResUf=");
		sb.append(getEndResUf());
		sb.append(", endResPais=");
		sb.append(getEndResPais());
		sb.append(", telComDdd=");
		sb.append(getTelComDdd());
		sb.append(", versao=");
		sb.append(getVersao());
		sb.append(", logoTipoId=");
		sb.append(getLogoTipoId());
		sb.append(", observacao=");
		sb.append(getObservacao());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(115);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.cliente.model.Cliente");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clienteId</column-name><column-value><![CDATA[");
		sb.append(getClienteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createUserId</column-name><column-value><![CDATA[");
		sb.append(getCreateUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgInscricaoMun</column-name><column-value><![CDATA[");
		sb.append(getRgInscricaoMun());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgOrgaoEmissor</column-name><column-value><![CDATA[");
		sb.append(getRgOrgaoEmissor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgDataEmissao</column-name><column-value><![CDATA[");
		sb.append(getRgDataEmissao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoPessoa</column-name><column-value><![CDATA[");
		sb.append(getTipoPessoa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cpfCnpj</column-name><column-value><![CDATA[");
		sb.append(getCpfCnpj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexo</column-name><column-value><![CDATA[");
		sb.append(getSexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoCivil</column-name><column-value><![CDATA[");
		sb.append(getEstadoCivil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataNascimento</column-name><column-value><![CDATA[");
		sb.append(getDataNascimento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndComLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComNumero</column-name><column-value><![CDATA[");
		sb.append(getEndComNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComComplemento</column-name><column-value><![CDATA[");
		sb.append(getEndComComplemento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCep</column-name><column-value><![CDATA[");
		sb.append(getEndComCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComBairro</column-name><column-value><![CDATA[");
		sb.append(getEndComBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCidade</column-name><column-value><![CDATA[");
		sb.append(getEndComCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComUf</column-name><column-value><![CDATA[");
		sb.append(getEndComUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComPais</column-name><column-value><![CDATA[");
		sb.append(getEndComPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndResLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResNumero</column-name><column-value><![CDATA[");
		sb.append(getEndResNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResComplemento</column-name><column-value><![CDATA[");
		sb.append(getEndResComplemento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCep</column-name><column-value><![CDATA[");
		sb.append(getEndResCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResBairro</column-name><column-value><![CDATA[");
		sb.append(getEndResBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCidade</column-name><column-value><![CDATA[");
		sb.append(getEndResCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResUf</column-name><column-value><![CDATA[");
		sb.append(getEndResUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResPais</column-name><column-value><![CDATA[");
		sb.append(getEndResPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telComDdd</column-name><column-value><![CDATA[");
		sb.append(getTelComDdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>versao</column-name><column-value><![CDATA[");
		sb.append(getVersao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logoTipoId</column-name><column-value><![CDATA[");
		sb.append(getLogoTipoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacao</column-name><column-value><![CDATA[");
		sb.append(getObservacao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Cliente.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Cliente.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _clienteId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _createUserId;
	private String _createUserUuid;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _nome;
	private String _originalNome;
	private String _rgInscricaoMun;
	private String _originalRgInscricaoMun;
	private String _rgOrgaoEmissor;
	private Date _rgDataEmissao;
	private String _tipoPessoa;
	private String _cpfCnpj;
	private String _originalCpfCnpj;
	private String _sexo;
	private String _estadoCivil;
	private Date _dataNascimento;
	private Date _originalDataNascimento;
	private String _endComLogradouro;
	private String _endComNumero;
	private String _endComComplemento;
	private String _endComCep;
	private String _endComBairro;
	private long _endComCidade;
	private String _endComUf;
	private String _endComPais;
	private String _endResLogradouro;
	private String _endResNumero;
	private String _endResComplemento;
	private String _endResCep;
	private String _endResBairro;
	private long _endResCidade;
	private String _endResUf;
	private String _endResPais;
	private String _telComDdd;
	private double _versao;
	private long _logoTipoId;
	private String _observacao;
	private long _columnBitmask;
	private Cliente _escapedModel;
}