/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.model.impl;

import br.com.prodevelopment.cliente.model.ClienteLimCredito;
import br.com.prodevelopment.cliente.model.ClienteLimCreditoModel;
import br.com.prodevelopment.cliente.model.ClienteLimCreditoSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ClienteLimCredito service. Represents a row in the &quot;ClienteLimCredito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.cliente.model.ClienteLimCreditoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClienteLimCreditoImpl}.
 * </p>
 *
 * @author marcelo
 * @see ClienteLimCreditoImpl
 * @see br.com.prodevelopment.cliente.model.ClienteLimCredito
 * @see br.com.prodevelopment.cliente.model.ClienteLimCreditoModel
 * @generated
 */
@JSON(strict = true)
public class ClienteLimCreditoModelImpl extends BaseModelImpl<ClienteLimCredito>
	implements ClienteLimCreditoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cliente lim credito model instance should use the {@link br.com.prodevelopment.cliente.model.ClienteLimCredito} interface instead.
	 */
	public static final String TABLE_NAME = "ClienteLimCredito";
	public static final Object[][] TABLE_COLUMNS = {
			{ "clienteLimCreditoId", Types.BIGINT },
			{ "valorLimiteMaximoCredito", Types.DOUBLE },
			{ "dataLimiteMaximoCredito", Types.TIMESTAMP },
			{ "valorLimiteMaximoCheque", Types.DOUBLE },
			{ "qtdeLimiteMaximoCheque", Types.INTEGER },
			{ "clienteId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ClienteLimCredito (clienteLimCreditoId LONG not null primary key,valorLimiteMaximoCredito DOUBLE,dataLimiteMaximoCredito DATE null,valorLimiteMaximoCheque DOUBLE,qtdeLimiteMaximoCheque INTEGER,clienteId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ClienteLimCredito";
	public static final String ORDER_BY_JPQL = " ORDER BY clienteLimCredito.clienteLimCreditoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ClienteLimCredito.clienteLimCreditoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.cliente.model.ClienteLimCredito"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.cliente.model.ClienteLimCredito"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.cliente.model.ClienteLimCredito"),
			true);
	public static long CLIENTEID_COLUMN_BITMASK = 1L;
	public static long CLIENTELIMCREDITOID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ClienteLimCredito toModel(ClienteLimCreditoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ClienteLimCredito model = new ClienteLimCreditoImpl();

		model.setClienteLimCreditoId(soapModel.getClienteLimCreditoId());
		model.setValorLimiteMaximoCredito(soapModel.getValorLimiteMaximoCredito());
		model.setDataLimiteMaximoCredito(soapModel.getDataLimiteMaximoCredito());
		model.setValorLimiteMaximoCheque(soapModel.getValorLimiteMaximoCheque());
		model.setQtdeLimiteMaximoCheque(soapModel.getQtdeLimiteMaximoCheque());
		model.setClienteId(soapModel.getClienteId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ClienteLimCredito> toModels(
		ClienteLimCreditoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ClienteLimCredito> models = new ArrayList<ClienteLimCredito>(soapModels.length);

		for (ClienteLimCreditoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.cliente.model.ClienteLimCredito"));

	public ClienteLimCreditoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _clienteLimCreditoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClienteLimCreditoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _clienteLimCreditoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ClienteLimCredito.class;
	}

	@Override
	public String getModelClassName() {
		return ClienteLimCredito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("clienteLimCreditoId", getClienteLimCreditoId());
		attributes.put("valorLimiteMaximoCredito", getValorLimiteMaximoCredito());
		attributes.put("dataLimiteMaximoCredito", getDataLimiteMaximoCredito());
		attributes.put("valorLimiteMaximoCheque", getValorLimiteMaximoCheque());
		attributes.put("qtdeLimiteMaximoCheque", getQtdeLimiteMaximoCheque());
		attributes.put("clienteId", getClienteId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long clienteLimCreditoId = (Long)attributes.get("clienteLimCreditoId");

		if (clienteLimCreditoId != null) {
			setClienteLimCreditoId(clienteLimCreditoId);
		}

		Double valorLimiteMaximoCredito = (Double)attributes.get(
				"valorLimiteMaximoCredito");

		if (valorLimiteMaximoCredito != null) {
			setValorLimiteMaximoCredito(valorLimiteMaximoCredito);
		}

		Date dataLimiteMaximoCredito = (Date)attributes.get(
				"dataLimiteMaximoCredito");

		if (dataLimiteMaximoCredito != null) {
			setDataLimiteMaximoCredito(dataLimiteMaximoCredito);
		}

		Double valorLimiteMaximoCheque = (Double)attributes.get(
				"valorLimiteMaximoCheque");

		if (valorLimiteMaximoCheque != null) {
			setValorLimiteMaximoCheque(valorLimiteMaximoCheque);
		}

		Integer qtdeLimiteMaximoCheque = (Integer)attributes.get(
				"qtdeLimiteMaximoCheque");

		if (qtdeLimiteMaximoCheque != null) {
			setQtdeLimiteMaximoCheque(qtdeLimiteMaximoCheque);
		}

		Long clienteId = (Long)attributes.get("clienteId");

		if (clienteId != null) {
			setClienteId(clienteId);
		}
	}

	@JSON
	@Override
	public long getClienteLimCreditoId() {
		return _clienteLimCreditoId;
	}

	@Override
	public void setClienteLimCreditoId(long clienteLimCreditoId) {
		_columnBitmask = -1L;

		_clienteLimCreditoId = clienteLimCreditoId;
	}

	@JSON
	@Override
	public double getValorLimiteMaximoCredito() {
		return _valorLimiteMaximoCredito;
	}

	@Override
	public void setValorLimiteMaximoCredito(double valorLimiteMaximoCredito) {
		_valorLimiteMaximoCredito = valorLimiteMaximoCredito;
	}

	@JSON
	@Override
	public Date getDataLimiteMaximoCredito() {
		return _dataLimiteMaximoCredito;
	}

	@Override
	public void setDataLimiteMaximoCredito(Date dataLimiteMaximoCredito) {
		_dataLimiteMaximoCredito = dataLimiteMaximoCredito;
	}

	@JSON
	@Override
	public double getValorLimiteMaximoCheque() {
		return _valorLimiteMaximoCheque;
	}

	@Override
	public void setValorLimiteMaximoCheque(double valorLimiteMaximoCheque) {
		_valorLimiteMaximoCheque = valorLimiteMaximoCheque;
	}

	@JSON
	@Override
	public int getQtdeLimiteMaximoCheque() {
		return _qtdeLimiteMaximoCheque;
	}

	@Override
	public void setQtdeLimiteMaximoCheque(int qtdeLimiteMaximoCheque) {
		_qtdeLimiteMaximoCheque = qtdeLimiteMaximoCheque;
	}

	@JSON
	@Override
	public long getClienteId() {
		return _clienteId;
	}

	@Override
	public void setClienteId(long clienteId) {
		_columnBitmask |= CLIENTEID_COLUMN_BITMASK;

		if (!_setOriginalClienteId) {
			_setOriginalClienteId = true;

			_originalClienteId = _clienteId;
		}

		_clienteId = clienteId;
	}

	public long getOriginalClienteId() {
		return _originalClienteId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ClienteLimCredito.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ClienteLimCredito toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ClienteLimCredito)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClienteLimCreditoImpl clienteLimCreditoImpl = new ClienteLimCreditoImpl();

		clienteLimCreditoImpl.setClienteLimCreditoId(getClienteLimCreditoId());
		clienteLimCreditoImpl.setValorLimiteMaximoCredito(getValorLimiteMaximoCredito());
		clienteLimCreditoImpl.setDataLimiteMaximoCredito(getDataLimiteMaximoCredito());
		clienteLimCreditoImpl.setValorLimiteMaximoCheque(getValorLimiteMaximoCheque());
		clienteLimCreditoImpl.setQtdeLimiteMaximoCheque(getQtdeLimiteMaximoCheque());
		clienteLimCreditoImpl.setClienteId(getClienteId());

		clienteLimCreditoImpl.resetOriginalValues();

		return clienteLimCreditoImpl;
	}

	@Override
	public int compareTo(ClienteLimCredito clienteLimCredito) {
		int value = 0;

		if (getClienteLimCreditoId() < clienteLimCredito.getClienteLimCreditoId()) {
			value = -1;
		}
		else if (getClienteLimCreditoId() > clienteLimCredito.getClienteLimCreditoId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ClienteLimCredito)) {
			return false;
		}

		ClienteLimCredito clienteLimCredito = (ClienteLimCredito)obj;

		long primaryKey = clienteLimCredito.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ClienteLimCreditoModelImpl clienteLimCreditoModelImpl = this;

		clienteLimCreditoModelImpl._originalClienteId = clienteLimCreditoModelImpl._clienteId;

		clienteLimCreditoModelImpl._setOriginalClienteId = false;

		clienteLimCreditoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ClienteLimCredito> toCacheModel() {
		ClienteLimCreditoCacheModel clienteLimCreditoCacheModel = new ClienteLimCreditoCacheModel();

		clienteLimCreditoCacheModel.clienteLimCreditoId = getClienteLimCreditoId();

		clienteLimCreditoCacheModel.valorLimiteMaximoCredito = getValorLimiteMaximoCredito();

		Date dataLimiteMaximoCredito = getDataLimiteMaximoCredito();

		if (dataLimiteMaximoCredito != null) {
			clienteLimCreditoCacheModel.dataLimiteMaximoCredito = dataLimiteMaximoCredito.getTime();
		}
		else {
			clienteLimCreditoCacheModel.dataLimiteMaximoCredito = Long.MIN_VALUE;
		}

		clienteLimCreditoCacheModel.valorLimiteMaximoCheque = getValorLimiteMaximoCheque();

		clienteLimCreditoCacheModel.qtdeLimiteMaximoCheque = getQtdeLimiteMaximoCheque();

		clienteLimCreditoCacheModel.clienteId = getClienteId();

		return clienteLimCreditoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{clienteLimCreditoId=");
		sb.append(getClienteLimCreditoId());
		sb.append(", valorLimiteMaximoCredito=");
		sb.append(getValorLimiteMaximoCredito());
		sb.append(", dataLimiteMaximoCredito=");
		sb.append(getDataLimiteMaximoCredito());
		sb.append(", valorLimiteMaximoCheque=");
		sb.append(getValorLimiteMaximoCheque());
		sb.append(", qtdeLimiteMaximoCheque=");
		sb.append(getQtdeLimiteMaximoCheque());
		sb.append(", clienteId=");
		sb.append(getClienteId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.cliente.model.ClienteLimCredito");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>clienteLimCreditoId</column-name><column-value><![CDATA[");
		sb.append(getClienteLimCreditoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>valorLimiteMaximoCredito</column-name><column-value><![CDATA[");
		sb.append(getValorLimiteMaximoCredito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataLimiteMaximoCredito</column-name><column-value><![CDATA[");
		sb.append(getDataLimiteMaximoCredito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>valorLimiteMaximoCheque</column-name><column-value><![CDATA[");
		sb.append(getValorLimiteMaximoCheque());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>qtdeLimiteMaximoCheque</column-name><column-value><![CDATA[");
		sb.append(getQtdeLimiteMaximoCheque());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clienteId</column-name><column-value><![CDATA[");
		sb.append(getClienteId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ClienteLimCredito.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ClienteLimCredito.class
		};
	private long _clienteLimCreditoId;
	private double _valorLimiteMaximoCredito;
	private Date _dataLimiteMaximoCredito;
	private double _valorLimiteMaximoCheque;
	private int _qtdeLimiteMaximoCheque;
	private long _clienteId;
	private long _originalClienteId;
	private boolean _setOriginalClienteId;
	private long _columnBitmask;
	private ClienteLimCredito _escapedModel;
}