/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.funcionario.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Cargo service. Represents a row in the &quot;Cargo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.funcionario.model.impl.CargoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.funcionario.model.impl.CargoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Cargo
 * @see br.com.prodevelopment.funcionario.model.impl.CargoImpl
 * @see br.com.prodevelopment.funcionario.model.impl.CargoModelImpl
 * @generated
 */
public interface CargoModel extends BaseModel<Cargo>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cargo model instance should use the {@link Cargo} interface instead.
	 */

	/**
	 * Returns the primary key of this cargo.
	 *
	 * @return the primary key of this cargo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cargo.
	 *
	 * @param primaryKey the primary key of this cargo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cargo.
	 *
	 * @return the uuid of this cargo
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cargo.
	 *
	 * @param uuid the uuid of this cargo
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cargo ID of this cargo.
	 *
	 * @return the cargo ID of this cargo
	 */
	public long getCargoId();

	/**
	 * Sets the cargo ID of this cargo.
	 *
	 * @param cargoId the cargo ID of this cargo
	 */
	public void setCargoId(long cargoId);

	/**
	 * Returns the company ID of this cargo.
	 *
	 * @return the company ID of this cargo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cargo.
	 *
	 * @param companyId the company ID of this cargo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this cargo.
	 *
	 * @return the group ID of this cargo
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cargo.
	 *
	 * @param groupId the group ID of this cargo
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this cargo.
	 *
	 * @return the create user ID of this cargo
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this cargo.
	 *
	 * @param createUserId the create user ID of this cargo
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this cargo.
	 *
	 * @return the create user uuid of this cargo
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this cargo.
	 *
	 * @param createUserUuid the create user uuid of this cargo
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this cargo.
	 *
	 * @return the modified user ID of this cargo
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this cargo.
	 *
	 * @param modifiedUserId the modified user ID of this cargo
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this cargo.
	 *
	 * @return the modified user uuid of this cargo
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this cargo.
	 *
	 * @param modifiedUserUuid the modified user uuid of this cargo
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this cargo.
	 *
	 * @return the create date of this cargo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cargo.
	 *
	 * @param createDate the create date of this cargo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cargo.
	 *
	 * @return the modified date of this cargo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cargo.
	 *
	 * @param modifiedDate the modified date of this cargo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this cargo.
	 *
	 * @return the nome of this cargo
	 */
	public String getNome();

	/**
	 * Returns the localized nome of this cargo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized nome of this cargo
	 */
	@AutoEscape
	public String getNome(Locale locale);

	/**
	 * Returns the localized nome of this cargo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nome of this cargo. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getNome(Locale locale, boolean useDefault);

	/**
	 * Returns the localized nome of this cargo in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized nome of this cargo
	 */
	@AutoEscape
	public String getNome(String languageId);

	/**
	 * Returns the localized nome of this cargo in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized nome of this cargo
	 */
	@AutoEscape
	public String getNome(String languageId, boolean useDefault);

	@AutoEscape
	public String getNomeCurrentLanguageId();

	@AutoEscape
	public String getNomeCurrentValue();

	/**
	 * Returns a map of the locales and localized nomes of this cargo.
	 *
	 * @return the locales and localized nomes of this cargo
	 */
	public Map<Locale, String> getNomeMap();

	/**
	 * Sets the nome of this cargo.
	 *
	 * @param nome the nome of this cargo
	 */
	public void setNome(String nome);

	/**
	 * Sets the localized nome of this cargo in the language.
	 *
	 * @param nome the localized nome of this cargo
	 * @param locale the locale of the language
	 */
	public void setNome(String nome, Locale locale);

	/**
	 * Sets the localized nome of this cargo in the language, and sets the default locale.
	 *
	 * @param nome the localized nome of this cargo
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setNome(String nome, Locale locale, Locale defaultLocale);

	public void setNomeCurrentLanguageId(String languageId);

	/**
	 * Sets the localized nomes of this cargo from the map of locales and localized nomes.
	 *
	 * @param nomeMap the locales and localized nomes of this cargo
	 */
	public void setNomeMap(Map<Locale, String> nomeMap);

	/**
	 * Sets the localized nomes of this cargo from the map of locales and localized nomes, and sets the default locale.
	 *
	 * @param nomeMap the locales and localized nomes of this cargo
	 * @param defaultLocale the default locale
	 */
	public void setNomeMap(Map<Locale, String> nomeMap, Locale defaultLocale);

	/**
	 * Returns the versao of this cargo.
	 *
	 * @return the versao of this cargo
	 */
	public double getVersao();

	/**
	 * Sets the versao of this cargo.
	 *
	 * @param versao the versao of this cargo
	 */
	public void setVersao(double versao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(br.com.prodevelopment.funcionario.model.Cargo cargo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.funcionario.model.Cargo> toCacheModel();

	@Override
	public br.com.prodevelopment.funcionario.model.Cargo toEscapedModel();

	@Override
	public br.com.prodevelopment.funcionario.model.Cargo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}