/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.funcionario.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Funcionario service. Represents a row in the &quot;Funcionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.funcionario.model.impl.FuncionarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.funcionario.model.impl.FuncionarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Funcionario
 * @see br.com.prodevelopment.funcionario.model.impl.FuncionarioImpl
 * @see br.com.prodevelopment.funcionario.model.impl.FuncionarioModelImpl
 * @generated
 */
public interface FuncionarioModel extends BaseModel<Funcionario>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a funcionario model instance should use the {@link Funcionario} interface instead.
	 */

	/**
	 * Returns the primary key of this funcionario.
	 *
	 * @return the primary key of this funcionario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this funcionario.
	 *
	 * @param primaryKey the primary key of this funcionario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this funcionario.
	 *
	 * @return the uuid of this funcionario
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this funcionario.
	 *
	 * @param uuid the uuid of this funcionario
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the funcionario ID of this funcionario.
	 *
	 * @return the funcionario ID of this funcionario
	 */
	public long getFuncionarioId();

	/**
	 * Sets the funcionario ID of this funcionario.
	 *
	 * @param funcionarioId the funcionario ID of this funcionario
	 */
	public void setFuncionarioId(long funcionarioId);

	/**
	 * Returns the company ID of this funcionario.
	 *
	 * @return the company ID of this funcionario
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this funcionario.
	 *
	 * @param companyId the company ID of this funcionario
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this funcionario.
	 *
	 * @return the group ID of this funcionario
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this funcionario.
	 *
	 * @param groupId the group ID of this funcionario
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this funcionario.
	 *
	 * @return the create user ID of this funcionario
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this funcionario.
	 *
	 * @param createUserId the create user ID of this funcionario
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this funcionario.
	 *
	 * @return the create user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this funcionario.
	 *
	 * @param createUserUuid the create user uuid of this funcionario
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this funcionario.
	 *
	 * @return the modified user ID of this funcionario
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this funcionario.
	 *
	 * @param modifiedUserId the modified user ID of this funcionario
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this funcionario.
	 *
	 * @return the modified user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this funcionario.
	 *
	 * @param modifiedUserUuid the modified user uuid of this funcionario
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this funcionario.
	 *
	 * @return the create date of this funcionario
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this funcionario.
	 *
	 * @param createDate the create date of this funcionario
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this funcionario.
	 *
	 * @return the modified date of this funcionario
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this funcionario.
	 *
	 * @param modifiedDate the modified date of this funcionario
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this funcionario.
	 *
	 * @return the nome of this funcionario
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this funcionario.
	 *
	 * @param nome the nome of this funcionario
	 */
	public void setNome(String nome);

	/**
	 * Returns the nome reduzido of this funcionario.
	 *
	 * @return the nome reduzido of this funcionario
	 */
	@AutoEscape
	public String getNomeReduzido();

	/**
	 * Sets the nome reduzido of this funcionario.
	 *
	 * @param nomeReduzido the nome reduzido of this funcionario
	 */
	public void setNomeReduzido(String nomeReduzido);

	/**
	 * Returns the observacao of this funcionario.
	 *
	 * @return the observacao of this funcionario
	 */
	@AutoEscape
	public String getObservacao();

	/**
	 * Sets the observacao of this funcionario.
	 *
	 * @param observacao the observacao of this funcionario
	 */
	public void setObservacao(String observacao);

	/**
	 * Returns the rg of this funcionario.
	 *
	 * @return the rg of this funcionario
	 */
	@AutoEscape
	public String getRg();

	/**
	 * Sets the rg of this funcionario.
	 *
	 * @param rg the rg of this funcionario
	 */
	public void setRg(String rg);

	/**
	 * Returns the rg orgao emissor of this funcionario.
	 *
	 * @return the rg orgao emissor of this funcionario
	 */
	@AutoEscape
	public String getRgOrgaoEmissor();

	/**
	 * Sets the rg orgao emissor of this funcionario.
	 *
	 * @param rgOrgaoEmissor the rg orgao emissor of this funcionario
	 */
	public void setRgOrgaoEmissor(String rgOrgaoEmissor);

	/**
	 * Returns the rg data emissao of this funcionario.
	 *
	 * @return the rg data emissao of this funcionario
	 */
	public Date getRgDataEmissao();

	/**
	 * Sets the rg data emissao of this funcionario.
	 *
	 * @param rgDataEmissao the rg data emissao of this funcionario
	 */
	public void setRgDataEmissao(Date rgDataEmissao);

	/**
	 * Returns the cpf of this funcionario.
	 *
	 * @return the cpf of this funcionario
	 */
	@AutoEscape
	public String getCpf();

	/**
	 * Sets the cpf of this funcionario.
	 *
	 * @param cpf the cpf of this funcionario
	 */
	public void setCpf(String cpf);

	/**
	 * Returns the sexo of this funcionario.
	 *
	 * @return the sexo of this funcionario
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this funcionario.
	 *
	 * @param sexo the sexo of this funcionario
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the estado civil of this funcionario.
	 *
	 * @return the estado civil of this funcionario
	 */
	@AutoEscape
	public String getEstadoCivil();

	/**
	 * Sets the estado civil of this funcionario.
	 *
	 * @param estadoCivil the estado civil of this funcionario
	 */
	public void setEstadoCivil(String estadoCivil);

	/**
	 * Returns the data nascimento of this funcionario.
	 *
	 * @return the data nascimento of this funcionario
	 */
	public Date getDataNascimento();

	/**
	 * Sets the data nascimento of this funcionario.
	 *
	 * @param dataNascimento the data nascimento of this funcionario
	 */
	public void setDataNascimento(Date dataNascimento);

	/**
	 * Returns the end com logradouro of this funcionario.
	 *
	 * @return the end com logradouro of this funcionario
	 */
	@AutoEscape
	public String getEndComLogradouro();

	/**
	 * Sets the end com logradouro of this funcionario.
	 *
	 * @param endComLogradouro the end com logradouro of this funcionario
	 */
	public void setEndComLogradouro(String endComLogradouro);

	/**
	 * Returns the end com numero of this funcionario.
	 *
	 * @return the end com numero of this funcionario
	 */
	@AutoEscape
	public String getEndComNumero();

	/**
	 * Sets the end com numero of this funcionario.
	 *
	 * @param endComNumero the end com numero of this funcionario
	 */
	public void setEndComNumero(String endComNumero);

	/**
	 * Returns the end com complemento of this funcionario.
	 *
	 * @return the end com complemento of this funcionario
	 */
	@AutoEscape
	public String getEndComComplemento();

	/**
	 * Sets the end com complemento of this funcionario.
	 *
	 * @param endComComplemento the end com complemento of this funcionario
	 */
	public void setEndComComplemento(String endComComplemento);

	/**
	 * Returns the end com cep of this funcionario.
	 *
	 * @return the end com cep of this funcionario
	 */
	@AutoEscape
	public String getEndComCep();

	/**
	 * Sets the end com cep of this funcionario.
	 *
	 * @param endComCep the end com cep of this funcionario
	 */
	public void setEndComCep(String endComCep);

	/**
	 * Returns the end com bairro of this funcionario.
	 *
	 * @return the end com bairro of this funcionario
	 */
	@AutoEscape
	public String getEndComBairro();

	/**
	 * Sets the end com bairro of this funcionario.
	 *
	 * @param endComBairro the end com bairro of this funcionario
	 */
	public void setEndComBairro(String endComBairro);

	/**
	 * Returns the end com cidade of this funcionario.
	 *
	 * @return the end com cidade of this funcionario
	 */
	public long getEndComCidade();

	/**
	 * Sets the end com cidade of this funcionario.
	 *
	 * @param endComCidade the end com cidade of this funcionario
	 */
	public void setEndComCidade(long endComCidade);

	/**
	 * Returns the end com uf of this funcionario.
	 *
	 * @return the end com uf of this funcionario
	 */
	@AutoEscape
	public String getEndComUf();

	/**
	 * Sets the end com uf of this funcionario.
	 *
	 * @param endComUf the end com uf of this funcionario
	 */
	public void setEndComUf(String endComUf);

	/**
	 * Returns the end com pais of this funcionario.
	 *
	 * @return the end com pais of this funcionario
	 */
	@AutoEscape
	public String getEndComPais();

	/**
	 * Sets the end com pais of this funcionario.
	 *
	 * @param endComPais the end com pais of this funcionario
	 */
	public void setEndComPais(String endComPais);

	/**
	 * Returns the end res logradouro of this funcionario.
	 *
	 * @return the end res logradouro of this funcionario
	 */
	@AutoEscape
	public String getEndResLogradouro();

	/**
	 * Sets the end res logradouro of this funcionario.
	 *
	 * @param endResLogradouro the end res logradouro of this funcionario
	 */
	public void setEndResLogradouro(String endResLogradouro);

	/**
	 * Returns the end res numero of this funcionario.
	 *
	 * @return the end res numero of this funcionario
	 */
	@AutoEscape
	public String getEndResNumero();

	/**
	 * Sets the end res numero of this funcionario.
	 *
	 * @param endResNumero the end res numero of this funcionario
	 */
	public void setEndResNumero(String endResNumero);

	/**
	 * Returns the end res complemento of this funcionario.
	 *
	 * @return the end res complemento of this funcionario
	 */
	@AutoEscape
	public String getEndResComplemento();

	/**
	 * Sets the end res complemento of this funcionario.
	 *
	 * @param endResComplemento the end res complemento of this funcionario
	 */
	public void setEndResComplemento(String endResComplemento);

	/**
	 * Returns the end res cep of this funcionario.
	 *
	 * @return the end res cep of this funcionario
	 */
	@AutoEscape
	public String getEndResCep();

	/**
	 * Sets the end res cep of this funcionario.
	 *
	 * @param endResCep the end res cep of this funcionario
	 */
	public void setEndResCep(String endResCep);

	/**
	 * Returns the end res bairro of this funcionario.
	 *
	 * @return the end res bairro of this funcionario
	 */
	@AutoEscape
	public String getEndResBairro();

	/**
	 * Sets the end res bairro of this funcionario.
	 *
	 * @param endResBairro the end res bairro of this funcionario
	 */
	public void setEndResBairro(String endResBairro);

	/**
	 * Returns the end res cidade of this funcionario.
	 *
	 * @return the end res cidade of this funcionario
	 */
	public long getEndResCidade();

	/**
	 * Sets the end res cidade of this funcionario.
	 *
	 * @param endResCidade the end res cidade of this funcionario
	 */
	public void setEndResCidade(long endResCidade);

	/**
	 * Returns the end res uf of this funcionario.
	 *
	 * @return the end res uf of this funcionario
	 */
	@AutoEscape
	public String getEndResUf();

	/**
	 * Sets the end res uf of this funcionario.
	 *
	 * @param endResUf the end res uf of this funcionario
	 */
	public void setEndResUf(String endResUf);

	/**
	 * Returns the end res pais of this funcionario.
	 *
	 * @return the end res pais of this funcionario
	 */
	@AutoEscape
	public String getEndResPais();

	/**
	 * Sets the end res pais of this funcionario.
	 *
	 * @param endResPais the end res pais of this funcionario
	 */
	public void setEndResPais(String endResPais);

	/**
	 * Returns the data entrada of this funcionario.
	 *
	 * @return the data entrada of this funcionario
	 */
	public Date getDataEntrada();

	/**
	 * Sets the data entrada of this funcionario.
	 *
	 * @param dataEntrada the data entrada of this funcionario
	 */
	public void setDataEntrada(Date dataEntrada);

	/**
	 * Returns the data saida of this funcionario.
	 *
	 * @return the data saida of this funcionario
	 */
	public Date getDataSaida();

	/**
	 * Sets the data saida of this funcionario.
	 *
	 * @param dataSaida the data saida of this funcionario
	 */
	public void setDataSaida(Date dataSaida);

	/**
	 * Returns the existe user of this funcionario.
	 *
	 * @return the existe user of this funcionario
	 */
	public Boolean getExisteUser();

	/**
	 * Sets the existe user of this funcionario.
	 *
	 * @param existeUser the existe user of this funcionario
	 */
	public void setExisteUser(Boolean existeUser);

	/**
	 * Returns the user ID of this funcionario.
	 *
	 * @return the user ID of this funcionario
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this funcionario.
	 *
	 * @param userId the user ID of this funcionario
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this funcionario.
	 *
	 * @return the user uuid of this funcionario
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this funcionario.
	 *
	 * @param userUuid the user uuid of this funcionario
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the versao of this funcionario.
	 *
	 * @return the versao of this funcionario
	 */
	public double getVersao();

	/**
	 * Sets the versao of this funcionario.
	 *
	 * @param versao the versao of this funcionario
	 */
	public void setVersao(double versao);

	/**
	 * Returns the cargo ID of this funcionario.
	 *
	 * @return the cargo ID of this funcionario
	 */
	public long getCargoId();

	/**
	 * Sets the cargo ID of this funcionario.
	 *
	 * @param cargoId the cargo ID of this funcionario
	 */
	public void setCargoId(long cargoId);

	/**
	 * Returns the foto ID of this funcionario.
	 *
	 * @return the foto ID of this funcionario
	 */
	public long getFotoId();

	/**
	 * Sets the foto ID of this funcionario.
	 *
	 * @param fotoId the foto ID of this funcionario
	 */
	public void setFotoId(long fotoId);

	/**
	 * Returns the ativo of this funcionario.
	 *
	 * @return the ativo of this funcionario
	 */
	public Boolean getAtivo();

	/**
	 * Sets the ativo of this funcionario.
	 *
	 * @param ativo the ativo of this funcionario
	 */
	public void setAtivo(Boolean ativo);

	/**
	 * Returns the salario of this funcionario.
	 *
	 * @return the salario of this funcionario
	 */
	public double getSalario();

	/**
	 * Sets the salario of this funcionario.
	 *
	 * @param salario the salario of this funcionario
	 */
	public void setSalario(double salario);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.funcionario.model.Funcionario funcionario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.funcionario.model.Funcionario> toCacheModel();

	@Override
	public br.com.prodevelopment.funcionario.model.Funcionario toEscapedModel();

	@Override
	public br.com.prodevelopment.funcionario.model.Funcionario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}