/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.appcomercial.servico.model.impl;

import br.com.prodevelopment.appcomercial.servico.model.Funcionario;
import br.com.prodevelopment.appcomercial.servico.model.FuncionarioModel;
import br.com.prodevelopment.appcomercial.servico.model.FuncionarioSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Funcionario service. Represents a row in the &quot;Funcionario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.appcomercial.servico.model.FuncionarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FuncionarioImpl}.
 * </p>
 *
 * @author marcelo
 * @see FuncionarioImpl
 * @see br.com.prodevelopment.appcomercial.servico.model.Funcionario
 * @see br.com.prodevelopment.appcomercial.servico.model.FuncionarioModel
 * @generated
 */
@JSON(strict = true)
public class FuncionarioModelImpl extends BaseModelImpl<Funcionario>
	implements FuncionarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a funcionario model instance should use the {@link br.com.prodevelopment.appcomercial.servico.model.Funcionario} interface instead.
	 */
	public static final String TABLE_NAME = "Funcionario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "funcionarioId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createUserId", Types.BIGINT },
			{ "modifiedUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "nome", Types.VARCHAR },
			{ "apelido", Types.VARCHAR },
			{ "observacao", Types.VARCHAR },
			{ "rg", Types.VARCHAR },
			{ "rgOrgaoEmissor", Types.VARCHAR },
			{ "rgDataEmissao", Types.TIMESTAMP },
			{ "cpf", Types.VARCHAR },
			{ "sexo", Types.VARCHAR },
			{ "estadoCivil", Types.VARCHAR },
			{ "dataNascimento", Types.TIMESTAMP },
			{ "endComLogradouro", Types.VARCHAR },
			{ "endComDescricao", Types.VARCHAR },
			{ "endComCep", Types.VARCHAR },
			{ "endComBairro", Types.VARCHAR },
			{ "endComCidade", Types.VARCHAR },
			{ "endComUf", Types.VARCHAR },
			{ "endComPais", Types.VARCHAR },
			{ "endResLogradouro", Types.VARCHAR },
			{ "endResDescricao", Types.VARCHAR },
			{ "endResCep", Types.VARCHAR },
			{ "endResBairro", Types.VARCHAR },
			{ "endResCidade", Types.VARCHAR },
			{ "endResUf", Types.VARCHAR },
			{ "endResPais", Types.VARCHAR },
			{ "telComDdd", Types.VARCHAR },
			{ "telComNumero", Types.VARCHAR },
			{ "telComRamal", Types.VARCHAR },
			{ "telResDdd", Types.VARCHAR },
			{ "telResNumero", Types.VARCHAR },
			{ "telCelDdd", Types.VARCHAR },
			{ "telCelNumero", Types.VARCHAR },
			{ "endEmail", Types.VARCHAR },
			{ "dataEntrada", Types.TIMESTAMP },
			{ "dataSaida", Types.TIMESTAMP },
			{ "existeUser", Types.BOOLEAN },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Funcionario (funcionarioId LONG not null primary key,companyId LONG,groupId LONG,createUserId LONG,modifiedUserId LONG,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,apelido VARCHAR(75) null,observacao VARCHAR(75) null,rg VARCHAR(75) null,rgOrgaoEmissor VARCHAR(75) null,rgDataEmissao DATE null,cpf VARCHAR(75) null,sexo VARCHAR(75) null,estadoCivil VARCHAR(75) null,dataNascimento DATE null,endComLogradouro VARCHAR(75) null,endComDescricao VARCHAR(75) null,endComCep VARCHAR(75) null,endComBairro VARCHAR(75) null,endComCidade VARCHAR(75) null,endComUf VARCHAR(75) null,endComPais VARCHAR(75) null,endResLogradouro VARCHAR(75) null,endResDescricao VARCHAR(75) null,endResCep VARCHAR(75) null,endResBairro VARCHAR(75) null,endResCidade VARCHAR(75) null,endResUf VARCHAR(75) null,endResPais VARCHAR(75) null,telComDdd VARCHAR(75) null,telComNumero VARCHAR(75) null,telComRamal VARCHAR(75) null,telResDdd VARCHAR(75) null,telResNumero VARCHAR(75) null,telCelDdd VARCHAR(75) null,telCelNumero VARCHAR(75) null,endEmail VARCHAR(75) null,dataEntrada DATE null,dataSaida DATE null,existeUser BOOLEAN,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Funcionario";
	public static final String ORDER_BY_JPQL = " ORDER BY funcionario.nome ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Funcionario.nome ASC";
	public static final String DATA_SOURCE = "appcomercialDataSource";
	public static final String SESSION_FACTORY = "appcomercialSessionFactory";
	public static final String TX_MANAGER = "appcomercialTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.appcomercial.servico.model.Funcionario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.appcomercial.servico.model.Funcionario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.appcomercial.servico.model.Funcionario"),
			true);
	public static long APELIDO_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long CPF_COLUMN_BITMASK = 4L;
	public static long DATANASCIMENTO_COLUMN_BITMASK = 8L;
	public static long GROUPID_COLUMN_BITMASK = 16L;
	public static long NOME_COLUMN_BITMASK = 32L;
	public static long RG_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Funcionario toModel(FuncionarioSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Funcionario model = new FuncionarioImpl();

		model.setFuncionarioId(soapModel.getFuncionarioId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateUserId(soapModel.getCreateUserId());
		model.setModifiedUserId(soapModel.getModifiedUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setNome(soapModel.getNome());
		model.setApelido(soapModel.getApelido());
		model.setObservacao(soapModel.getObservacao());
		model.setRg(soapModel.getRg());
		model.setRgOrgaoEmissor(soapModel.getRgOrgaoEmissor());
		model.setRgDataEmissao(soapModel.getRgDataEmissao());
		model.setCpf(soapModel.getCpf());
		model.setSexo(soapModel.getSexo());
		model.setEstadoCivil(soapModel.getEstadoCivil());
		model.setDataNascimento(soapModel.getDataNascimento());
		model.setEndComLogradouro(soapModel.getEndComLogradouro());
		model.setEndComDescricao(soapModel.getEndComDescricao());
		model.setEndComCep(soapModel.getEndComCep());
		model.setEndComBairro(soapModel.getEndComBairro());
		model.setEndComCidade(soapModel.getEndComCidade());
		model.setEndComUf(soapModel.getEndComUf());
		model.setEndComPais(soapModel.getEndComPais());
		model.setEndResLogradouro(soapModel.getEndResLogradouro());
		model.setEndResDescricao(soapModel.getEndResDescricao());
		model.setEndResCep(soapModel.getEndResCep());
		model.setEndResBairro(soapModel.getEndResBairro());
		model.setEndResCidade(soapModel.getEndResCidade());
		model.setEndResUf(soapModel.getEndResUf());
		model.setEndResPais(soapModel.getEndResPais());
		model.setTelComDdd(soapModel.getTelComDdd());
		model.setTelComNumero(soapModel.getTelComNumero());
		model.setTelComRamal(soapModel.getTelComRamal());
		model.setTelResDdd(soapModel.getTelResDdd());
		model.setTelResNumero(soapModel.getTelResNumero());
		model.setTelCelDdd(soapModel.getTelCelDdd());
		model.setTelCelNumero(soapModel.getTelCelNumero());
		model.setEndEmail(soapModel.getEndEmail());
		model.setDataEntrada(soapModel.getDataEntrada());
		model.setDataSaida(soapModel.getDataSaida());
		model.setExisteUser(soapModel.getExisteUser());
		model.setUserId(soapModel.getUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Funcionario> toModels(FuncionarioSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Funcionario> models = new ArrayList<Funcionario>(soapModels.length);

		for (FuncionarioSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.appcomercial.servico.model.Funcionario"));

	public FuncionarioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _funcionarioId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFuncionarioId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _funcionarioId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Funcionario.class;
	}

	@Override
	public String getModelClassName() {
		return Funcionario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("funcionarioId", getFuncionarioId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createUserId", getCreateUserId());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("nome", getNome());
		attributes.put("apelido", getApelido());
		attributes.put("observacao", getObservacao());
		attributes.put("rg", getRg());
		attributes.put("rgOrgaoEmissor", getRgOrgaoEmissor());
		attributes.put("rgDataEmissao", getRgDataEmissao());
		attributes.put("cpf", getCpf());
		attributes.put("sexo", getSexo());
		attributes.put("estadoCivil", getEstadoCivil());
		attributes.put("dataNascimento", getDataNascimento());
		attributes.put("endComLogradouro", getEndComLogradouro());
		attributes.put("endComDescricao", getEndComDescricao());
		attributes.put("endComCep", getEndComCep());
		attributes.put("endComBairro", getEndComBairro());
		attributes.put("endComCidade", getEndComCidade());
		attributes.put("endComUf", getEndComUf());
		attributes.put("endComPais", getEndComPais());
		attributes.put("endResLogradouro", getEndResLogradouro());
		attributes.put("endResDescricao", getEndResDescricao());
		attributes.put("endResCep", getEndResCep());
		attributes.put("endResBairro", getEndResBairro());
		attributes.put("endResCidade", getEndResCidade());
		attributes.put("endResUf", getEndResUf());
		attributes.put("endResPais", getEndResPais());
		attributes.put("telComDdd", getTelComDdd());
		attributes.put("telComNumero", getTelComNumero());
		attributes.put("telComRamal", getTelComRamal());
		attributes.put("telResDdd", getTelResDdd());
		attributes.put("telResNumero", getTelResNumero());
		attributes.put("telCelDdd", getTelCelDdd());
		attributes.put("telCelNumero", getTelCelNumero());
		attributes.put("endEmail", getEndEmail());
		attributes.put("dataEntrada", getDataEntrada());
		attributes.put("dataSaida", getDataSaida());
		attributes.put("existeUser", getExisteUser());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long funcionarioId = (Long)attributes.get("funcionarioId");

		if (funcionarioId != null) {
			setFuncionarioId(funcionarioId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long createUserId = (Long)attributes.get("createUserId");

		if (createUserId != null) {
			setCreateUserId(createUserId);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		String apelido = (String)attributes.get("apelido");

		if (apelido != null) {
			setApelido(apelido);
		}

		String observacao = (String)attributes.get("observacao");

		if (observacao != null) {
			setObservacao(observacao);
		}

		String rg = (String)attributes.get("rg");

		if (rg != null) {
			setRg(rg);
		}

		String rgOrgaoEmissor = (String)attributes.get("rgOrgaoEmissor");

		if (rgOrgaoEmissor != null) {
			setRgOrgaoEmissor(rgOrgaoEmissor);
		}

		Date rgDataEmissao = (Date)attributes.get("rgDataEmissao");

		if (rgDataEmissao != null) {
			setRgDataEmissao(rgDataEmissao);
		}

		String cpf = (String)attributes.get("cpf");

		if (cpf != null) {
			setCpf(cpf);
		}

		String sexo = (String)attributes.get("sexo");

		if (sexo != null) {
			setSexo(sexo);
		}

		String estadoCivil = (String)attributes.get("estadoCivil");

		if (estadoCivil != null) {
			setEstadoCivil(estadoCivil);
		}

		Date dataNascimento = (Date)attributes.get("dataNascimento");

		if (dataNascimento != null) {
			setDataNascimento(dataNascimento);
		}

		String endComLogradouro = (String)attributes.get("endComLogradouro");

		if (endComLogradouro != null) {
			setEndComLogradouro(endComLogradouro);
		}

		String endComDescricao = (String)attributes.get("endComDescricao");

		if (endComDescricao != null) {
			setEndComDescricao(endComDescricao);
		}

		String endComCep = (String)attributes.get("endComCep");

		if (endComCep != null) {
			setEndComCep(endComCep);
		}

		String endComBairro = (String)attributes.get("endComBairro");

		if (endComBairro != null) {
			setEndComBairro(endComBairro);
		}

		String endComCidade = (String)attributes.get("endComCidade");

		if (endComCidade != null) {
			setEndComCidade(endComCidade);
		}

		String endComUf = (String)attributes.get("endComUf");

		if (endComUf != null) {
			setEndComUf(endComUf);
		}

		String endComPais = (String)attributes.get("endComPais");

		if (endComPais != null) {
			setEndComPais(endComPais);
		}

		String endResLogradouro = (String)attributes.get("endResLogradouro");

		if (endResLogradouro != null) {
			setEndResLogradouro(endResLogradouro);
		}

		String endResDescricao = (String)attributes.get("endResDescricao");

		if (endResDescricao != null) {
			setEndResDescricao(endResDescricao);
		}

		String endResCep = (String)attributes.get("endResCep");

		if (endResCep != null) {
			setEndResCep(endResCep);
		}

		String endResBairro = (String)attributes.get("endResBairro");

		if (endResBairro != null) {
			setEndResBairro(endResBairro);
		}

		String endResCidade = (String)attributes.get("endResCidade");

		if (endResCidade != null) {
			setEndResCidade(endResCidade);
		}

		String endResUf = (String)attributes.get("endResUf");

		if (endResUf != null) {
			setEndResUf(endResUf);
		}

		String endResPais = (String)attributes.get("endResPais");

		if (endResPais != null) {
			setEndResPais(endResPais);
		}

		String telComDdd = (String)attributes.get("telComDdd");

		if (telComDdd != null) {
			setTelComDdd(telComDdd);
		}

		String telComNumero = (String)attributes.get("telComNumero");

		if (telComNumero != null) {
			setTelComNumero(telComNumero);
		}

		String telComRamal = (String)attributes.get("telComRamal");

		if (telComRamal != null) {
			setTelComRamal(telComRamal);
		}

		String telResDdd = (String)attributes.get("telResDdd");

		if (telResDdd != null) {
			setTelResDdd(telResDdd);
		}

		String telResNumero = (String)attributes.get("telResNumero");

		if (telResNumero != null) {
			setTelResNumero(telResNumero);
		}

		String telCelDdd = (String)attributes.get("telCelDdd");

		if (telCelDdd != null) {
			setTelCelDdd(telCelDdd);
		}

		String telCelNumero = (String)attributes.get("telCelNumero");

		if (telCelNumero != null) {
			setTelCelNumero(telCelNumero);
		}

		String endEmail = (String)attributes.get("endEmail");

		if (endEmail != null) {
			setEndEmail(endEmail);
		}

		Date dataEntrada = (Date)attributes.get("dataEntrada");

		if (dataEntrada != null) {
			setDataEntrada(dataEntrada);
		}

		Date dataSaida = (Date)attributes.get("dataSaida");

		if (dataSaida != null) {
			setDataSaida(dataSaida);
		}

		Boolean existeUser = (Boolean)attributes.get("existeUser");

		if (existeUser != null) {
			setExisteUser(existeUser);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@JSON
	@Override
	public long getFuncionarioId() {
		return _funcionarioId;
	}

	@Override
	public void setFuncionarioId(long funcionarioId) {
		_funcionarioId = funcionarioId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCreateUserId() {
		return _createUserId;
	}

	@Override
	public void setCreateUserId(long createUserId) {
		_createUserId = createUserId;
	}

	@Override
	public String getCreateUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreateUserId(), "uuid",
			_createUserUuid);
	}

	@Override
	public void setCreateUserUuid(String createUserUuid) {
		_createUserUuid = createUserUuid;
	}

	@JSON
	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_columnBitmask = -1L;

		if (_originalNome == null) {
			_originalNome = _nome;
		}

		_nome = nome;
	}

	public String getOriginalNome() {
		return GetterUtil.getString(_originalNome);
	}

	@JSON
	@Override
	public String getApelido() {
		if (_apelido == null) {
			return StringPool.BLANK;
		}
		else {
			return _apelido;
		}
	}

	@Override
	public void setApelido(String apelido) {
		_columnBitmask |= APELIDO_COLUMN_BITMASK;

		if (_originalApelido == null) {
			_originalApelido = _apelido;
		}

		_apelido = apelido;
	}

	public String getOriginalApelido() {
		return GetterUtil.getString(_originalApelido);
	}

	@JSON
	@Override
	public String getObservacao() {
		if (_observacao == null) {
			return StringPool.BLANK;
		}
		else {
			return _observacao;
		}
	}

	@Override
	public void setObservacao(String observacao) {
		_observacao = observacao;
	}

	@JSON
	@Override
	public String getRg() {
		if (_rg == null) {
			return StringPool.BLANK;
		}
		else {
			return _rg;
		}
	}

	@Override
	public void setRg(String rg) {
		_columnBitmask |= RG_COLUMN_BITMASK;

		if (_originalRg == null) {
			_originalRg = _rg;
		}

		_rg = rg;
	}

	public String getOriginalRg() {
		return GetterUtil.getString(_originalRg);
	}

	@JSON
	@Override
	public String getRgOrgaoEmissor() {
		if (_rgOrgaoEmissor == null) {
			return StringPool.BLANK;
		}
		else {
			return _rgOrgaoEmissor;
		}
	}

	@Override
	public void setRgOrgaoEmissor(String rgOrgaoEmissor) {
		_rgOrgaoEmissor = rgOrgaoEmissor;
	}

	@JSON
	@Override
	public Date getRgDataEmissao() {
		return _rgDataEmissao;
	}

	@Override
	public void setRgDataEmissao(Date rgDataEmissao) {
		_rgDataEmissao = rgDataEmissao;
	}

	@JSON
	@Override
	public String getCpf() {
		if (_cpf == null) {
			return StringPool.BLANK;
		}
		else {
			return _cpf;
		}
	}

	@Override
	public void setCpf(String cpf) {
		_columnBitmask |= CPF_COLUMN_BITMASK;

		if (_originalCpf == null) {
			_originalCpf = _cpf;
		}

		_cpf = cpf;
	}

	public String getOriginalCpf() {
		return GetterUtil.getString(_originalCpf);
	}

	@JSON
	@Override
	public String getSexo() {
		if (_sexo == null) {
			return StringPool.BLANK;
		}
		else {
			return _sexo;
		}
	}

	@Override
	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	@JSON
	@Override
	public String getEstadoCivil() {
		if (_estadoCivil == null) {
			return StringPool.BLANK;
		}
		else {
			return _estadoCivil;
		}
	}

	@Override
	public void setEstadoCivil(String estadoCivil) {
		_estadoCivil = estadoCivil;
	}

	@JSON
	@Override
	public Date getDataNascimento() {
		return _dataNascimento;
	}

	@Override
	public void setDataNascimento(Date dataNascimento) {
		_columnBitmask |= DATANASCIMENTO_COLUMN_BITMASK;

		if (_originalDataNascimento == null) {
			_originalDataNascimento = _dataNascimento;
		}

		_dataNascimento = dataNascimento;
	}

	public Date getOriginalDataNascimento() {
		return _originalDataNascimento;
	}

	@JSON
	@Override
	public String getEndComLogradouro() {
		if (_endComLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComLogradouro;
		}
	}

	@Override
	public void setEndComLogradouro(String endComLogradouro) {
		_endComLogradouro = endComLogradouro;
	}

	@JSON
	@Override
	public String getEndComDescricao() {
		if (_endComDescricao == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComDescricao;
		}
	}

	@Override
	public void setEndComDescricao(String endComDescricao) {
		_endComDescricao = endComDescricao;
	}

	@JSON
	@Override
	public String getEndComCep() {
		if (_endComCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComCep;
		}
	}

	@Override
	public void setEndComCep(String endComCep) {
		_endComCep = endComCep;
	}

	@JSON
	@Override
	public String getEndComBairro() {
		if (_endComBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComBairro;
		}
	}

	@Override
	public void setEndComBairro(String endComBairro) {
		_endComBairro = endComBairro;
	}

	@JSON
	@Override
	public String getEndComCidade() {
		if (_endComCidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComCidade;
		}
	}

	@Override
	public void setEndComCidade(String endComCidade) {
		_endComCidade = endComCidade;
	}

	@JSON
	@Override
	public String getEndComUf() {
		if (_endComUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComUf;
		}
	}

	@Override
	public void setEndComUf(String endComUf) {
		_endComUf = endComUf;
	}

	@JSON
	@Override
	public String getEndComPais() {
		if (_endComPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endComPais;
		}
	}

	@Override
	public void setEndComPais(String endComPais) {
		_endComPais = endComPais;
	}

	@JSON
	@Override
	public String getEndResLogradouro() {
		if (_endResLogradouro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResLogradouro;
		}
	}

	@Override
	public void setEndResLogradouro(String endResLogradouro) {
		_endResLogradouro = endResLogradouro;
	}

	@JSON
	@Override
	public String getEndResDescricao() {
		if (_endResDescricao == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResDescricao;
		}
	}

	@Override
	public void setEndResDescricao(String endResDescricao) {
		_endResDescricao = endResDescricao;
	}

	@JSON
	@Override
	public String getEndResCep() {
		if (_endResCep == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResCep;
		}
	}

	@Override
	public void setEndResCep(String endResCep) {
		_endResCep = endResCep;
	}

	@JSON
	@Override
	public String getEndResBairro() {
		if (_endResBairro == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResBairro;
		}
	}

	@Override
	public void setEndResBairro(String endResBairro) {
		_endResBairro = endResBairro;
	}

	@JSON
	@Override
	public String getEndResCidade() {
		if (_endResCidade == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResCidade;
		}
	}

	@Override
	public void setEndResCidade(String endResCidade) {
		_endResCidade = endResCidade;
	}

	@JSON
	@Override
	public String getEndResUf() {
		if (_endResUf == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResUf;
		}
	}

	@Override
	public void setEndResUf(String endResUf) {
		_endResUf = endResUf;
	}

	@JSON
	@Override
	public String getEndResPais() {
		if (_endResPais == null) {
			return StringPool.BLANK;
		}
		else {
			return _endResPais;
		}
	}

	@Override
	public void setEndResPais(String endResPais) {
		_endResPais = endResPais;
	}

	@JSON
	@Override
	public String getTelComDdd() {
		if (_telComDdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _telComDdd;
		}
	}

	@Override
	public void setTelComDdd(String telComDdd) {
		_telComDdd = telComDdd;
	}

	@JSON
	@Override
	public String getTelComNumero() {
		if (_telComNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _telComNumero;
		}
	}

	@Override
	public void setTelComNumero(String telComNumero) {
		_telComNumero = telComNumero;
	}

	@JSON
	@Override
	public String getTelComRamal() {
		if (_telComRamal == null) {
			return StringPool.BLANK;
		}
		else {
			return _telComRamal;
		}
	}

	@Override
	public void setTelComRamal(String telComRamal) {
		_telComRamal = telComRamal;
	}

	@JSON
	@Override
	public String getTelResDdd() {
		if (_telResDdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _telResDdd;
		}
	}

	@Override
	public void setTelResDdd(String telResDdd) {
		_telResDdd = telResDdd;
	}

	@JSON
	@Override
	public String getTelResNumero() {
		if (_telResNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _telResNumero;
		}
	}

	@Override
	public void setTelResNumero(String telResNumero) {
		_telResNumero = telResNumero;
	}

	@JSON
	@Override
	public String getTelCelDdd() {
		if (_telCelDdd == null) {
			return StringPool.BLANK;
		}
		else {
			return _telCelDdd;
		}
	}

	@Override
	public void setTelCelDdd(String telCelDdd) {
		_telCelDdd = telCelDdd;
	}

	@JSON
	@Override
	public String getTelCelNumero() {
		if (_telCelNumero == null) {
			return StringPool.BLANK;
		}
		else {
			return _telCelNumero;
		}
	}

	@Override
	public void setTelCelNumero(String telCelNumero) {
		_telCelNumero = telCelNumero;
	}

	@JSON
	@Override
	public String getEndEmail() {
		if (_endEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _endEmail;
		}
	}

	@Override
	public void setEndEmail(String endEmail) {
		_endEmail = endEmail;
	}

	@JSON
	@Override
	public Date getDataEntrada() {
		return _dataEntrada;
	}

	@Override
	public void setDataEntrada(Date dataEntrada) {
		_dataEntrada = dataEntrada;
	}

	@JSON
	@Override
	public Date getDataSaida() {
		return _dataSaida;
	}

	@Override
	public void setDataSaida(Date dataSaida) {
		_dataSaida = dataSaida;
	}

	@JSON
	@Override
	public Boolean getExisteUser() {
		return _existeUser;
	}

	@Override
	public void setExisteUser(Boolean existeUser) {
		_existeUser = existeUser;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Funcionario.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Funcionario toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Funcionario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FuncionarioImpl funcionarioImpl = new FuncionarioImpl();

		funcionarioImpl.setFuncionarioId(getFuncionarioId());
		funcionarioImpl.setCompanyId(getCompanyId());
		funcionarioImpl.setGroupId(getGroupId());
		funcionarioImpl.setCreateUserId(getCreateUserId());
		funcionarioImpl.setModifiedUserId(getModifiedUserId());
		funcionarioImpl.setCreateDate(getCreateDate());
		funcionarioImpl.setModifiedDate(getModifiedDate());
		funcionarioImpl.setNome(getNome());
		funcionarioImpl.setApelido(getApelido());
		funcionarioImpl.setObservacao(getObservacao());
		funcionarioImpl.setRg(getRg());
		funcionarioImpl.setRgOrgaoEmissor(getRgOrgaoEmissor());
		funcionarioImpl.setRgDataEmissao(getRgDataEmissao());
		funcionarioImpl.setCpf(getCpf());
		funcionarioImpl.setSexo(getSexo());
		funcionarioImpl.setEstadoCivil(getEstadoCivil());
		funcionarioImpl.setDataNascimento(getDataNascimento());
		funcionarioImpl.setEndComLogradouro(getEndComLogradouro());
		funcionarioImpl.setEndComDescricao(getEndComDescricao());
		funcionarioImpl.setEndComCep(getEndComCep());
		funcionarioImpl.setEndComBairro(getEndComBairro());
		funcionarioImpl.setEndComCidade(getEndComCidade());
		funcionarioImpl.setEndComUf(getEndComUf());
		funcionarioImpl.setEndComPais(getEndComPais());
		funcionarioImpl.setEndResLogradouro(getEndResLogradouro());
		funcionarioImpl.setEndResDescricao(getEndResDescricao());
		funcionarioImpl.setEndResCep(getEndResCep());
		funcionarioImpl.setEndResBairro(getEndResBairro());
		funcionarioImpl.setEndResCidade(getEndResCidade());
		funcionarioImpl.setEndResUf(getEndResUf());
		funcionarioImpl.setEndResPais(getEndResPais());
		funcionarioImpl.setTelComDdd(getTelComDdd());
		funcionarioImpl.setTelComNumero(getTelComNumero());
		funcionarioImpl.setTelComRamal(getTelComRamal());
		funcionarioImpl.setTelResDdd(getTelResDdd());
		funcionarioImpl.setTelResNumero(getTelResNumero());
		funcionarioImpl.setTelCelDdd(getTelCelDdd());
		funcionarioImpl.setTelCelNumero(getTelCelNumero());
		funcionarioImpl.setEndEmail(getEndEmail());
		funcionarioImpl.setDataEntrada(getDataEntrada());
		funcionarioImpl.setDataSaida(getDataSaida());
		funcionarioImpl.setExisteUser(getExisteUser());
		funcionarioImpl.setUserId(getUserId());

		funcionarioImpl.resetOriginalValues();

		return funcionarioImpl;
	}

	@Override
	public int compareTo(Funcionario funcionario) {
		int value = 0;

		value = getNome().compareTo(funcionario.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Funcionario)) {
			return false;
		}

		Funcionario funcionario = (Funcionario)obj;

		long primaryKey = funcionario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FuncionarioModelImpl funcionarioModelImpl = this;

		funcionarioModelImpl._originalCompanyId = funcionarioModelImpl._companyId;

		funcionarioModelImpl._setOriginalCompanyId = false;

		funcionarioModelImpl._originalGroupId = funcionarioModelImpl._groupId;

		funcionarioModelImpl._setOriginalGroupId = false;

		funcionarioModelImpl._originalNome = funcionarioModelImpl._nome;

		funcionarioModelImpl._originalApelido = funcionarioModelImpl._apelido;

		funcionarioModelImpl._originalRg = funcionarioModelImpl._rg;

		funcionarioModelImpl._originalCpf = funcionarioModelImpl._cpf;

		funcionarioModelImpl._originalDataNascimento = funcionarioModelImpl._dataNascimento;

		funcionarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Funcionario> toCacheModel() {
		FuncionarioCacheModel funcionarioCacheModel = new FuncionarioCacheModel();

		funcionarioCacheModel.funcionarioId = getFuncionarioId();

		funcionarioCacheModel.companyId = getCompanyId();

		funcionarioCacheModel.groupId = getGroupId();

		funcionarioCacheModel.createUserId = getCreateUserId();

		funcionarioCacheModel.modifiedUserId = getModifiedUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			funcionarioCacheModel.createDate = createDate.getTime();
		}
		else {
			funcionarioCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			funcionarioCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			funcionarioCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		funcionarioCacheModel.nome = getNome();

		String nome = funcionarioCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			funcionarioCacheModel.nome = null;
		}

		funcionarioCacheModel.apelido = getApelido();

		String apelido = funcionarioCacheModel.apelido;

		if ((apelido != null) && (apelido.length() == 0)) {
			funcionarioCacheModel.apelido = null;
		}

		funcionarioCacheModel.observacao = getObservacao();

		String observacao = funcionarioCacheModel.observacao;

		if ((observacao != null) && (observacao.length() == 0)) {
			funcionarioCacheModel.observacao = null;
		}

		funcionarioCacheModel.rg = getRg();

		String rg = funcionarioCacheModel.rg;

		if ((rg != null) && (rg.length() == 0)) {
			funcionarioCacheModel.rg = null;
		}

		funcionarioCacheModel.rgOrgaoEmissor = getRgOrgaoEmissor();

		String rgOrgaoEmissor = funcionarioCacheModel.rgOrgaoEmissor;

		if ((rgOrgaoEmissor != null) && (rgOrgaoEmissor.length() == 0)) {
			funcionarioCacheModel.rgOrgaoEmissor = null;
		}

		Date rgDataEmissao = getRgDataEmissao();

		if (rgDataEmissao != null) {
			funcionarioCacheModel.rgDataEmissao = rgDataEmissao.getTime();
		}
		else {
			funcionarioCacheModel.rgDataEmissao = Long.MIN_VALUE;
		}

		funcionarioCacheModel.cpf = getCpf();

		String cpf = funcionarioCacheModel.cpf;

		if ((cpf != null) && (cpf.length() == 0)) {
			funcionarioCacheModel.cpf = null;
		}

		funcionarioCacheModel.sexo = getSexo();

		String sexo = funcionarioCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			funcionarioCacheModel.sexo = null;
		}

		funcionarioCacheModel.estadoCivil = getEstadoCivil();

		String estadoCivil = funcionarioCacheModel.estadoCivil;

		if ((estadoCivil != null) && (estadoCivil.length() == 0)) {
			funcionarioCacheModel.estadoCivil = null;
		}

		Date dataNascimento = getDataNascimento();

		if (dataNascimento != null) {
			funcionarioCacheModel.dataNascimento = dataNascimento.getTime();
		}
		else {
			funcionarioCacheModel.dataNascimento = Long.MIN_VALUE;
		}

		funcionarioCacheModel.endComLogradouro = getEndComLogradouro();

		String endComLogradouro = funcionarioCacheModel.endComLogradouro;

		if ((endComLogradouro != null) && (endComLogradouro.length() == 0)) {
			funcionarioCacheModel.endComLogradouro = null;
		}

		funcionarioCacheModel.endComDescricao = getEndComDescricao();

		String endComDescricao = funcionarioCacheModel.endComDescricao;

		if ((endComDescricao != null) && (endComDescricao.length() == 0)) {
			funcionarioCacheModel.endComDescricao = null;
		}

		funcionarioCacheModel.endComCep = getEndComCep();

		String endComCep = funcionarioCacheModel.endComCep;

		if ((endComCep != null) && (endComCep.length() == 0)) {
			funcionarioCacheModel.endComCep = null;
		}

		funcionarioCacheModel.endComBairro = getEndComBairro();

		String endComBairro = funcionarioCacheModel.endComBairro;

		if ((endComBairro != null) && (endComBairro.length() == 0)) {
			funcionarioCacheModel.endComBairro = null;
		}

		funcionarioCacheModel.endComCidade = getEndComCidade();

		String endComCidade = funcionarioCacheModel.endComCidade;

		if ((endComCidade != null) && (endComCidade.length() == 0)) {
			funcionarioCacheModel.endComCidade = null;
		}

		funcionarioCacheModel.endComUf = getEndComUf();

		String endComUf = funcionarioCacheModel.endComUf;

		if ((endComUf != null) && (endComUf.length() == 0)) {
			funcionarioCacheModel.endComUf = null;
		}

		funcionarioCacheModel.endComPais = getEndComPais();

		String endComPais = funcionarioCacheModel.endComPais;

		if ((endComPais != null) && (endComPais.length() == 0)) {
			funcionarioCacheModel.endComPais = null;
		}

		funcionarioCacheModel.endResLogradouro = getEndResLogradouro();

		String endResLogradouro = funcionarioCacheModel.endResLogradouro;

		if ((endResLogradouro != null) && (endResLogradouro.length() == 0)) {
			funcionarioCacheModel.endResLogradouro = null;
		}

		funcionarioCacheModel.endResDescricao = getEndResDescricao();

		String endResDescricao = funcionarioCacheModel.endResDescricao;

		if ((endResDescricao != null) && (endResDescricao.length() == 0)) {
			funcionarioCacheModel.endResDescricao = null;
		}

		funcionarioCacheModel.endResCep = getEndResCep();

		String endResCep = funcionarioCacheModel.endResCep;

		if ((endResCep != null) && (endResCep.length() == 0)) {
			funcionarioCacheModel.endResCep = null;
		}

		funcionarioCacheModel.endResBairro = getEndResBairro();

		String endResBairro = funcionarioCacheModel.endResBairro;

		if ((endResBairro != null) && (endResBairro.length() == 0)) {
			funcionarioCacheModel.endResBairro = null;
		}

		funcionarioCacheModel.endResCidade = getEndResCidade();

		String endResCidade = funcionarioCacheModel.endResCidade;

		if ((endResCidade != null) && (endResCidade.length() == 0)) {
			funcionarioCacheModel.endResCidade = null;
		}

		funcionarioCacheModel.endResUf = getEndResUf();

		String endResUf = funcionarioCacheModel.endResUf;

		if ((endResUf != null) && (endResUf.length() == 0)) {
			funcionarioCacheModel.endResUf = null;
		}

		funcionarioCacheModel.endResPais = getEndResPais();

		String endResPais = funcionarioCacheModel.endResPais;

		if ((endResPais != null) && (endResPais.length() == 0)) {
			funcionarioCacheModel.endResPais = null;
		}

		funcionarioCacheModel.telComDdd = getTelComDdd();

		String telComDdd = funcionarioCacheModel.telComDdd;

		if ((telComDdd != null) && (telComDdd.length() == 0)) {
			funcionarioCacheModel.telComDdd = null;
		}

		funcionarioCacheModel.telComNumero = getTelComNumero();

		String telComNumero = funcionarioCacheModel.telComNumero;

		if ((telComNumero != null) && (telComNumero.length() == 0)) {
			funcionarioCacheModel.telComNumero = null;
		}

		funcionarioCacheModel.telComRamal = getTelComRamal();

		String telComRamal = funcionarioCacheModel.telComRamal;

		if ((telComRamal != null) && (telComRamal.length() == 0)) {
			funcionarioCacheModel.telComRamal = null;
		}

		funcionarioCacheModel.telResDdd = getTelResDdd();

		String telResDdd = funcionarioCacheModel.telResDdd;

		if ((telResDdd != null) && (telResDdd.length() == 0)) {
			funcionarioCacheModel.telResDdd = null;
		}

		funcionarioCacheModel.telResNumero = getTelResNumero();

		String telResNumero = funcionarioCacheModel.telResNumero;

		if ((telResNumero != null) && (telResNumero.length() == 0)) {
			funcionarioCacheModel.telResNumero = null;
		}

		funcionarioCacheModel.telCelDdd = getTelCelDdd();

		String telCelDdd = funcionarioCacheModel.telCelDdd;

		if ((telCelDdd != null) && (telCelDdd.length() == 0)) {
			funcionarioCacheModel.telCelDdd = null;
		}

		funcionarioCacheModel.telCelNumero = getTelCelNumero();

		String telCelNumero = funcionarioCacheModel.telCelNumero;

		if ((telCelNumero != null) && (telCelNumero.length() == 0)) {
			funcionarioCacheModel.telCelNumero = null;
		}

		funcionarioCacheModel.endEmail = getEndEmail();

		String endEmail = funcionarioCacheModel.endEmail;

		if ((endEmail != null) && (endEmail.length() == 0)) {
			funcionarioCacheModel.endEmail = null;
		}

		Date dataEntrada = getDataEntrada();

		if (dataEntrada != null) {
			funcionarioCacheModel.dataEntrada = dataEntrada.getTime();
		}
		else {
			funcionarioCacheModel.dataEntrada = Long.MIN_VALUE;
		}

		Date dataSaida = getDataSaida();

		if (dataSaida != null) {
			funcionarioCacheModel.dataSaida = dataSaida.getTime();
		}
		else {
			funcionarioCacheModel.dataSaida = Long.MIN_VALUE;
		}

		funcionarioCacheModel.existeUser = getExisteUser();

		funcionarioCacheModel.userId = getUserId();

		return funcionarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(87);

		sb.append("{funcionarioId=");
		sb.append(getFuncionarioId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createUserId=");
		sb.append(getCreateUserId());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", apelido=");
		sb.append(getApelido());
		sb.append(", observacao=");
		sb.append(getObservacao());
		sb.append(", rg=");
		sb.append(getRg());
		sb.append(", rgOrgaoEmissor=");
		sb.append(getRgOrgaoEmissor());
		sb.append(", rgDataEmissao=");
		sb.append(getRgDataEmissao());
		sb.append(", cpf=");
		sb.append(getCpf());
		sb.append(", sexo=");
		sb.append(getSexo());
		sb.append(", estadoCivil=");
		sb.append(getEstadoCivil());
		sb.append(", dataNascimento=");
		sb.append(getDataNascimento());
		sb.append(", endComLogradouro=");
		sb.append(getEndComLogradouro());
		sb.append(", endComDescricao=");
		sb.append(getEndComDescricao());
		sb.append(", endComCep=");
		sb.append(getEndComCep());
		sb.append(", endComBairro=");
		sb.append(getEndComBairro());
		sb.append(", endComCidade=");
		sb.append(getEndComCidade());
		sb.append(", endComUf=");
		sb.append(getEndComUf());
		sb.append(", endComPais=");
		sb.append(getEndComPais());
		sb.append(", endResLogradouro=");
		sb.append(getEndResLogradouro());
		sb.append(", endResDescricao=");
		sb.append(getEndResDescricao());
		sb.append(", endResCep=");
		sb.append(getEndResCep());
		sb.append(", endResBairro=");
		sb.append(getEndResBairro());
		sb.append(", endResCidade=");
		sb.append(getEndResCidade());
		sb.append(", endResUf=");
		sb.append(getEndResUf());
		sb.append(", endResPais=");
		sb.append(getEndResPais());
		sb.append(", telComDdd=");
		sb.append(getTelComDdd());
		sb.append(", telComNumero=");
		sb.append(getTelComNumero());
		sb.append(", telComRamal=");
		sb.append(getTelComRamal());
		sb.append(", telResDdd=");
		sb.append(getTelResDdd());
		sb.append(", telResNumero=");
		sb.append(getTelResNumero());
		sb.append(", telCelDdd=");
		sb.append(getTelCelDdd());
		sb.append(", telCelNumero=");
		sb.append(getTelCelNumero());
		sb.append(", endEmail=");
		sb.append(getEndEmail());
		sb.append(", dataEntrada=");
		sb.append(getDataEntrada());
		sb.append(", dataSaida=");
		sb.append(getDataSaida());
		sb.append(", existeUser=");
		sb.append(getExisteUser());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(133);

		sb.append("<model><model-name>");
		sb.append(
			"br.com.prodevelopment.appcomercial.servico.model.Funcionario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>funcionarioId</column-name><column-value><![CDATA[");
		sb.append(getFuncionarioId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createUserId</column-name><column-value><![CDATA[");
		sb.append(getCreateUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apelido</column-name><column-value><![CDATA[");
		sb.append(getApelido());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>observacao</column-name><column-value><![CDATA[");
		sb.append(getObservacao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rg</column-name><column-value><![CDATA[");
		sb.append(getRg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgOrgaoEmissor</column-name><column-value><![CDATA[");
		sb.append(getRgOrgaoEmissor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rgDataEmissao</column-name><column-value><![CDATA[");
		sb.append(getRgDataEmissao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cpf</column-name><column-value><![CDATA[");
		sb.append(getCpf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexo</column-name><column-value><![CDATA[");
		sb.append(getSexo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estadoCivil</column-name><column-value><![CDATA[");
		sb.append(getEstadoCivil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataNascimento</column-name><column-value><![CDATA[");
		sb.append(getDataNascimento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndComLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComDescricao</column-name><column-value><![CDATA[");
		sb.append(getEndComDescricao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCep</column-name><column-value><![CDATA[");
		sb.append(getEndComCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComBairro</column-name><column-value><![CDATA[");
		sb.append(getEndComBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComCidade</column-name><column-value><![CDATA[");
		sb.append(getEndComCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComUf</column-name><column-value><![CDATA[");
		sb.append(getEndComUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endComPais</column-name><column-value><![CDATA[");
		sb.append(getEndComPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResLogradouro</column-name><column-value><![CDATA[");
		sb.append(getEndResLogradouro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResDescricao</column-name><column-value><![CDATA[");
		sb.append(getEndResDescricao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCep</column-name><column-value><![CDATA[");
		sb.append(getEndResCep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResBairro</column-name><column-value><![CDATA[");
		sb.append(getEndResBairro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResCidade</column-name><column-value><![CDATA[");
		sb.append(getEndResCidade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResUf</column-name><column-value><![CDATA[");
		sb.append(getEndResUf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endResPais</column-name><column-value><![CDATA[");
		sb.append(getEndResPais());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telComDdd</column-name><column-value><![CDATA[");
		sb.append(getTelComDdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telComNumero</column-name><column-value><![CDATA[");
		sb.append(getTelComNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telComRamal</column-name><column-value><![CDATA[");
		sb.append(getTelComRamal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telResDdd</column-name><column-value><![CDATA[");
		sb.append(getTelResDdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telResNumero</column-name><column-value><![CDATA[");
		sb.append(getTelResNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telCelDdd</column-name><column-value><![CDATA[");
		sb.append(getTelCelDdd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>telCelNumero</column-name><column-value><![CDATA[");
		sb.append(getTelCelNumero());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endEmail</column-name><column-value><![CDATA[");
		sb.append(getEndEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataEntrada</column-name><column-value><![CDATA[");
		sb.append(getDataEntrada());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataSaida</column-name><column-value><![CDATA[");
		sb.append(getDataSaida());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>existeUser</column-name><column-value><![CDATA[");
		sb.append(getExisteUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Funcionario.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Funcionario.class
		};
	private long _funcionarioId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _createUserId;
	private String _createUserUuid;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _nome;
	private String _originalNome;
	private String _apelido;
	private String _originalApelido;
	private String _observacao;
	private String _rg;
	private String _originalRg;
	private String _rgOrgaoEmissor;
	private Date _rgDataEmissao;
	private String _cpf;
	private String _originalCpf;
	private String _sexo;
	private String _estadoCivil;
	private Date _dataNascimento;
	private Date _originalDataNascimento;
	private String _endComLogradouro;
	private String _endComDescricao;
	private String _endComCep;
	private String _endComBairro;
	private String _endComCidade;
	private String _endComUf;
	private String _endComPais;
	private String _endResLogradouro;
	private String _endResDescricao;
	private String _endResCep;
	private String _endResBairro;
	private String _endResCidade;
	private String _endResUf;
	private String _endResPais;
	private String _telComDdd;
	private String _telComNumero;
	private String _telComRamal;
	private String _telResDdd;
	private String _telResNumero;
	private String _telCelDdd;
	private String _telCelNumero;
	private String _endEmail;
	private Date _dataEntrada;
	private Date _dataSaida;
	private Boolean _existeUser;
	private long _userId;
	private String _userUuid;
	private long _columnBitmask;
	private Funcionario _escapedModel;
}