/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ClienteLimCredito service. Represents a row in the &quot;ClienteLimCredito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.cliente.model.impl.ClienteLimCreditoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.cliente.model.impl.ClienteLimCreditoImpl}.
 * </p>
 *
 * @author marcelo
 * @see ClienteLimCredito
 * @see br.com.prodevelopment.cliente.model.impl.ClienteLimCreditoImpl
 * @see br.com.prodevelopment.cliente.model.impl.ClienteLimCreditoModelImpl
 * @generated
 */
public interface ClienteLimCreditoModel extends BaseModel<ClienteLimCredito> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cliente lim credito model instance should use the {@link ClienteLimCredito} interface instead.
	 */

	/**
	 * Returns the primary key of this cliente lim credito.
	 *
	 * @return the primary key of this cliente lim credito
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cliente lim credito.
	 *
	 * @param primaryKey the primary key of this cliente lim credito
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cliente lim credito ID of this cliente lim credito.
	 *
	 * @return the cliente lim credito ID of this cliente lim credito
	 */
	public long getClienteLimCreditoId();

	/**
	 * Sets the cliente lim credito ID of this cliente lim credito.
	 *
	 * @param clienteLimCreditoId the cliente lim credito ID of this cliente lim credito
	 */
	public void setClienteLimCreditoId(long clienteLimCreditoId);

	/**
	 * Returns the valor limite maximo credito of this cliente lim credito.
	 *
	 * @return the valor limite maximo credito of this cliente lim credito
	 */
	public double getValorLimiteMaximoCredito();

	/**
	 * Sets the valor limite maximo credito of this cliente lim credito.
	 *
	 * @param valorLimiteMaximoCredito the valor limite maximo credito of this cliente lim credito
	 */
	public void setValorLimiteMaximoCredito(double valorLimiteMaximoCredito);

	/**
	 * Returns the data limite maximo credito of this cliente lim credito.
	 *
	 * @return the data limite maximo credito of this cliente lim credito
	 */
	public Date getDataLimiteMaximoCredito();

	/**
	 * Sets the data limite maximo credito of this cliente lim credito.
	 *
	 * @param dataLimiteMaximoCredito the data limite maximo credito of this cliente lim credito
	 */
	public void setDataLimiteMaximoCredito(Date dataLimiteMaximoCredito);

	/**
	 * Returns the valor limite maximo cheque of this cliente lim credito.
	 *
	 * @return the valor limite maximo cheque of this cliente lim credito
	 */
	public double getValorLimiteMaximoCheque();

	/**
	 * Sets the valor limite maximo cheque of this cliente lim credito.
	 *
	 * @param valorLimiteMaximoCheque the valor limite maximo cheque of this cliente lim credito
	 */
	public void setValorLimiteMaximoCheque(double valorLimiteMaximoCheque);

	/**
	 * Returns the qtde limite maximo cheque of this cliente lim credito.
	 *
	 * @return the qtde limite maximo cheque of this cliente lim credito
	 */
	public int getQtdeLimiteMaximoCheque();

	/**
	 * Sets the qtde limite maximo cheque of this cliente lim credito.
	 *
	 * @param qtdeLimiteMaximoCheque the qtde limite maximo cheque of this cliente lim credito
	 */
	public void setQtdeLimiteMaximoCheque(int qtdeLimiteMaximoCheque);

	/**
	 * Returns the cliente ID of this cliente lim credito.
	 *
	 * @return the cliente ID of this cliente lim credito
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this cliente lim credito.
	 *
	 * @param clienteId the cliente ID of this cliente lim credito
	 */
	public void setClienteId(long clienteId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ClienteLimCredito clienteLimCredito);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ClienteLimCredito> toCacheModel();

	@Override
	public ClienteLimCredito toEscapedModel();

	@Override
	public ClienteLimCredito toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}