/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Cliente service. Represents a row in the &quot;Cliente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.cliente.model.impl.ClienteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.cliente.model.impl.ClienteImpl}.
 * </p>
 *
 * @author marcelo
 * @see Cliente
 * @see br.com.prodevelopment.cliente.model.impl.ClienteImpl
 * @see br.com.prodevelopment.cliente.model.impl.ClienteModelImpl
 * @generated
 */
public interface ClienteModel extends BaseModel<Cliente>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cliente model instance should use the {@link Cliente} interface instead.
	 */

	/**
	 * Returns the primary key of this cliente.
	 *
	 * @return the primary key of this cliente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cliente.
	 *
	 * @param primaryKey the primary key of this cliente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cliente.
	 *
	 * @return the uuid of this cliente
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this cliente.
	 *
	 * @param uuid the uuid of this cliente
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cliente ID of this cliente.
	 *
	 * @return the cliente ID of this cliente
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this cliente.
	 *
	 * @param clienteId the cliente ID of this cliente
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the company ID of this cliente.
	 *
	 * @return the company ID of this cliente
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cliente.
	 *
	 * @param companyId the company ID of this cliente
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this cliente.
	 *
	 * @return the group ID of this cliente
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cliente.
	 *
	 * @param groupId the group ID of this cliente
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this cliente.
	 *
	 * @return the create user ID of this cliente
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this cliente.
	 *
	 * @param createUserId the create user ID of this cliente
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this cliente.
	 *
	 * @return the create user uuid of this cliente
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this cliente.
	 *
	 * @param createUserUuid the create user uuid of this cliente
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this cliente.
	 *
	 * @return the modified user ID of this cliente
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this cliente.
	 *
	 * @param modifiedUserId the modified user ID of this cliente
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this cliente.
	 *
	 * @return the modified user uuid of this cliente
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this cliente.
	 *
	 * @param modifiedUserUuid the modified user uuid of this cliente
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this cliente.
	 *
	 * @return the create date of this cliente
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cliente.
	 *
	 * @param createDate the create date of this cliente
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cliente.
	 *
	 * @return the modified date of this cliente
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cliente.
	 *
	 * @param modifiedDate the modified date of this cliente
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this cliente.
	 *
	 * @return the nome of this cliente
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this cliente.
	 *
	 * @param nome the nome of this cliente
	 */
	public void setNome(String nome);

	/**
	 * Returns the rg inscricao mun of this cliente.
	 *
	 * @return the rg inscricao mun of this cliente
	 */
	@AutoEscape
	public String getRgInscricaoMun();

	/**
	 * Sets the rg inscricao mun of this cliente.
	 *
	 * @param rgInscricaoMun the rg inscricao mun of this cliente
	 */
	public void setRgInscricaoMun(String rgInscricaoMun);

	/**
	 * Returns the rg orgao emissor of this cliente.
	 *
	 * @return the rg orgao emissor of this cliente
	 */
	@AutoEscape
	public String getRgOrgaoEmissor();

	/**
	 * Sets the rg orgao emissor of this cliente.
	 *
	 * @param rgOrgaoEmissor the rg orgao emissor of this cliente
	 */
	public void setRgOrgaoEmissor(String rgOrgaoEmissor);

	/**
	 * Returns the rg data emissao of this cliente.
	 *
	 * @return the rg data emissao of this cliente
	 */
	public Date getRgDataEmissao();

	/**
	 * Sets the rg data emissao of this cliente.
	 *
	 * @param rgDataEmissao the rg data emissao of this cliente
	 */
	public void setRgDataEmissao(Date rgDataEmissao);

	/**
	 * Returns the tipo pessoa of this cliente.
	 *
	 * @return the tipo pessoa of this cliente
	 */
	@AutoEscape
	public String getTipoPessoa();

	/**
	 * Sets the tipo pessoa of this cliente.
	 *
	 * @param tipoPessoa the tipo pessoa of this cliente
	 */
	public void setTipoPessoa(String tipoPessoa);

	/**
	 * Returns the cpf cnpj of this cliente.
	 *
	 * @return the cpf cnpj of this cliente
	 */
	@AutoEscape
	public String getCpfCnpj();

	/**
	 * Sets the cpf cnpj of this cliente.
	 *
	 * @param cpfCnpj the cpf cnpj of this cliente
	 */
	public void setCpfCnpj(String cpfCnpj);

	/**
	 * Returns the sexo of this cliente.
	 *
	 * @return the sexo of this cliente
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this cliente.
	 *
	 * @param sexo the sexo of this cliente
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the estado civil of this cliente.
	 *
	 * @return the estado civil of this cliente
	 */
	@AutoEscape
	public String getEstadoCivil();

	/**
	 * Sets the estado civil of this cliente.
	 *
	 * @param estadoCivil the estado civil of this cliente
	 */
	public void setEstadoCivil(String estadoCivil);

	/**
	 * Returns the data nascimento of this cliente.
	 *
	 * @return the data nascimento of this cliente
	 */
	public Date getDataNascimento();

	/**
	 * Sets the data nascimento of this cliente.
	 *
	 * @param dataNascimento the data nascimento of this cliente
	 */
	public void setDataNascimento(Date dataNascimento);

	/**
	 * Returns the end com logradouro of this cliente.
	 *
	 * @return the end com logradouro of this cliente
	 */
	@AutoEscape
	public String getEndComLogradouro();

	/**
	 * Sets the end com logradouro of this cliente.
	 *
	 * @param endComLogradouro the end com logradouro of this cliente
	 */
	public void setEndComLogradouro(String endComLogradouro);

	/**
	 * Returns the end com numero of this cliente.
	 *
	 * @return the end com numero of this cliente
	 */
	@AutoEscape
	public String getEndComNumero();

	/**
	 * Sets the end com numero of this cliente.
	 *
	 * @param endComNumero the end com numero of this cliente
	 */
	public void setEndComNumero(String endComNumero);

	/**
	 * Returns the end com complemento of this cliente.
	 *
	 * @return the end com complemento of this cliente
	 */
	@AutoEscape
	public String getEndComComplemento();

	/**
	 * Sets the end com complemento of this cliente.
	 *
	 * @param endComComplemento the end com complemento of this cliente
	 */
	public void setEndComComplemento(String endComComplemento);

	/**
	 * Returns the end com cep of this cliente.
	 *
	 * @return the end com cep of this cliente
	 */
	@AutoEscape
	public String getEndComCep();

	/**
	 * Sets the end com cep of this cliente.
	 *
	 * @param endComCep the end com cep of this cliente
	 */
	public void setEndComCep(String endComCep);

	/**
	 * Returns the end com bairro of this cliente.
	 *
	 * @return the end com bairro of this cliente
	 */
	@AutoEscape
	public String getEndComBairro();

	/**
	 * Sets the end com bairro of this cliente.
	 *
	 * @param endComBairro the end com bairro of this cliente
	 */
	public void setEndComBairro(String endComBairro);

	/**
	 * Returns the end com cidade of this cliente.
	 *
	 * @return the end com cidade of this cliente
	 */
	public long getEndComCidade();

	/**
	 * Sets the end com cidade of this cliente.
	 *
	 * @param endComCidade the end com cidade of this cliente
	 */
	public void setEndComCidade(long endComCidade);

	/**
	 * Returns the end com uf of this cliente.
	 *
	 * @return the end com uf of this cliente
	 */
	@AutoEscape
	public String getEndComUf();

	/**
	 * Sets the end com uf of this cliente.
	 *
	 * @param endComUf the end com uf of this cliente
	 */
	public void setEndComUf(String endComUf);

	/**
	 * Returns the end com pais of this cliente.
	 *
	 * @return the end com pais of this cliente
	 */
	@AutoEscape
	public String getEndComPais();

	/**
	 * Sets the end com pais of this cliente.
	 *
	 * @param endComPais the end com pais of this cliente
	 */
	public void setEndComPais(String endComPais);

	/**
	 * Returns the end res logradouro of this cliente.
	 *
	 * @return the end res logradouro of this cliente
	 */
	@AutoEscape
	public String getEndResLogradouro();

	/**
	 * Sets the end res logradouro of this cliente.
	 *
	 * @param endResLogradouro the end res logradouro of this cliente
	 */
	public void setEndResLogradouro(String endResLogradouro);

	/**
	 * Returns the end res numero of this cliente.
	 *
	 * @return the end res numero of this cliente
	 */
	@AutoEscape
	public String getEndResNumero();

	/**
	 * Sets the end res numero of this cliente.
	 *
	 * @param endResNumero the end res numero of this cliente
	 */
	public void setEndResNumero(String endResNumero);

	/**
	 * Returns the end res complemento of this cliente.
	 *
	 * @return the end res complemento of this cliente
	 */
	@AutoEscape
	public String getEndResComplemento();

	/**
	 * Sets the end res complemento of this cliente.
	 *
	 * @param endResComplemento the end res complemento of this cliente
	 */
	public void setEndResComplemento(String endResComplemento);

	/**
	 * Returns the end res cep of this cliente.
	 *
	 * @return the end res cep of this cliente
	 */
	@AutoEscape
	public String getEndResCep();

	/**
	 * Sets the end res cep of this cliente.
	 *
	 * @param endResCep the end res cep of this cliente
	 */
	public void setEndResCep(String endResCep);

	/**
	 * Returns the end res bairro of this cliente.
	 *
	 * @return the end res bairro of this cliente
	 */
	@AutoEscape
	public String getEndResBairro();

	/**
	 * Sets the end res bairro of this cliente.
	 *
	 * @param endResBairro the end res bairro of this cliente
	 */
	public void setEndResBairro(String endResBairro);

	/**
	 * Returns the end res cidade of this cliente.
	 *
	 * @return the end res cidade of this cliente
	 */
	public long getEndResCidade();

	/**
	 * Sets the end res cidade of this cliente.
	 *
	 * @param endResCidade the end res cidade of this cliente
	 */
	public void setEndResCidade(long endResCidade);

	/**
	 * Returns the end res uf of this cliente.
	 *
	 * @return the end res uf of this cliente
	 */
	@AutoEscape
	public String getEndResUf();

	/**
	 * Sets the end res uf of this cliente.
	 *
	 * @param endResUf the end res uf of this cliente
	 */
	public void setEndResUf(String endResUf);

	/**
	 * Returns the end res pais of this cliente.
	 *
	 * @return the end res pais of this cliente
	 */
	@AutoEscape
	public String getEndResPais();

	/**
	 * Sets the end res pais of this cliente.
	 *
	 * @param endResPais the end res pais of this cliente
	 */
	public void setEndResPais(String endResPais);

	/**
	 * Returns the tel com ddd of this cliente.
	 *
	 * @return the tel com ddd of this cliente
	 */
	@AutoEscape
	public String getTelComDdd();

	/**
	 * Sets the tel com ddd of this cliente.
	 *
	 * @param telComDdd the tel com ddd of this cliente
	 */
	public void setTelComDdd(String telComDdd);

	/**
	 * Returns the versao of this cliente.
	 *
	 * @return the versao of this cliente
	 */
	public double getVersao();

	/**
	 * Sets the versao of this cliente.
	 *
	 * @param versao the versao of this cliente
	 */
	public void setVersao(double versao);

	/**
	 * Returns the logo tipo ID of this cliente.
	 *
	 * @return the logo tipo ID of this cliente
	 */
	public long getLogoTipoId();

	/**
	 * Sets the logo tipo ID of this cliente.
	 *
	 * @param logoTipoId the logo tipo ID of this cliente
	 */
	public void setLogoTipoId(long logoTipoId);

	/**
	 * Returns the observacao of this cliente.
	 *
	 * @return the observacao of this cliente
	 */
	@AutoEscape
	public String getObservacao();

	/**
	 * Sets the observacao of this cliente.
	 *
	 * @param observacao the observacao of this cliente
	 */
	public void setObservacao(String observacao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Cliente cliente);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Cliente> toCacheModel();

	@Override
	public Cliente toEscapedModel();

	@Override
	public Cliente toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}