/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.etask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TypeTaskUsers service. Represents a row in the &quot;etsk_TypeTaskUsers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.etask.model.impl.TypeTaskUsersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.etask.model.impl.TypeTaskUsersImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see TypeTaskUsers
 * @see br.com.prodevelopment.etask.model.impl.TypeTaskUsersImpl
 * @see br.com.prodevelopment.etask.model.impl.TypeTaskUsersModelImpl
 * @generated
 */
public interface TypeTaskUsersModel extends BaseModel<TypeTaskUsers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a type task users model instance should use the {@link TypeTaskUsers} interface instead.
	 */

	/**
	 * Returns the primary key of this type task users.
	 *
	 * @return the primary key of this type task users
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this type task users.
	 *
	 * @param primaryKey the primary key of this type task users
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type task users ID of this type task users.
	 *
	 * @return the type task users ID of this type task users
	 */
	public long getTypeTaskUsersId();

	/**
	 * Sets the type task users ID of this type task users.
	 *
	 * @param typeTaskUsersId the type task users ID of this type task users
	 */
	public void setTypeTaskUsersId(long typeTaskUsersId);

	/**
	 * Returns the user ID create of this type task users.
	 *
	 * @return the user ID create of this type task users
	 */
	public long getUserIdCreate();

	/**
	 * Sets the user ID create of this type task users.
	 *
	 * @param userIdCreate the user ID create of this type task users
	 */
	public void setUserIdCreate(long userIdCreate);

	/**
	 * Returns the create date of this type task users.
	 *
	 * @return the create date of this type task users
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this type task users.
	 *
	 * @param createDate the create date of this type task users
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the type task ID of this type task users.
	 *
	 * @return the type task ID of this type task users
	 */
	public long getTypeTaskId();

	/**
	 * Sets the type task ID of this type task users.
	 *
	 * @param typeTaskId the type task ID of this type task users
	 */
	public void setTypeTaskId(long typeTaskId);

	/**
	 * Returns the user ID of this type task users.
	 *
	 * @return the user ID of this type task users
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this type task users.
	 *
	 * @param userId the user ID of this type task users
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this type task users.
	 *
	 * @return the user uuid of this type task users
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this type task users.
	 *
	 * @param userUuid the user uuid of this type task users
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the type user of this type task users.
	 *
	 * @return the type user of this type task users
	 */
	@AutoEscape
	public String getTypeUser();

	/**
	 * Sets the type user of this type task users.
	 *
	 * @param typeUser the type user of this type task users
	 */
	public void setTypeUser(String typeUser);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.prodevelopment.etask.model.TypeTaskUsers typeTaskUsers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.etask.model.TypeTaskUsers> toCacheModel();

	@Override
	public br.com.prodevelopment.etask.model.TypeTaskUsers toEscapedModel();

	@Override
	public br.com.prodevelopment.etask.model.TypeTaskUsers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}