/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.academiahorario.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the AcademiaHorario service. Represents a row in the &quot;AcademiaHorario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.academiahorario.model.impl.AcademiaHorarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.academiahorario.model.impl.AcademiaHorarioImpl}.
 * </p>
 *
 * @author Marcelo
 * @see AcademiaHorario
 * @see br.com.prodevelopment.academiahorario.model.impl.AcademiaHorarioImpl
 * @see br.com.prodevelopment.academiahorario.model.impl.AcademiaHorarioModelImpl
 * @generated
 */
public interface AcademiaHorarioModel extends BaseModel<AcademiaHorario>,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a academia horario model instance should use the {@link AcademiaHorario} interface instead.
	 */

	/**
	 * Returns the primary key of this academia horario.
	 *
	 * @return the primary key of this academia horario
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this academia horario.
	 *
	 * @param primaryKey the primary key of this academia horario
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this academia horario.
	 *
	 * @return the uuid of this academia horario
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this academia horario.
	 *
	 * @param uuid the uuid of this academia horario
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the academia horario ID of this academia horario.
	 *
	 * @return the academia horario ID of this academia horario
	 */
	public long getAcademiaHorarioId();

	/**
	 * Sets the academia horario ID of this academia horario.
	 *
	 * @param academiaHorarioId the academia horario ID of this academia horario
	 */
	public void setAcademiaHorarioId(long academiaHorarioId);

	/**
	 * Returns the company ID of this academia horario.
	 *
	 * @return the company ID of this academia horario
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this academia horario.
	 *
	 * @param companyId the company ID of this academia horario
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this academia horario.
	 *
	 * @return the group ID of this academia horario
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this academia horario.
	 *
	 * @param groupId the group ID of this academia horario
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this academia horario.
	 *
	 * @return the create user ID of this academia horario
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this academia horario.
	 *
	 * @param createUserId the create user ID of this academia horario
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this academia horario.
	 *
	 * @return the create user uuid of this academia horario
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this academia horario.
	 *
	 * @param createUserUuid the create user uuid of this academia horario
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this academia horario.
	 *
	 * @return the modified user ID of this academia horario
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this academia horario.
	 *
	 * @param modifiedUserId the modified user ID of this academia horario
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this academia horario.
	 *
	 * @return the modified user uuid of this academia horario
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this academia horario.
	 *
	 * @param modifiedUserUuid the modified user uuid of this academia horario
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this academia horario.
	 *
	 * @return the create date of this academia horario
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this academia horario.
	 *
	 * @param createDate the create date of this academia horario
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this academia horario.
	 *
	 * @return the modified date of this academia horario
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this academia horario.
	 *
	 * @param modifiedDate the modified date of this academia horario
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dia semana of this academia horario.
	 *
	 * @return the dia semana of this academia horario
	 */
	public int getDiaSemana();

	/**
	 * Sets the dia semana of this academia horario.
	 *
	 * @param diaSemana the dia semana of this academia horario
	 */
	public void setDiaSemana(int diaSemana);

	/**
	 * Returns the hora inicial of this academia horario.
	 *
	 * @return the hora inicial of this academia horario
	 */
	@AutoEscape
	public String getHoraInicial();

	/**
	 * Sets the hora inicial of this academia horario.
	 *
	 * @param horaInicial the hora inicial of this academia horario
	 */
	public void setHoraInicial(String horaInicial);

	/**
	 * Returns the hora final of this academia horario.
	 *
	 * @return the hora final of this academia horario
	 */
	@AutoEscape
	public String getHoraFinal();

	/**
	 * Sets the hora final of this academia horario.
	 *
	 * @param HoraFinal the hora final of this academia horario
	 */
	public void setHoraFinal(String HoraFinal);

	/**
	 * Returns the atividade ID of this academia horario.
	 *
	 * @return the atividade ID of this academia horario
	 */
	public long getAtividadeId();

	/**
	 * Sets the atividade ID of this academia horario.
	 *
	 * @param atividadeId the atividade ID of this academia horario
	 */
	public void setAtividadeId(long atividadeId);

	/**
	 * Returns the atividade nome of this academia horario.
	 *
	 * @return the atividade nome of this academia horario
	 */
	public String getAtividadeNome();

	/**
	 * Returns the localized atividade nome of this academia horario in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized atividade nome of this academia horario
	 */
	@AutoEscape
	public String getAtividadeNome(Locale locale);

	/**
	 * Returns the localized atividade nome of this academia horario in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized atividade nome of this academia horario. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getAtividadeNome(Locale locale, boolean useDefault);

	/**
	 * Returns the localized atividade nome of this academia horario in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized atividade nome of this academia horario
	 */
	@AutoEscape
	public String getAtividadeNome(String languageId);

	/**
	 * Returns the localized atividade nome of this academia horario in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized atividade nome of this academia horario
	 */
	@AutoEscape
	public String getAtividadeNome(String languageId, boolean useDefault);

	@AutoEscape
	public String getAtividadeNomeCurrentLanguageId();

	@AutoEscape
	public String getAtividadeNomeCurrentValue();

	/**
	 * Returns a map of the locales and localized atividade nomes of this academia horario.
	 *
	 * @return the locales and localized atividade nomes of this academia horario
	 */
	public Map<Locale, String> getAtividadeNomeMap();

	/**
	 * Sets the atividade nome of this academia horario.
	 *
	 * @param atividadeNome the atividade nome of this academia horario
	 */
	public void setAtividadeNome(String atividadeNome);

	/**
	 * Sets the localized atividade nome of this academia horario in the language.
	 *
	 * @param atividadeNome the localized atividade nome of this academia horario
	 * @param locale the locale of the language
	 */
	public void setAtividadeNome(String atividadeNome, Locale locale);

	/**
	 * Sets the localized atividade nome of this academia horario in the language, and sets the default locale.
	 *
	 * @param atividadeNome the localized atividade nome of this academia horario
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setAtividadeNome(String atividadeNome, Locale locale,
		Locale defaultLocale);

	public void setAtividadeNomeCurrentLanguageId(String languageId);

	/**
	 * Sets the localized atividade nomes of this academia horario from the map of locales and localized atividade nomes.
	 *
	 * @param atividadeNomeMap the locales and localized atividade nomes of this academia horario
	 */
	public void setAtividadeNomeMap(Map<Locale, String> atividadeNomeMap);

	/**
	 * Sets the localized atividade nomes of this academia horario from the map of locales and localized atividade nomes, and sets the default locale.
	 *
	 * @param atividadeNomeMap the locales and localized atividade nomes of this academia horario
	 * @param defaultLocale the default locale
	 */
	public void setAtividadeNomeMap(Map<Locale, String> atividadeNomeMap,
		Locale defaultLocale);

	/**
	 * Returns the versao of this academia horario.
	 *
	 * @return the versao of this academia horario
	 */
	public double getVersao();

	/**
	 * Sets the versao of this academia horario.
	 *
	 * @param versao the versao of this academia horario
	 */
	public void setVersao(double versao);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(AcademiaHorario academiaHorario);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AcademiaHorario> toCacheModel();

	@Override
	public AcademiaHorario toEscapedModel();

	@Override
	public AcademiaHorario toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}