/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.contato.model.impl;

import br.com.prodevelopment.contato.model.EnderecoEmail;
import br.com.prodevelopment.contato.model.EnderecoEmailModel;
import br.com.prodevelopment.contato.model.EnderecoEmailSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EnderecoEmail service. Represents a row in the &quot;EnderecoEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.contato.model.EnderecoEmailModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnderecoEmailImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see EnderecoEmailImpl
 * @see br.com.prodevelopment.contato.model.EnderecoEmail
 * @see br.com.prodevelopment.contato.model.EnderecoEmailModel
 * @generated
 */
@JSON(strict = true)
public class EnderecoEmailModelImpl extends BaseModelImpl<EnderecoEmail>
	implements EnderecoEmailModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a endereco email model instance should use the {@link br.com.prodevelopment.contato.model.EnderecoEmail} interface instead.
	 */
	public static final String TABLE_NAME = "EnderecoEmail";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "enderecoEmailId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createUserId", Types.BIGINT },
			{ "modifiedUserId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "endereco", Types.VARCHAR },
			{ "tipo", Types.INTEGER },
			{ "principal", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table EnderecoEmail (uuid_ VARCHAR(75) null,enderecoEmailId LONG not null primary key,companyId LONG,groupId LONG,createUserId LONG,modifiedUserId LONG,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,endereco VARCHAR(200) null,tipo INTEGER,principal BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table EnderecoEmail";
	public static final String ORDER_BY_JPQL = " ORDER BY enderecoEmail.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EnderecoEmail.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.contato.model.EnderecoEmail"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.contato.model.EnderecoEmail"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.contato.model.EnderecoEmail"),
			true);
	public static long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static long CLASSPK_COLUMN_BITMASK = 2L;
	public static long COMPANYID_COLUMN_BITMASK = 4L;
	public static long GROUPID_COLUMN_BITMASK = 8L;
	public static long PRINCIPAL_COLUMN_BITMASK = 16L;
	public static long UUID_COLUMN_BITMASK = 32L;
	public static long CREATEDATE_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EnderecoEmail toModel(EnderecoEmailSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EnderecoEmail model = new EnderecoEmailImpl();

		model.setUuid(soapModel.getUuid());
		model.setEnderecoEmailId(soapModel.getEnderecoEmailId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setCreateUserId(soapModel.getCreateUserId());
		model.setModifiedUserId(soapModel.getModifiedUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setEndereco(soapModel.getEndereco());
		model.setTipo(soapModel.getTipo());
		model.setPrincipal(soapModel.getPrincipal());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EnderecoEmail> toModels(EnderecoEmailSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EnderecoEmail> models = new ArrayList<EnderecoEmail>(soapModels.length);

		for (EnderecoEmailSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.contato.model.EnderecoEmail"));

	public EnderecoEmailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _enderecoEmailId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEnderecoEmailId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _enderecoEmailId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EnderecoEmail.class;
	}

	@Override
	public String getModelClassName() {
		return EnderecoEmail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("enderecoEmailId", getEnderecoEmailId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createUserId", getCreateUserId());
		attributes.put("modifiedUserId", getModifiedUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("endereco", getEndereco());
		attributes.put("tipo", getTipo());
		attributes.put("principal", getPrincipal());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long enderecoEmailId = (Long)attributes.get("enderecoEmailId");

		if (enderecoEmailId != null) {
			setEnderecoEmailId(enderecoEmailId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long createUserId = (Long)attributes.get("createUserId");

		if (createUserId != null) {
			setCreateUserId(createUserId);
		}

		Long modifiedUserId = (Long)attributes.get("modifiedUserId");

		if (modifiedUserId != null) {
			setModifiedUserId(modifiedUserId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		String endereco = (String)attributes.get("endereco");

		if (endereco != null) {
			setEndereco(endereco);
		}

		Integer tipo = (Integer)attributes.get("tipo");

		if (tipo != null) {
			setTipo(tipo);
		}

		Boolean principal = (Boolean)attributes.get("principal");

		if (principal != null) {
			setPrincipal(principal);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEnderecoEmailId() {
		return _enderecoEmailId;
	}

	@Override
	public void setEnderecoEmailId(long enderecoEmailId) {
		_enderecoEmailId = enderecoEmailId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCreateUserId() {
		return _createUserId;
	}

	@Override
	public void setCreateUserId(long createUserId) {
		_createUserId = createUserId;
	}

	@Override
	public String getCreateUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getCreateUserId(), "uuid",
			_createUserUuid);
	}

	@Override
	public void setCreateUserUuid(String createUserUuid) {
		_createUserUuid = createUserUuid;
	}

	@JSON
	@Override
	public long getModifiedUserId() {
		return _modifiedUserId;
	}

	@Override
	public void setModifiedUserId(long modifiedUserId) {
		_modifiedUserId = modifiedUserId;
	}

	@Override
	public String getModifiedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getModifiedUserId(), "uuid",
			_modifiedUserUuid);
	}

	@Override
	public void setModifiedUserUuid(String modifiedUserUuid) {
		_modifiedUserUuid = modifiedUserUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return StringPool.BLANK;
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@JSON
	@Override
	public String getEndereco() {
		if (_endereco == null) {
			return StringPool.BLANK;
		}
		else {
			return _endereco;
		}
	}

	@Override
	public void setEndereco(String endereco) {
		_endereco = endereco;
	}

	@JSON
	@Override
	public int getTipo() {
		return _tipo;
	}

	@Override
	public void setTipo(int tipo) {
		_tipo = tipo;
	}

	@JSON
	@Override
	public boolean getPrincipal() {
		return _principal;
	}

	@Override
	public boolean isPrincipal() {
		return _principal;
	}

	@Override
	public void setPrincipal(boolean principal) {
		_columnBitmask |= PRINCIPAL_COLUMN_BITMASK;

		if (!_setOriginalPrincipal) {
			_setOriginalPrincipal = true;

			_originalPrincipal = _principal;
		}

		_principal = principal;
	}

	public boolean getOriginalPrincipal() {
		return _originalPrincipal;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				EnderecoEmail.class.getName()), getClassNameId());
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EnderecoEmail.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EnderecoEmail toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EnderecoEmail)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EnderecoEmailImpl enderecoEmailImpl = new EnderecoEmailImpl();

		enderecoEmailImpl.setUuid(getUuid());
		enderecoEmailImpl.setEnderecoEmailId(getEnderecoEmailId());
		enderecoEmailImpl.setCompanyId(getCompanyId());
		enderecoEmailImpl.setGroupId(getGroupId());
		enderecoEmailImpl.setCreateUserId(getCreateUserId());
		enderecoEmailImpl.setModifiedUserId(getModifiedUserId());
		enderecoEmailImpl.setCreateDate(getCreateDate());
		enderecoEmailImpl.setModifiedDate(getModifiedDate());
		enderecoEmailImpl.setClassNameId(getClassNameId());
		enderecoEmailImpl.setClassPK(getClassPK());
		enderecoEmailImpl.setEndereco(getEndereco());
		enderecoEmailImpl.setTipo(getTipo());
		enderecoEmailImpl.setPrincipal(getPrincipal());

		enderecoEmailImpl.resetOriginalValues();

		return enderecoEmailImpl;
	}

	@Override
	public int compareTo(EnderecoEmail enderecoEmail) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				enderecoEmail.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EnderecoEmail)) {
			return false;
		}

		EnderecoEmail enderecoEmail = (EnderecoEmail)obj;

		long primaryKey = enderecoEmail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EnderecoEmailModelImpl enderecoEmailModelImpl = this;

		enderecoEmailModelImpl._originalUuid = enderecoEmailModelImpl._uuid;

		enderecoEmailModelImpl._originalCompanyId = enderecoEmailModelImpl._companyId;

		enderecoEmailModelImpl._setOriginalCompanyId = false;

		enderecoEmailModelImpl._originalGroupId = enderecoEmailModelImpl._groupId;

		enderecoEmailModelImpl._setOriginalGroupId = false;

		enderecoEmailModelImpl._originalClassNameId = enderecoEmailModelImpl._classNameId;

		enderecoEmailModelImpl._setOriginalClassNameId = false;

		enderecoEmailModelImpl._originalClassPK = enderecoEmailModelImpl._classPK;

		enderecoEmailModelImpl._setOriginalClassPK = false;

		enderecoEmailModelImpl._originalPrincipal = enderecoEmailModelImpl._principal;

		enderecoEmailModelImpl._setOriginalPrincipal = false;

		enderecoEmailModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EnderecoEmail> toCacheModel() {
		EnderecoEmailCacheModel enderecoEmailCacheModel = new EnderecoEmailCacheModel();

		enderecoEmailCacheModel.uuid = getUuid();

		String uuid = enderecoEmailCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			enderecoEmailCacheModel.uuid = null;
		}

		enderecoEmailCacheModel.enderecoEmailId = getEnderecoEmailId();

		enderecoEmailCacheModel.companyId = getCompanyId();

		enderecoEmailCacheModel.groupId = getGroupId();

		enderecoEmailCacheModel.createUserId = getCreateUserId();

		enderecoEmailCacheModel.modifiedUserId = getModifiedUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			enderecoEmailCacheModel.createDate = createDate.getTime();
		}
		else {
			enderecoEmailCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			enderecoEmailCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			enderecoEmailCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		enderecoEmailCacheModel.classNameId = getClassNameId();

		enderecoEmailCacheModel.classPK = getClassPK();

		enderecoEmailCacheModel.endereco = getEndereco();

		String endereco = enderecoEmailCacheModel.endereco;

		if ((endereco != null) && (endereco.length() == 0)) {
			enderecoEmailCacheModel.endereco = null;
		}

		enderecoEmailCacheModel.tipo = getTipo();

		enderecoEmailCacheModel.principal = getPrincipal();

		return enderecoEmailCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", enderecoEmailId=");
		sb.append(getEnderecoEmailId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createUserId=");
		sb.append(getCreateUserId());
		sb.append(", modifiedUserId=");
		sb.append(getModifiedUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", endereco=");
		sb.append(getEndereco());
		sb.append(", tipo=");
		sb.append(getTipo());
		sb.append(", principal=");
		sb.append(getPrincipal());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.contato.model.EnderecoEmail");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enderecoEmailId</column-name><column-value><![CDATA[");
		sb.append(getEnderecoEmailId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createUserId</column-name><column-value><![CDATA[");
		sb.append(getCreateUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedUserId</column-name><column-value><![CDATA[");
		sb.append(getModifiedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endereco</column-name><column-value><![CDATA[");
		sb.append(getEndereco());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipo</column-name><column-value><![CDATA[");
		sb.append(getTipo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>principal</column-name><column-value><![CDATA[");
		sb.append(getPrincipal());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EnderecoEmail.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EnderecoEmail.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _enderecoEmailId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _createUserId;
	private String _createUserUuid;
	private long _modifiedUserId;
	private String _modifiedUserUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _endereco;
	private int _tipo;
	private boolean _principal;
	private boolean _originalPrincipal;
	private boolean _setOriginalPrincipal;
	private long _columnBitmask;
	private EnderecoEmail _escapedModel;
}