/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.contato.model.impl;

import br.com.prodevelopment.contato.model.EnderecoEmail;
import br.com.prodevelopment.contato.service.EnderecoEmailLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EnderecoEmail service. Represents a row in the &quot;EnderecoEmail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnderecoEmailImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see EnderecoEmailImpl
 * @see br.com.prodevelopment.contato.model.EnderecoEmail
 * @generated
 */
public abstract class EnderecoEmailBaseImpl extends EnderecoEmailModelImpl
	implements EnderecoEmail {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a endereco email model instance should use the {@link EnderecoEmail} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EnderecoEmailLocalServiceUtil.addEnderecoEmail(this);
		}
		else {
			EnderecoEmailLocalServiceUtil.updateEnderecoEmail(this);
		}
	}
}