/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.contato.model.impl;

import br.com.prodevelopment.contato.model.Endereco;
import br.com.prodevelopment.contato.service.EnderecoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Endereco service. Represents a row in the &quot;Endereco&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnderecoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see EnderecoImpl
 * @see br.com.prodevelopment.contato.model.Endereco
 * @generated
 */
public abstract class EnderecoBaseImpl extends EnderecoModelImpl
	implements Endereco {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a endereco model instance should use the {@link Endereco} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EnderecoLocalServiceUtil.addEndereco(this);
		}
		else {
			EnderecoLocalServiceUtil.updateEndereco(this);
		}
	}
}