/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.cliente.service.base;

import br.com.prodevelopment.cliente.model.ClienteLimCredito;
import br.com.prodevelopment.cliente.service.ClienteLimCreditoService;
import br.com.prodevelopment.cliente.service.persistence.ClienteLimCreditoPersistence;
import br.com.prodevelopment.cliente.service.persistence.ClientePersistence;
import br.com.prodevelopment.cliente.service.persistence.ClienteUsuarioPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the cliente lim credito remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link br.com.prodevelopment.cliente.service.impl.ClienteLimCreditoServiceImpl}.
 * </p>
 *
 * @author marcelo
 * @see br.com.prodevelopment.cliente.service.impl.ClienteLimCreditoServiceImpl
 * @see br.com.prodevelopment.cliente.service.ClienteLimCreditoServiceUtil
 * @generated
 */
public abstract class ClienteLimCreditoServiceBaseImpl extends BaseServiceImpl
	implements ClienteLimCreditoService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link br.com.prodevelopment.cliente.service.ClienteLimCreditoServiceUtil} to access the cliente lim credito remote service.
	 */

	/**
	 * Returns the cliente local service.
	 *
	 * @return the cliente local service
	 */
	public br.com.prodevelopment.cliente.service.ClienteLocalService getClienteLocalService() {
		return clienteLocalService;
	}

	/**
	 * Sets the cliente local service.
	 *
	 * @param clienteLocalService the cliente local service
	 */
	public void setClienteLocalService(
		br.com.prodevelopment.cliente.service.ClienteLocalService clienteLocalService) {
		this.clienteLocalService = clienteLocalService;
	}

	/**
	 * Returns the cliente remote service.
	 *
	 * @return the cliente remote service
	 */
	public br.com.prodevelopment.cliente.service.ClienteService getClienteService() {
		return clienteService;
	}

	/**
	 * Sets the cliente remote service.
	 *
	 * @param clienteService the cliente remote service
	 */
	public void setClienteService(
		br.com.prodevelopment.cliente.service.ClienteService clienteService) {
		this.clienteService = clienteService;
	}

	/**
	 * Returns the cliente persistence.
	 *
	 * @return the cliente persistence
	 */
	public ClientePersistence getClientePersistence() {
		return clientePersistence;
	}

	/**
	 * Sets the cliente persistence.
	 *
	 * @param clientePersistence the cliente persistence
	 */
	public void setClientePersistence(ClientePersistence clientePersistence) {
		this.clientePersistence = clientePersistence;
	}

	/**
	 * Returns the cliente lim credito local service.
	 *
	 * @return the cliente lim credito local service
	 */
	public br.com.prodevelopment.cliente.service.ClienteLimCreditoLocalService getClienteLimCreditoLocalService() {
		return clienteLimCreditoLocalService;
	}

	/**
	 * Sets the cliente lim credito local service.
	 *
	 * @param clienteLimCreditoLocalService the cliente lim credito local service
	 */
	public void setClienteLimCreditoLocalService(
		br.com.prodevelopment.cliente.service.ClienteLimCreditoLocalService clienteLimCreditoLocalService) {
		this.clienteLimCreditoLocalService = clienteLimCreditoLocalService;
	}

	/**
	 * Returns the cliente lim credito remote service.
	 *
	 * @return the cliente lim credito remote service
	 */
	public br.com.prodevelopment.cliente.service.ClienteLimCreditoService getClienteLimCreditoService() {
		return clienteLimCreditoService;
	}

	/**
	 * Sets the cliente lim credito remote service.
	 *
	 * @param clienteLimCreditoService the cliente lim credito remote service
	 */
	public void setClienteLimCreditoService(
		br.com.prodevelopment.cliente.service.ClienteLimCreditoService clienteLimCreditoService) {
		this.clienteLimCreditoService = clienteLimCreditoService;
	}

	/**
	 * Returns the cliente lim credito persistence.
	 *
	 * @return the cliente lim credito persistence
	 */
	public ClienteLimCreditoPersistence getClienteLimCreditoPersistence() {
		return clienteLimCreditoPersistence;
	}

	/**
	 * Sets the cliente lim credito persistence.
	 *
	 * @param clienteLimCreditoPersistence the cliente lim credito persistence
	 */
	public void setClienteLimCreditoPersistence(
		ClienteLimCreditoPersistence clienteLimCreditoPersistence) {
		this.clienteLimCreditoPersistence = clienteLimCreditoPersistence;
	}

	/**
	 * Returns the cliente usuario local service.
	 *
	 * @return the cliente usuario local service
	 */
	public br.com.prodevelopment.cliente.service.ClienteUsuarioLocalService getClienteUsuarioLocalService() {
		return clienteUsuarioLocalService;
	}

	/**
	 * Sets the cliente usuario local service.
	 *
	 * @param clienteUsuarioLocalService the cliente usuario local service
	 */
	public void setClienteUsuarioLocalService(
		br.com.prodevelopment.cliente.service.ClienteUsuarioLocalService clienteUsuarioLocalService) {
		this.clienteUsuarioLocalService = clienteUsuarioLocalService;
	}

	/**
	 * Returns the cliente usuario remote service.
	 *
	 * @return the cliente usuario remote service
	 */
	public br.com.prodevelopment.cliente.service.ClienteUsuarioService getClienteUsuarioService() {
		return clienteUsuarioService;
	}

	/**
	 * Sets the cliente usuario remote service.
	 *
	 * @param clienteUsuarioService the cliente usuario remote service
	 */
	public void setClienteUsuarioService(
		br.com.prodevelopment.cliente.service.ClienteUsuarioService clienteUsuarioService) {
		this.clienteUsuarioService = clienteUsuarioService;
	}

	/**
	 * Returns the cliente usuario persistence.
	 *
	 * @return the cliente usuario persistence
	 */
	public ClienteUsuarioPersistence getClienteUsuarioPersistence() {
		return clienteUsuarioPersistence;
	}

	/**
	 * Sets the cliente usuario persistence.
	 *
	 * @param clienteUsuarioPersistence the cliente usuario persistence
	 */
	public void setClienteUsuarioPersistence(
		ClienteUsuarioPersistence clienteUsuarioPersistence) {
		this.clienteUsuarioPersistence = clienteUsuarioPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ClienteLimCredito.class;
	}

	protected String getModelClassName() {
		return ClienteLimCredito.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = clienteLimCreditoPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteLocalService.class)
	protected br.com.prodevelopment.cliente.service.ClienteLocalService clienteLocalService;
	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteService.class)
	protected br.com.prodevelopment.cliente.service.ClienteService clienteService;
	@BeanReference(type = ClientePersistence.class)
	protected ClientePersistence clientePersistence;
	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteLimCreditoLocalService.class)
	protected br.com.prodevelopment.cliente.service.ClienteLimCreditoLocalService clienteLimCreditoLocalService;
	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteLimCreditoService.class)
	protected br.com.prodevelopment.cliente.service.ClienteLimCreditoService clienteLimCreditoService;
	@BeanReference(type = ClienteLimCreditoPersistence.class)
	protected ClienteLimCreditoPersistence clienteLimCreditoPersistence;
	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteUsuarioLocalService.class)
	protected br.com.prodevelopment.cliente.service.ClienteUsuarioLocalService clienteUsuarioLocalService;
	@BeanReference(type = br.com.prodevelopment.cliente.service.ClienteUsuarioService.class)
	protected br.com.prodevelopment.cliente.service.ClienteUsuarioService clienteUsuarioService;
	@BeanReference(type = ClienteUsuarioPersistence.class)
	protected ClienteUsuarioPersistence clienteUsuarioPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ClienteLimCreditoServiceClpInvoker _clpInvoker = new ClienteLimCreditoServiceClpInvoker();
}