/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.pesquisaopiniao.model.impl;

import br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario;
import br.com.prodevelopment.pesquisaopiniao.model.Resposta_UsuarioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Resposta_Usuario service. Represents a row in the &quot;PO_Resposta_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.pesquisaopiniao.model.Resposta_UsuarioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Resposta_UsuarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Resposta_UsuarioImpl
 * @see br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario
 * @see br.com.prodevelopment.pesquisaopiniao.model.Resposta_UsuarioModel
 * @generated
 */
public class Resposta_UsuarioModelImpl extends BaseModelImpl<Resposta_Usuario>
	implements Resposta_UsuarioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resposta_ usuario model instance should use the {@link br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario} interface instead.
	 */
	public static final String TABLE_NAME = "PO_Resposta_Usuario";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "dataInclusao", Types.TIMESTAMP },
			{ "pesquisaUsuarioId", Types.BIGINT },
			{ "respostaId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table PO_Resposta_Usuario (id_ LONG not null primary key,dataInclusao DATE null,pesquisaUsuarioId LONG,respostaId LONG)";
	public static final String TABLE_SQL_DROP = "drop table PO_Resposta_Usuario";
	public static final String ORDER_BY_JPQL = " ORDER BY resposta_Usuario.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PO_Resposta_Usuario.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario"),
			true);
	public static long PESQUISAUSUARIOID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario"));

	public Resposta_UsuarioModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Resposta_Usuario.class;
	}

	public String getModelClassName() {
		return Resposta_Usuario.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("dataInclusao", getDataInclusao());
		attributes.put("pesquisaUsuarioId", getPesquisaUsuarioId());
		attributes.put("respostaId", getRespostaId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Date dataInclusao = (Date)attributes.get("dataInclusao");

		if (dataInclusao != null) {
			setDataInclusao(dataInclusao);
		}

		Long pesquisaUsuarioId = (Long)attributes.get("pesquisaUsuarioId");

		if (pesquisaUsuarioId != null) {
			setPesquisaUsuarioId(pesquisaUsuarioId);
		}

		Long respostaId = (Long)attributes.get("respostaId");

		if (respostaId != null) {
			setRespostaId(respostaId);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public Date getDataInclusao() {
		return _dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		_dataInclusao = dataInclusao;
	}

	public long getPesquisaUsuarioId() {
		return _pesquisaUsuarioId;
	}

	public void setPesquisaUsuarioId(long pesquisaUsuarioId) {
		_columnBitmask |= PESQUISAUSUARIOID_COLUMN_BITMASK;

		if (!_setOriginalPesquisaUsuarioId) {
			_setOriginalPesquisaUsuarioId = true;

			_originalPesquisaUsuarioId = _pesquisaUsuarioId;
		}

		_pesquisaUsuarioId = pesquisaUsuarioId;
	}

	public long getOriginalPesquisaUsuarioId() {
		return _originalPesquisaUsuarioId;
	}

	public long getRespostaId() {
		return _respostaId;
	}

	public void setRespostaId(long respostaId) {
		_respostaId = respostaId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Resposta_Usuario.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Resposta_Usuario toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Resposta_Usuario)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		Resposta_UsuarioImpl resposta_UsuarioImpl = new Resposta_UsuarioImpl();

		resposta_UsuarioImpl.setId(getId());
		resposta_UsuarioImpl.setDataInclusao(getDataInclusao());
		resposta_UsuarioImpl.setPesquisaUsuarioId(getPesquisaUsuarioId());
		resposta_UsuarioImpl.setRespostaId(getRespostaId());

		resposta_UsuarioImpl.resetOriginalValues();

		return resposta_UsuarioImpl;
	}

	public int compareTo(Resposta_Usuario resposta_Usuario) {
		int value = 0;

		if (getId() < resposta_Usuario.getId()) {
			value = -1;
		}
		else if (getId() > resposta_Usuario.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Resposta_Usuario resposta_Usuario = null;

		try {
			resposta_Usuario = (Resposta_Usuario)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = resposta_Usuario.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		Resposta_UsuarioModelImpl resposta_UsuarioModelImpl = this;

		resposta_UsuarioModelImpl._originalPesquisaUsuarioId = resposta_UsuarioModelImpl._pesquisaUsuarioId;

		resposta_UsuarioModelImpl._setOriginalPesquisaUsuarioId = false;

		resposta_UsuarioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Resposta_Usuario> toCacheModel() {
		Resposta_UsuarioCacheModel resposta_UsuarioCacheModel = new Resposta_UsuarioCacheModel();

		resposta_UsuarioCacheModel.id = getId();

		Date dataInclusao = getDataInclusao();

		if (dataInclusao != null) {
			resposta_UsuarioCacheModel.dataInclusao = dataInclusao.getTime();
		}
		else {
			resposta_UsuarioCacheModel.dataInclusao = Long.MIN_VALUE;
		}

		resposta_UsuarioCacheModel.pesquisaUsuarioId = getPesquisaUsuarioId();

		resposta_UsuarioCacheModel.respostaId = getRespostaId();

		return resposta_UsuarioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", dataInclusao=");
		sb.append(getDataInclusao());
		sb.append(", pesquisaUsuarioId=");
		sb.append(getPesquisaUsuarioId());
		sb.append(", respostaId=");
		sb.append(getRespostaId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append(
			"br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataInclusao</column-name><column-value><![CDATA[");
		sb.append(getDataInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pesquisaUsuarioId</column-name><column-value><![CDATA[");
		sb.append(getPesquisaUsuarioId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>respostaId</column-name><column-value><![CDATA[");
		sb.append(getRespostaId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Resposta_Usuario.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Resposta_Usuario.class
		};
	private long _id;
	private Date _dataInclusao;
	private long _pesquisaUsuarioId;
	private long _originalPesquisaUsuarioId;
	private boolean _setOriginalPesquisaUsuarioId;
	private long _respostaId;
	private long _columnBitmask;
	private Resposta_Usuario _escapedModelProxy;
}