/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.testeconhecimento.model.impl;

import br.com.prodevelopment.testeconhecimento.model.Teste;
import br.com.prodevelopment.testeconhecimento.model.TesteModel;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the Teste service. Represents a row in the &quot;TC_Teste&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link br.com.prodevelopment.testeconhecimento.model.TesteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TesteImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see TesteImpl
 * @see br.com.prodevelopment.testeconhecimento.model.Teste
 * @see br.com.prodevelopment.testeconhecimento.model.TesteModel
 * @generated
 */
public class TesteModelImpl extends BaseModelImpl<Teste> implements TesteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a teste model instance should use the {@link br.com.prodevelopment.testeconhecimento.model.Teste} interface instead.
	 */
	public static final String TABLE_NAME = "TC_Teste";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "id_", Types.BIGINT },
			{ "titulo", Types.VARCHAR },
			{ "descricao", Types.VARCHAR },
			{ "dataInclusao", Types.TIMESTAMP },
			{ "dataAlteracao", Types.TIMESTAMP },
			{ "ativo", Types.BOOLEAN },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userIdInclusao", Types.BIGINT },
			{ "userIdAlteracao", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table TC_Teste (uuid_ VARCHAR(75) null,id_ LONG not null primary key,titulo STRING null,descricao STRING null,dataInclusao DATE null,dataAlteracao DATE null,ativo BOOLEAN,companyId LONG,groupId LONG,userIdInclusao LONG,userIdAlteracao LONG)";
	public static final String TABLE_SQL_DROP = "drop table TC_Teste";
	public static final String ORDER_BY_JPQL = " ORDER BY teste.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TC_Teste.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Teste"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.br.com.prodevelopment.testeconhecimento.model.Teste"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.br.com.prodevelopment.testeconhecimento.model.Teste"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.br.com.prodevelopment.testeconhecimento.model.Teste"));

	public TesteModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Teste.class;
	}

	public String getModelClassName() {
		return Teste.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("id", getId());
		attributes.put("titulo", getTitulo());
		attributes.put("descricao", getDescricao());
		attributes.put("dataInclusao", getDataInclusao());
		attributes.put("dataAlteracao", getDataAlteracao());
		attributes.put("ativo", getAtivo());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userIdInclusao", getUserIdInclusao());
		attributes.put("userIdAlteracao", getUserIdAlteracao());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String titulo = (String)attributes.get("titulo");

		if (titulo != null) {
			setTitulo(titulo);
		}

		String descricao = (String)attributes.get("descricao");

		if (descricao != null) {
			setDescricao(descricao);
		}

		Date dataInclusao = (Date)attributes.get("dataInclusao");

		if (dataInclusao != null) {
			setDataInclusao(dataInclusao);
		}

		Date dataAlteracao = (Date)attributes.get("dataAlteracao");

		if (dataAlteracao != null) {
			setDataAlteracao(dataAlteracao);
		}

		Boolean ativo = (Boolean)attributes.get("ativo");

		if (ativo != null) {
			setAtivo(ativo);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userIdInclusao = (Long)attributes.get("userIdInclusao");

		if (userIdInclusao != null) {
			setUserIdInclusao(userIdInclusao);
		}

		Long userIdAlteracao = (Long)attributes.get("userIdAlteracao");

		if (userIdAlteracao != null) {
			setUserIdAlteracao(userIdAlteracao);
		}
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getTitulo() {
		if (_titulo == null) {
			return StringPool.BLANK;
		}
		else {
			return _titulo;
		}
	}

	public String getTitulo(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitulo(languageId);
	}

	public String getTitulo(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitulo(languageId, useDefault);
	}

	public String getTitulo(String languageId) {
		return LocalizationUtil.getLocalization(getTitulo(), languageId);
	}

	public String getTitulo(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getTitulo(), languageId,
			useDefault);
	}

	public String getTituloCurrentLanguageId() {
		return _tituloCurrentLanguageId;
	}

	@JSON
	public String getTituloCurrentValue() {
		Locale locale = getLocale(_tituloCurrentLanguageId);

		return getTitulo(locale);
	}

	public Map<Locale, String> getTituloMap() {
		return LocalizationUtil.getLocalizationMap(getTitulo());
	}

	public void setTitulo(String titulo) {
		_titulo = titulo;
	}

	public void setTitulo(String titulo, Locale locale) {
		setTitulo(titulo, locale, LocaleUtil.getDefault());
	}

	public void setTitulo(String titulo, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(titulo)) {
			setTitulo(LocalizationUtil.updateLocalization(getTitulo(),
					"Titulo", titulo, languageId, defaultLanguageId));
		}
		else {
			setTitulo(LocalizationUtil.removeLocalization(getTitulo(),
					"Titulo", languageId));
		}
	}

	public void setTituloCurrentLanguageId(String languageId) {
		_tituloCurrentLanguageId = languageId;
	}

	public void setTituloMap(Map<Locale, String> tituloMap) {
		setTituloMap(tituloMap, LocaleUtil.getDefault());
	}

	public void setTituloMap(Map<Locale, String> tituloMap, Locale defaultLocale) {
		if (tituloMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String titulo = tituloMap.get(locale);

			setTitulo(titulo, locale, defaultLocale);
		}
	}

	public String getDescricao() {
		if (_descricao == null) {
			return StringPool.BLANK;
		}
		else {
			return _descricao;
		}
	}

	public String getDescricao(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescricao(languageId);
	}

	public String getDescricao(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescricao(languageId, useDefault);
	}

	public String getDescricao(String languageId) {
		return LocalizationUtil.getLocalization(getDescricao(), languageId);
	}

	public String getDescricao(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescricao(), languageId,
			useDefault);
	}

	public String getDescricaoCurrentLanguageId() {
		return _descricaoCurrentLanguageId;
	}

	@JSON
	public String getDescricaoCurrentValue() {
		Locale locale = getLocale(_descricaoCurrentLanguageId);

		return getDescricao(locale);
	}

	public Map<Locale, String> getDescricaoMap() {
		return LocalizationUtil.getLocalizationMap(getDescricao());
	}

	public void setDescricao(String descricao) {
		_descricao = descricao;
	}

	public void setDescricao(String descricao, Locale locale) {
		setDescricao(descricao, locale, LocaleUtil.getDefault());
	}

	public void setDescricao(String descricao, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(descricao)) {
			setDescricao(LocalizationUtil.updateLocalization(getDescricao(),
					"Descricao", descricao, languageId, defaultLanguageId));
		}
		else {
			setDescricao(LocalizationUtil.removeLocalization(getDescricao(),
					"Descricao", languageId));
		}
	}

	public void setDescricaoCurrentLanguageId(String languageId) {
		_descricaoCurrentLanguageId = languageId;
	}

	public void setDescricaoMap(Map<Locale, String> descricaoMap) {
		setDescricaoMap(descricaoMap, LocaleUtil.getDefault());
	}

	public void setDescricaoMap(Map<Locale, String> descricaoMap,
		Locale defaultLocale) {
		if (descricaoMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String descricao = descricaoMap.get(locale);

			setDescricao(descricao, locale, defaultLocale);
		}
	}

	public Date getDataInclusao() {
		return _dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		_dataInclusao = dataInclusao;
	}

	public Date getDataAlteracao() {
		return _dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		_dataAlteracao = dataAlteracao;
	}

	public boolean getAtivo() {
		return _ativo;
	}

	public boolean isAtivo() {
		return _ativo;
	}

	public void setAtivo(boolean ativo) {
		_ativo = ativo;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getUserIdInclusao() {
		return _userIdInclusao;
	}

	public void setUserIdInclusao(long userIdInclusao) {
		_userIdInclusao = userIdInclusao;
	}

	public long getUserIdAlteracao() {
		return _userIdAlteracao;
	}

	public void setUserIdAlteracao(long userIdAlteracao) {
		_userIdAlteracao = userIdAlteracao;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Teste.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		setTitulo(getTitulo(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
		setDescricao(getDescricao(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
	}

	@Override
	public Teste toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Teste)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TesteImpl testeImpl = new TesteImpl();

		testeImpl.setUuid(getUuid());
		testeImpl.setId(getId());
		testeImpl.setTitulo(getTitulo());
		testeImpl.setDescricao(getDescricao());
		testeImpl.setDataInclusao(getDataInclusao());
		testeImpl.setDataAlteracao(getDataAlteracao());
		testeImpl.setAtivo(getAtivo());
		testeImpl.setCompanyId(getCompanyId());
		testeImpl.setGroupId(getGroupId());
		testeImpl.setUserIdInclusao(getUserIdInclusao());
		testeImpl.setUserIdAlteracao(getUserIdAlteracao());

		testeImpl.resetOriginalValues();

		return testeImpl;
	}

	public int compareTo(Teste teste) {
		int value = 0;

		if (getId() < teste.getId()) {
			value = -1;
		}
		else if (getId() > teste.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Teste teste = null;

		try {
			teste = (Teste)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = teste.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TesteModelImpl testeModelImpl = this;

		testeModelImpl._originalUuid = testeModelImpl._uuid;

		testeModelImpl._originalCompanyId = testeModelImpl._companyId;

		testeModelImpl._setOriginalCompanyId = false;

		testeModelImpl._originalGroupId = testeModelImpl._groupId;

		testeModelImpl._setOriginalGroupId = false;

		testeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Teste> toCacheModel() {
		TesteCacheModel testeCacheModel = new TesteCacheModel();

		testeCacheModel.uuid = getUuid();

		String uuid = testeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			testeCacheModel.uuid = null;
		}

		testeCacheModel.id = getId();

		testeCacheModel.titulo = getTitulo();

		String titulo = testeCacheModel.titulo;

		if ((titulo != null) && (titulo.length() == 0)) {
			testeCacheModel.titulo = null;
		}

		testeCacheModel.descricao = getDescricao();

		String descricao = testeCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			testeCacheModel.descricao = null;
		}

		Date dataInclusao = getDataInclusao();

		if (dataInclusao != null) {
			testeCacheModel.dataInclusao = dataInclusao.getTime();
		}
		else {
			testeCacheModel.dataInclusao = Long.MIN_VALUE;
		}

		Date dataAlteracao = getDataAlteracao();

		if (dataAlteracao != null) {
			testeCacheModel.dataAlteracao = dataAlteracao.getTime();
		}
		else {
			testeCacheModel.dataAlteracao = Long.MIN_VALUE;
		}

		testeCacheModel.ativo = getAtivo();

		testeCacheModel.companyId = getCompanyId();

		testeCacheModel.groupId = getGroupId();

		testeCacheModel.userIdInclusao = getUserIdInclusao();

		testeCacheModel.userIdAlteracao = getUserIdAlteracao();

		return testeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", titulo=");
		sb.append(getTitulo());
		sb.append(", descricao=");
		sb.append(getDescricao());
		sb.append(", dataInclusao=");
		sb.append(getDataInclusao());
		sb.append(", dataAlteracao=");
		sb.append(getDataAlteracao());
		sb.append(", ativo=");
		sb.append(getAtivo());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userIdInclusao=");
		sb.append(getUserIdInclusao());
		sb.append(", userIdAlteracao=");
		sb.append(getUserIdAlteracao());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("br.com.prodevelopment.testeconhecimento.model.Teste");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>titulo</column-name><column-value><![CDATA[");
		sb.append(getTitulo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descricao</column-name><column-value><![CDATA[");
		sb.append(getDescricao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataInclusao</column-name><column-value><![CDATA[");
		sb.append(getDataInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dataAlteracao</column-name><column-value><![CDATA[");
		sb.append(getDataAlteracao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ativo</column-name><column-value><![CDATA[");
		sb.append(getAtivo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userIdInclusao</column-name><column-value><![CDATA[");
		sb.append(getUserIdInclusao());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userIdAlteracao</column-name><column-value><![CDATA[");
		sb.append(getUserIdAlteracao());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Teste.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Teste.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _id;
	private String _titulo;
	private String _tituloCurrentLanguageId;
	private String _descricao;
	private String _descricaoCurrentLanguageId;
	private Date _dataInclusao;
	private Date _dataAlteracao;
	private boolean _ativo;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userIdInclusao;
	private long _userIdAlteracao;
	private long _columnBitmask;
	private Teste _escapedModelProxy;
}