/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.contato.model.impl;

import br.com.prodevelopment.contato.model.Endereco;
import br.com.prodevelopment.contato.service.EnderecoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Endereco service. Represents a row in the &quot;Endereco&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnderecoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see EnderecoImpl
 * @see br.com.prodevelopment.contato.model.Endereco
 * @generated
 */
public abstract class EnderecoBaseImpl extends EnderecoModelImpl
	implements Endereco {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a endereco model instance should use the {@link Endereco} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			EnderecoLocalServiceUtil.addEndereco(this);
		}
		else {
			EnderecoLocalServiceUtil.updateEndereco(this);
		}
	}
}