/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.contato.model.impl;

import br.com.prodevelopment.contato.model.Telefone;
import br.com.prodevelopment.contato.service.TelefoneLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Telefone service. Represents a row in the &quot;Telefone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TelefoneImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see TelefoneImpl
 * @see br.com.prodevelopment.contato.model.Telefone
 * @generated
 */
public abstract class TelefoneBaseImpl extends TelefoneModelImpl
	implements Telefone {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a telefone model instance should use the {@link Telefone} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TelefoneLocalServiceUtil.addTelefone(this);
		}
		else {
			TelefoneLocalServiceUtil.updateTelefone(this);
		}
	}
}