/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.pesquisaopiniao.model.impl;

import br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario;
import br.com.prodevelopment.pesquisaopiniao.service.Resposta_UsuarioLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Resposta_Usuario service. Represents a row in the &quot;PO_Resposta_Usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Resposta_UsuarioImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Resposta_UsuarioImpl
 * @see br.com.prodevelopment.pesquisaopiniao.model.Resposta_Usuario
 * @generated
 */
public abstract class Resposta_UsuarioBaseImpl extends Resposta_UsuarioModelImpl
	implements Resposta_Usuario {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a resposta_ usuario model instance should use the {@link Resposta_Usuario} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			Resposta_UsuarioLocalServiceUtil.addResposta_Usuario(this);
		}
		else {
			Resposta_UsuarioLocalServiceUtil.updateResposta_Usuario(this);
		}
	}
}