create table Cargo (
	uuid_ VARCHAR(75) null,
	cargoId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	createUserId LONG,
	modifiedUserId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	nome STRING null,
	versao DOUBLE
);

create table Funcionario (
	uuid_ VARCHAR(75) null,
	funcionarioId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	createUserId LONG,
	modifiedUserId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	nome VARCHAR(75) null,
	nomeReduzido VARCHAR(75) null,
	observacao VARCHAR(75) null,
	rg VARCHAR(75) null,
	rgOrgaoEmissor VARCHAR(75) null,
	rgDataEmissao DATE null,
	cpf VARCHAR(75) null,
	sexo VARCHAR(75) null,
	estadoCivil VARCHAR(75) null,
	dataNascimento DATE null,
	endComLogradouro VARCHAR(75) null,
	endComNumero VARCHAR(75) null,
	endComComplemento VARCHAR(75) null,
	endComCep VARCHAR(75) null,
	endComBairro VARCHAR(75) null,
	endComCidade LONG,
	endComUf VARCHAR(75) null,
	endComPais VARCHAR(75) null,
	endResLogradouro VARCHAR(75) null,
	endResNumero VARCHAR(75) null,
	endResComplemento VARCHAR(75) null,
	endResCep VARCHAR(75) null,
	endResBairro VARCHAR(75) null,
	endResCidade LONG,
	endResUf VARCHAR(75) null,
	endResPais VARCHAR(75) null,
	dataEntrada DATE null,
	dataSaida DATE null,
	existeUser BOOLEAN,
	userId LONG,
	versao DOUBLE,
	cargoId LONG,
	fotoId LONG,
	ativo BOOLEAN,
	salario DOUBLE
);