/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.testeconhecimento.service.base;

import br.com.prodevelopment.testeconhecimento.model.Teste_Usuario;
import br.com.prodevelopment.testeconhecimento.service.PerguntaLocalService;
import br.com.prodevelopment.testeconhecimento.service.RespostaLocalService;
import br.com.prodevelopment.testeconhecimento.service.Resposta_UsuarioLocalService;
import br.com.prodevelopment.testeconhecimento.service.TesteLocalService;
import br.com.prodevelopment.testeconhecimento.service.Teste_UsuarioLocalService;
import br.com.prodevelopment.testeconhecimento.service.persistence.PerguntaPersistence;
import br.com.prodevelopment.testeconhecimento.service.persistence.RespostaPersistence;
import br.com.prodevelopment.testeconhecimento.service.persistence.Resposta_UsuarioPersistence;
import br.com.prodevelopment.testeconhecimento.service.persistence.TestePersistence;
import br.com.prodevelopment.testeconhecimento.service.persistence.Teste_UsuarioPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.liferay.portlet.social.service.SocialActivityLocalService;
import com.liferay.portlet.social.service.persistence.SocialActivityPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the teste_ usuario local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link br.com.prodevelopment.testeconhecimento.service.impl.Teste_UsuarioLocalServiceImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see br.com.prodevelopment.testeconhecimento.service.impl.Teste_UsuarioLocalServiceImpl
 * @see br.com.prodevelopment.testeconhecimento.service.Teste_UsuarioLocalServiceUtil
 * @generated
 */
public abstract class Teste_UsuarioLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements Teste_UsuarioLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link br.com.prodevelopment.testeconhecimento.service.Teste_UsuarioLocalServiceUtil} to access the teste_ usuario local service.
	 */

	/**
	 * Adds the teste_ usuario to the database. Also notifies the appropriate model listeners.
	 *
	 * @param teste_Usuario the teste_ usuario
	 * @return the teste_ usuario that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Teste_Usuario addTeste_Usuario(Teste_Usuario teste_Usuario)
		throws SystemException {
		teste_Usuario.setNew(true);

		return teste_UsuarioPersistence.update(teste_Usuario, false);
	}

	/**
	 * Creates a new teste_ usuario with the primary key. Does not add the teste_ usuario to the database.
	 *
	 * @param id the primary key for the new teste_ usuario
	 * @return the new teste_ usuario
	 */
	public Teste_Usuario createTeste_Usuario(long id) {
		return teste_UsuarioPersistence.create(id);
	}

	/**
	 * Deletes the teste_ usuario with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the teste_ usuario
	 * @return the teste_ usuario that was removed
	 * @throws PortalException if a teste_ usuario with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Teste_Usuario deleteTeste_Usuario(long id)
		throws PortalException, SystemException {
		return teste_UsuarioPersistence.remove(id);
	}

	/**
	 * Deletes the teste_ usuario from the database. Also notifies the appropriate model listeners.
	 *
	 * @param teste_Usuario the teste_ usuario
	 * @return the teste_ usuario that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Teste_Usuario deleteTeste_Usuario(Teste_Usuario teste_Usuario)
		throws SystemException {
		return teste_UsuarioPersistence.remove(teste_Usuario);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Teste_Usuario.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return teste_UsuarioPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return teste_UsuarioPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return teste_UsuarioPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return teste_UsuarioPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Teste_Usuario fetchTeste_Usuario(long id) throws SystemException {
		return teste_UsuarioPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the teste_ usuario with the primary key.
	 *
	 * @param id the primary key of the teste_ usuario
	 * @return the teste_ usuario
	 * @throws PortalException if a teste_ usuario with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Teste_Usuario getTeste_Usuario(long id)
		throws PortalException, SystemException {
		return teste_UsuarioPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return teste_UsuarioPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the teste_ usuarios.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of teste_ usuarios
	 * @param end the upper bound of the range of teste_ usuarios (not inclusive)
	 * @return the range of teste_ usuarios
	 * @throws SystemException if a system exception occurred
	 */
	public List<Teste_Usuario> getTeste_Usuarios(int start, int end)
		throws SystemException {
		return teste_UsuarioPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of teste_ usuarios.
	 *
	 * @return the number of teste_ usuarios
	 * @throws SystemException if a system exception occurred
	 */
	public int getTeste_UsuariosCount() throws SystemException {
		return teste_UsuarioPersistence.countAll();
	}

	/**
	 * Updates the teste_ usuario in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param teste_Usuario the teste_ usuario
	 * @return the teste_ usuario that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Teste_Usuario updateTeste_Usuario(Teste_Usuario teste_Usuario)
		throws SystemException {
		return updateTeste_Usuario(teste_Usuario, true);
	}

	/**
	 * Updates the teste_ usuario in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param teste_Usuario the teste_ usuario
	 * @param merge whether to merge the teste_ usuario with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the teste_ usuario that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Teste_Usuario updateTeste_Usuario(Teste_Usuario teste_Usuario,
		boolean merge) throws SystemException {
		teste_Usuario.setNew(false);

		return teste_UsuarioPersistence.update(teste_Usuario, merge);
	}

	/**
	 * Returns the pergunta local service.
	 *
	 * @return the pergunta local service
	 */
	public PerguntaLocalService getPerguntaLocalService() {
		return perguntaLocalService;
	}

	/**
	 * Sets the pergunta local service.
	 *
	 * @param perguntaLocalService the pergunta local service
	 */
	public void setPerguntaLocalService(
		PerguntaLocalService perguntaLocalService) {
		this.perguntaLocalService = perguntaLocalService;
	}

	/**
	 * Returns the pergunta persistence.
	 *
	 * @return the pergunta persistence
	 */
	public PerguntaPersistence getPerguntaPersistence() {
		return perguntaPersistence;
	}

	/**
	 * Sets the pergunta persistence.
	 *
	 * @param perguntaPersistence the pergunta persistence
	 */
	public void setPerguntaPersistence(PerguntaPersistence perguntaPersistence) {
		this.perguntaPersistence = perguntaPersistence;
	}

	/**
	 * Returns the resposta local service.
	 *
	 * @return the resposta local service
	 */
	public RespostaLocalService getRespostaLocalService() {
		return respostaLocalService;
	}

	/**
	 * Sets the resposta local service.
	 *
	 * @param respostaLocalService the resposta local service
	 */
	public void setRespostaLocalService(
		RespostaLocalService respostaLocalService) {
		this.respostaLocalService = respostaLocalService;
	}

	/**
	 * Returns the resposta persistence.
	 *
	 * @return the resposta persistence
	 */
	public RespostaPersistence getRespostaPersistence() {
		return respostaPersistence;
	}

	/**
	 * Sets the resposta persistence.
	 *
	 * @param respostaPersistence the resposta persistence
	 */
	public void setRespostaPersistence(RespostaPersistence respostaPersistence) {
		this.respostaPersistence = respostaPersistence;
	}

	/**
	 * Returns the resposta_ usuario local service.
	 *
	 * @return the resposta_ usuario local service
	 */
	public Resposta_UsuarioLocalService getResposta_UsuarioLocalService() {
		return resposta_UsuarioLocalService;
	}

	/**
	 * Sets the resposta_ usuario local service.
	 *
	 * @param resposta_UsuarioLocalService the resposta_ usuario local service
	 */
	public void setResposta_UsuarioLocalService(
		Resposta_UsuarioLocalService resposta_UsuarioLocalService) {
		this.resposta_UsuarioLocalService = resposta_UsuarioLocalService;
	}

	/**
	 * Returns the resposta_ usuario persistence.
	 *
	 * @return the resposta_ usuario persistence
	 */
	public Resposta_UsuarioPersistence getResposta_UsuarioPersistence() {
		return resposta_UsuarioPersistence;
	}

	/**
	 * Sets the resposta_ usuario persistence.
	 *
	 * @param resposta_UsuarioPersistence the resposta_ usuario persistence
	 */
	public void setResposta_UsuarioPersistence(
		Resposta_UsuarioPersistence resposta_UsuarioPersistence) {
		this.resposta_UsuarioPersistence = resposta_UsuarioPersistence;
	}

	/**
	 * Returns the teste local service.
	 *
	 * @return the teste local service
	 */
	public TesteLocalService getTesteLocalService() {
		return testeLocalService;
	}

	/**
	 * Sets the teste local service.
	 *
	 * @param testeLocalService the teste local service
	 */
	public void setTesteLocalService(TesteLocalService testeLocalService) {
		this.testeLocalService = testeLocalService;
	}

	/**
	 * Returns the teste persistence.
	 *
	 * @return the teste persistence
	 */
	public TestePersistence getTestePersistence() {
		return testePersistence;
	}

	/**
	 * Sets the teste persistence.
	 *
	 * @param testePersistence the teste persistence
	 */
	public void setTestePersistence(TestePersistence testePersistence) {
		this.testePersistence = testePersistence;
	}

	/**
	 * Returns the teste_ usuario local service.
	 *
	 * @return the teste_ usuario local service
	 */
	public Teste_UsuarioLocalService getTeste_UsuarioLocalService() {
		return teste_UsuarioLocalService;
	}

	/**
	 * Sets the teste_ usuario local service.
	 *
	 * @param teste_UsuarioLocalService the teste_ usuario local service
	 */
	public void setTeste_UsuarioLocalService(
		Teste_UsuarioLocalService teste_UsuarioLocalService) {
		this.teste_UsuarioLocalService = teste_UsuarioLocalService;
	}

	/**
	 * Returns the teste_ usuario persistence.
	 *
	 * @return the teste_ usuario persistence
	 */
	public Teste_UsuarioPersistence getTeste_UsuarioPersistence() {
		return teste_UsuarioPersistence;
	}

	/**
	 * Sets the teste_ usuario persistence.
	 *
	 * @param teste_UsuarioPersistence the teste_ usuario persistence
	 */
	public void setTeste_UsuarioPersistence(
		Teste_UsuarioPersistence teste_UsuarioPersistence) {
		this.teste_UsuarioPersistence = teste_UsuarioPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the social activity local service.
	 *
	 * @return the social activity local service
	 */
	public SocialActivityLocalService getSocialActivityLocalService() {
		return socialActivityLocalService;
	}

	/**
	 * Sets the social activity local service.
	 *
	 * @param socialActivityLocalService the social activity local service
	 */
	public void setSocialActivityLocalService(
		SocialActivityLocalService socialActivityLocalService) {
		this.socialActivityLocalService = socialActivityLocalService;
	}

	/**
	 * Returns the social activity persistence.
	 *
	 * @return the social activity persistence
	 */
	public SocialActivityPersistence getSocialActivityPersistence() {
		return socialActivityPersistence;
	}

	/**
	 * Sets the social activity persistence.
	 *
	 * @param socialActivityPersistence the social activity persistence
	 */
	public void setSocialActivityPersistence(
		SocialActivityPersistence socialActivityPersistence) {
		this.socialActivityPersistence = socialActivityPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("br.com.prodevelopment.testeconhecimento.model.Teste_Usuario",
			teste_UsuarioLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"br.com.prodevelopment.testeconhecimento.model.Teste_Usuario");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return Teste_Usuario.class;
	}

	protected String getModelClassName() {
		return Teste_Usuario.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = teste_UsuarioPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = PerguntaLocalService.class)
	protected PerguntaLocalService perguntaLocalService;
	@BeanReference(type = PerguntaPersistence.class)
	protected PerguntaPersistence perguntaPersistence;
	@BeanReference(type = RespostaLocalService.class)
	protected RespostaLocalService respostaLocalService;
	@BeanReference(type = RespostaPersistence.class)
	protected RespostaPersistence respostaPersistence;
	@BeanReference(type = Resposta_UsuarioLocalService.class)
	protected Resposta_UsuarioLocalService resposta_UsuarioLocalService;
	@BeanReference(type = Resposta_UsuarioPersistence.class)
	protected Resposta_UsuarioPersistence resposta_UsuarioPersistence;
	@BeanReference(type = TesteLocalService.class)
	protected TesteLocalService testeLocalService;
	@BeanReference(type = TestePersistence.class)
	protected TestePersistence testePersistence;
	@BeanReference(type = Teste_UsuarioLocalService.class)
	protected Teste_UsuarioLocalService teste_UsuarioLocalService;
	@BeanReference(type = Teste_UsuarioPersistence.class)
	protected Teste_UsuarioPersistence teste_UsuarioPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@BeanReference(type = SocialActivityLocalService.class)
	protected SocialActivityLocalService socialActivityLocalService;
	@BeanReference(type = SocialActivityPersistence.class)
	protected SocialActivityPersistence socialActivityPersistence;
	private String _beanIdentifier;
	private Teste_UsuarioLocalServiceClpInvoker _clpInvoker = new Teste_UsuarioLocalServiceClpInvoker();
}