/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.contato.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Contato service. Represents a row in the &quot;Contato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.contato.model.impl.ContatoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.contato.model.impl.ContatoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Contato
 * @see br.com.prodevelopment.contato.model.impl.ContatoImpl
 * @see br.com.prodevelopment.contato.model.impl.ContatoModelImpl
 * @generated
 */
public interface ContatoModel extends AttachedModel, BaseModel<Contato> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contato model instance should use the {@link Contato} interface instead.
	 */

	/**
	 * Returns the primary key of this contato.
	 *
	 * @return the primary key of this contato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contato.
	 *
	 * @param primaryKey the primary key of this contato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contato ID of this contato.
	 *
	 * @return the contato ID of this contato
	 */
	public long getContatoId();

	/**
	 * Sets the contato ID of this contato.
	 *
	 * @param contatoId the contato ID of this contato
	 */
	public void setContatoId(long contatoId);

	/**
	 * Returns the company ID of this contato.
	 *
	 * @return the company ID of this contato
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this contato.
	 *
	 * @param companyId the company ID of this contato
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this contato.
	 *
	 * @return the group ID of this contato
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this contato.
	 *
	 * @param groupId the group ID of this contato
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this contato.
	 *
	 * @return the create user ID of this contato
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this contato.
	 *
	 * @param createUserId the create user ID of this contato
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this contato.
	 *
	 * @return the create user uuid of this contato
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this contato.
	 *
	 * @param createUserUuid the create user uuid of this contato
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this contato.
	 *
	 * @return the modified user ID of this contato
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this contato.
	 *
	 * @param modifiedUserId the modified user ID of this contato
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this contato.
	 *
	 * @return the modified user uuid of this contato
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this contato.
	 *
	 * @param modifiedUserUuid the modified user uuid of this contato
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this contato.
	 *
	 * @return the create date of this contato
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this contato.
	 *
	 * @param createDate the create date of this contato
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contato.
	 *
	 * @return the modified date of this contato
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contato.
	 *
	 * @param modifiedDate the modified date of this contato
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this contato.
	 *
	 * @return the fully qualified class name of this contato
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this contato.
	 *
	 * @return the class name ID of this contato
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this contato.
	 *
	 * @param classNameId the class name ID of this contato
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this contato.
	 *
	 * @return the class p k of this contato
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this contato.
	 *
	 * @param classPK the class p k of this contato
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the account ID of this contato.
	 *
	 * @return the account ID of this contato
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this contato.
	 *
	 * @param accountId the account ID of this contato
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the end email of this contato.
	 *
	 * @return the end email of this contato
	 */
	@AutoEscape
	public String getEndEmail();

	/**
	 * Sets the end email of this contato.
	 *
	 * @param endEmail the end email of this contato
	 */
	public void setEndEmail(String endEmail);

	/**
	 * Returns the nome of this contato.
	 *
	 * @return the nome of this contato
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this contato.
	 *
	 * @param nome the nome of this contato
	 */
	public void setNome(String nome);

	/**
	 * Returns the sexo of this contato.
	 *
	 * @return the sexo of this contato
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this contato.
	 *
	 * @param sexo the sexo of this contato
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the data nascimento of this contato.
	 *
	 * @return the data nascimento of this contato
	 */
	public Date getDataNascimento();

	/**
	 * Sets the data nascimento of this contato.
	 *
	 * @param dataNascimento the data nascimento of this contato
	 */
	public void setDataNascimento(Date dataNascimento);

	/**
	 * Returns the cargo ID of this contato.
	 *
	 * @return the cargo ID of this contato
	 */
	public long getCargoId();

	/**
	 * Sets the cargo ID of this contato.
	 *
	 * @param cargoId the cargo ID of this contato
	 */
	public void setCargoId(long cargoId);

	/**
	 * Returns the skype of this contato.
	 *
	 * @return the skype of this contato
	 */
	@AutoEscape
	public String getSkype();

	/**
	 * Sets the skype of this contato.
	 *
	 * @param skype the skype of this contato
	 */
	public void setSkype(String skype);

	/**
	 * Returns the facebook of this contato.
	 *
	 * @return the facebook of this contato
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this contato.
	 *
	 * @param facebook the facebook of this contato
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the twitter of this contato.
	 *
	 * @return the twitter of this contato
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this contato.
	 *
	 * @param twitter the twitter of this contato
	 */
	public void setTwitter(String twitter);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(br.com.prodevelopment.contato.model.Contato contato);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.contato.model.Contato> toCacheModel();

	@Override
	public br.com.prodevelopment.contato.model.Contato toEscapedModel();

	@Override
	public br.com.prodevelopment.contato.model.Contato toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}