/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package br.com.prodevelopment.contato.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Endereco service. Represents a row in the &quot;Endereco&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.contato.model.impl.EnderecoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.contato.model.impl.EnderecoImpl}.
 * </p>
 *
 * @author Marcelo Melo
 * @see Endereco
 * @see br.com.prodevelopment.contato.model.impl.EnderecoImpl
 * @see br.com.prodevelopment.contato.model.impl.EnderecoModelImpl
 * @generated
 */
public interface EnderecoModel extends AttachedModel, BaseModel<Endereco>,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a endereco model instance should use the {@link Endereco} interface instead.
	 */

	/**
	 * Returns the primary key of this endereco.
	 *
	 * @return the primary key of this endereco
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this endereco.
	 *
	 * @param primaryKey the primary key of this endereco
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this endereco.
	 *
	 * @return the uuid of this endereco
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this endereco.
	 *
	 * @param uuid the uuid of this endereco
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the endereco ID of this endereco.
	 *
	 * @return the endereco ID of this endereco
	 */
	public long getEnderecoId();

	/**
	 * Sets the endereco ID of this endereco.
	 *
	 * @param enderecoId the endereco ID of this endereco
	 */
	public void setEnderecoId(long enderecoId);

	/**
	 * Returns the company ID of this endereco.
	 *
	 * @return the company ID of this endereco
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this endereco.
	 *
	 * @param companyId the company ID of this endereco
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this endereco.
	 *
	 * @return the group ID of this endereco
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this endereco.
	 *
	 * @param groupId the group ID of this endereco
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this endereco.
	 *
	 * @return the create user ID of this endereco
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this endereco.
	 *
	 * @param createUserId the create user ID of this endereco
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this endereco.
	 *
	 * @return the create user uuid of this endereco
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this endereco.
	 *
	 * @param createUserUuid the create user uuid of this endereco
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this endereco.
	 *
	 * @return the modified user ID of this endereco
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this endereco.
	 *
	 * @param modifiedUserId the modified user ID of this endereco
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this endereco.
	 *
	 * @return the modified user uuid of this endereco
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this endereco.
	 *
	 * @param modifiedUserUuid the modified user uuid of this endereco
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this endereco.
	 *
	 * @return the create date of this endereco
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this endereco.
	 *
	 * @param createDate the create date of this endereco
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this endereco.
	 *
	 * @return the modified date of this endereco
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this endereco.
	 *
	 * @param modifiedDate the modified date of this endereco
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this endereco.
	 *
	 * @return the fully qualified class name of this endereco
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this endereco.
	 *
	 * @return the class name ID of this endereco
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this endereco.
	 *
	 * @param classNameId the class name ID of this endereco
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this endereco.
	 *
	 * @return the class p k of this endereco
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this endereco.
	 *
	 * @param classPK the class p k of this endereco
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the logradouro of this endereco.
	 *
	 * @return the logradouro of this endereco
	 */
	@AutoEscape
	public String getLogradouro();

	/**
	 * Sets the logradouro of this endereco.
	 *
	 * @param logradouro the logradouro of this endereco
	 */
	public void setLogradouro(String logradouro);

	/**
	 * Returns the numero of this endereco.
	 *
	 * @return the numero of this endereco
	 */
	@AutoEscape
	public String getNumero();

	/**
	 * Sets the numero of this endereco.
	 *
	 * @param numero the numero of this endereco
	 */
	public void setNumero(String numero);

	/**
	 * Returns the complemento of this endereco.
	 *
	 * @return the complemento of this endereco
	 */
	@AutoEscape
	public String getComplemento();

	/**
	 * Sets the complemento of this endereco.
	 *
	 * @param complemento the complemento of this endereco
	 */
	public void setComplemento(String complemento);

	/**
	 * Returns the cep of this endereco.
	 *
	 * @return the cep of this endereco
	 */
	@AutoEscape
	public String getCep();

	/**
	 * Sets the cep of this endereco.
	 *
	 * @param cep the cep of this endereco
	 */
	public void setCep(String cep);

	/**
	 * Returns the bairro of this endereco.
	 *
	 * @return the bairro of this endereco
	 */
	@AutoEscape
	public String getBairro();

	/**
	 * Sets the bairro of this endereco.
	 *
	 * @param bairro the bairro of this endereco
	 */
	public void setBairro(String bairro);

	/**
	 * Returns the cidade ID of this endereco.
	 *
	 * @return the cidade ID of this endereco
	 */
	public long getCidadeId();

	/**
	 * Sets the cidade ID of this endereco.
	 *
	 * @param cidadeId the cidade ID of this endereco
	 */
	public void setCidadeId(long cidadeId);

	/**
	 * Returns the uf of this endereco.
	 *
	 * @return the uf of this endereco
	 */
	@AutoEscape
	public String getUf();

	/**
	 * Sets the uf of this endereco.
	 *
	 * @param uf the uf of this endereco
	 */
	public void setUf(String uf);

	/**
	 * Returns the pais ID of this endereco.
	 *
	 * @return the pais ID of this endereco
	 */
	public long getPaisId();

	/**
	 * Sets the pais ID of this endereco.
	 *
	 * @param paisId the pais ID of this endereco
	 */
	public void setPaisId(long paisId);

	/**
	 * Returns the principal of this endereco.
	 *
	 * @return the principal of this endereco
	 */
	public boolean getPrincipal();

	/**
	 * Returns <code>true</code> if this endereco is principal.
	 *
	 * @return <code>true</code> if this endereco is principal; <code>false</code> otherwise
	 */
	public boolean isPrincipal();

	/**
	 * Sets whether this endereco is principal.
	 *
	 * @param principal the principal of this endereco
	 */
	public void setPrincipal(boolean principal);

	/**
	 * Returns the tipo of this endereco.
	 *
	 * @return the tipo of this endereco
	 */
	public int getTipo();

	/**
	 * Sets the tipo of this endereco.
	 *
	 * @param tipo the tipo of this endereco
	 */
	public void setTipo(int tipo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(br.com.prodevelopment.contato.model.Endereco endereco);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.prodevelopment.contato.model.Endereco> toCacheModel();

	@Override
	public br.com.prodevelopment.contato.model.Endereco toEscapedModel();

	@Override
	public br.com.prodevelopment.contato.model.Endereco toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}