/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.prodevelopment.contato.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Telefone service. Represents a row in the &quot;Telefone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.prodevelopment.contato.model.impl.TelefoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.prodevelopment.contato.model.impl.TelefoneImpl}.
 * </p>
 *
 * @author marcelo
 * @see Telefone
 * @see br.com.prodevelopment.contato.model.impl.TelefoneImpl
 * @see br.com.prodevelopment.contato.model.impl.TelefoneModelImpl
 * @generated
 */
public interface TelefoneModel extends AttachedModel, BaseModel<Telefone>,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a telefone model instance should use the {@link Telefone} interface instead.
	 */

	/**
	 * Returns the primary key of this telefone.
	 *
	 * @return the primary key of this telefone
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this telefone.
	 *
	 * @param primaryKey the primary key of this telefone
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this telefone.
	 *
	 * @return the uuid of this telefone
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this telefone.
	 *
	 * @param uuid the uuid of this telefone
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the telefone ID of this telefone.
	 *
	 * @return the telefone ID of this telefone
	 */
	public long getTelefoneId();

	/**
	 * Sets the telefone ID of this telefone.
	 *
	 * @param telefoneId the telefone ID of this telefone
	 */
	public void setTelefoneId(long telefoneId);

	/**
	 * Returns the company ID of this telefone.
	 *
	 * @return the company ID of this telefone
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this telefone.
	 *
	 * @param companyId the company ID of this telefone
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this telefone.
	 *
	 * @return the group ID of this telefone
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this telefone.
	 *
	 * @param groupId the group ID of this telefone
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create user ID of this telefone.
	 *
	 * @return the create user ID of this telefone
	 */
	public long getCreateUserId();

	/**
	 * Sets the create user ID of this telefone.
	 *
	 * @param createUserId the create user ID of this telefone
	 */
	public void setCreateUserId(long createUserId);

	/**
	 * Returns the create user uuid of this telefone.
	 *
	 * @return the create user uuid of this telefone
	 * @throws SystemException if a system exception occurred
	 */
	public String getCreateUserUuid() throws SystemException;

	/**
	 * Sets the create user uuid of this telefone.
	 *
	 * @param createUserUuid the create user uuid of this telefone
	 */
	public void setCreateUserUuid(String createUserUuid);

	/**
	 * Returns the modified user ID of this telefone.
	 *
	 * @return the modified user ID of this telefone
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this telefone.
	 *
	 * @param modifiedUserId the modified user ID of this telefone
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this telefone.
	 *
	 * @return the modified user uuid of this telefone
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this telefone.
	 *
	 * @param modifiedUserUuid the modified user uuid of this telefone
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the create date of this telefone.
	 *
	 * @return the create date of this telefone
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this telefone.
	 *
	 * @param createDate the create date of this telefone
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this telefone.
	 *
	 * @return the modified date of this telefone
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this telefone.
	 *
	 * @param modifiedDate the modified date of this telefone
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this telefone.
	 *
	 * @return the fully qualified class name of this telefone
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this telefone.
	 *
	 * @return the class name ID of this telefone
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this telefone.
	 *
	 * @param classNameId the class name ID of this telefone
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this telefone.
	 *
	 * @return the class p k of this telefone
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this telefone.
	 *
	 * @param classPK the class p k of this telefone
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the ddi of this telefone.
	 *
	 * @return the ddi of this telefone
	 */
	@AutoEscape
	public String getDdi();

	/**
	 * Sets the ddi of this telefone.
	 *
	 * @param ddi the ddi of this telefone
	 */
	public void setDdi(String ddi);

	/**
	 * Returns the ddd of this telefone.
	 *
	 * @return the ddd of this telefone
	 */
	@AutoEscape
	public String getDdd();

	/**
	 * Sets the ddd of this telefone.
	 *
	 * @param ddd the ddd of this telefone
	 */
	public void setDdd(String ddd);

	/**
	 * Returns the numero of this telefone.
	 *
	 * @return the numero of this telefone
	 */
	@AutoEscape
	public String getNumero();

	/**
	 * Sets the numero of this telefone.
	 *
	 * @param numero the numero of this telefone
	 */
	public void setNumero(String numero);

	/**
	 * Returns the ramal of this telefone.
	 *
	 * @return the ramal of this telefone
	 */
	@AutoEscape
	public String getRamal();

	/**
	 * Sets the ramal of this telefone.
	 *
	 * @param ramal the ramal of this telefone
	 */
	public void setRamal(String ramal);

	/**
	 * Returns the tipo of this telefone.
	 *
	 * @return the tipo of this telefone
	 */
	public int getTipo();

	/**
	 * Sets the tipo of this telefone.
	 *
	 * @param tipo the tipo of this telefone
	 */
	public void setTipo(int tipo);

	/**
	 * Returns the principal of this telefone.
	 *
	 * @return the principal of this telefone
	 */
	public boolean getPrincipal();

	/**
	 * Returns <code>true</code> if this telefone is principal.
	 *
	 * @return <code>true</code> if this telefone is principal; <code>false</code> otherwise
	 */
	public boolean isPrincipal();

	/**
	 * Sets whether this telefone is principal.
	 *
	 * @param principal the principal of this telefone
	 */
	public void setPrincipal(boolean principal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Telefone telefone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Telefone> toCacheModel();

	@Override
	public Telefone toEscapedModel();

	@Override
	public Telefone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}